### ISSUE TITLE
Add "donations" info to docs

### ISSUE THREAD

**Issue by thd6n75** [AppDaemon/appdaemon#1005]
Andrew and team, I'd like to support the development of Appdaemon by donating $$.  I couldn't find any info on https://appdaemon.readthedocs.io/en/latest/# - could you please add some information to the front page about how we can support this project?  Paypal is often an easy choice for folks.  Having "bug bounties" to add a little weight to issue prioritization would also be a cool thing to have but that is very much a secondary request.

Thanks for the fantastic app.  I've been using Appdaemon for about 2 years and I'm still awed by the fact that I can automate my house with a few lines of python.

**Comment by Odianosen25** [comment]
@thd6n75,

Thanks for the offer, but there is no plan as at now for this to be done. But the very fact you appreciate the work, spearheaded by @acockburn really is cool, and thanks. 

Keep enjoying automating.
