### ISSUE TITLE
run_in callbacks not removed from Admin Interface

### ISSUE THREAD

**Issue by roflcoopter** [AppDaemon/appdaemon#1007]
I have an issue with run_in and the Admin Interface. Running latest AD 4.0.4
I have several apps that use run_in to schedule actions, for example one that loops through lovelace views with service calls on a dashboard.

If you run this example app and check under Callbacks in the Admin Interface you can see that every occurence of the run_in callback remains in the list, which eventually makes the entire interface stop responding.

```yaml
RunInTest:
  module: run_in_test
  class: RunInTest
```
```python
import hassapi as hass


class RunInTest(hass.Hass):
    def initialize(self):
        self.callback({})

    def callback(self, kwargs):
        self.log("Hi there")
        self.run_in(self.callback, 10)
```

And this is what it looks like, all times are in the past
App | Execution Time | Repeat | Callback | Fired | Executed | Pinned | Thread | Kwargs
-- | -- | -- | -- | -- | -- | -- | -- | --
RunInTest | 2020-07-17T11:23:52+02:00 | 0:00:00 | callback | 1 | 1 | true | 0 | {}
RunInTest | 2020-07-17T11:24:02+02:00 | 0:00:00 | callback | 1 | 1 | true | 0 | {}
RunInTest | 2020-07-17T11:24:12+02:00 | 0:00:00 | callback | 1 | 1 | true | 0 | {}
RunInTest | 2020-07-17T11:24:22+02:00 | 0:00:00 | callback | 1 | 1 | true | 0 | {}
RunInTest | 2020-07-17T11:24:32+02:00 | 0:00:00 | callback | 1 | 1 | true | 0 | {}
RunInTest | 2020-07-17T11:24:42+02:00 | 0:00:00 | callback | 1 | 1 | true | 0 | {}
RunInTest | 2020-07-17T11:24:52+02:00 | 0:00:00 | callback | 1 | 1 | true | 0 | {}
RunInTest | 2020-07-17T11:25:02+02:00 | 0:00:00 | callback | 1 | 1 | true | 0 | {}
RunInTest | 2020-07-17T11:25:12+02:00 | 0:00:00 | callback | 1 | 1 | true | 0 | {}
RunInTest | 2020-07-17T11:25:22+02:00 | 0:00:00 | callback | 1 | 1 | true | 0 | {}
RunInTest | 2020-07-17T11:25:32+02:00 | 0:00:00 | callback | 1 | 1 | true | 0 | {}
RunInTest | 2020-07-17T11:25:42+02:00 | 0:00:00 | callback | 1 | 1 | true | 0 | {}

Is this an error or by design?

**Comment by Odianosen25** [comment]
@roflcoopter,

When this happens, did you refresh the page and its still same? Sometimes even when entities are removed from the AI, it still shows until the page is refreshed. Its not as real-time as one would have loved

Regards

**Comment by roflcoopter** [comment]
@Odianosen25 
Yes, it actually gets worse after a refresh, more of them pops up.
The issues is that after a day or so the UI gets so slow to load that appdaemon has to be restarted to clear up all the callbacks

**Comment by ReneTode** [comment]
thats the problem i pointed out to you @Odianosen25 
thats why i cant upgrade.

**Comment by Odianosen25** [comment]
@roflcoopter,

I have ran your test code, and I can  confirm its as I described above. I do admit the AI is not as responsive in real-time removing removed scheduled entities, and you will notice the same when using the `remove_entity` api for any other entity. 

The scheduler is being removed, but will only be noticed after a refresh. This is evident as in your test, you have the scheduler writing to log, so if it wasn't clearing the scheduler entity, the same number of `RunInTest: Hi there` as in the log, will always be same on the AI, but it is not the case. Yes it builds up after refresh, but that is when one is using a lot of run_ins at once.

The AI needs more work, and as ReneTode eluded to its on our radar, but bare with us a while longer until we get sometime to work on the re-modelling of the AI so this can be fixed.

regards

**Comment by Odianosen25** [comment]
@roflcoopter,

Based on the picture you gave, I honestly can't find the bug. All I had was a single entry for `RunInTest`, and it disappears and reappears each time the schedule was executed and a new one started.

On the other hand, I can  confirm its as I described above. I do admit the AI is not as responsive in real-time removing removed scheduled entities, and you will notice the same when using the `remove_entity` api for any other entity. 

The scheduler is being removed, but will only be noticed after a refresh. This is evident as in your test, you have the scheduler writing to log, so if it wasn't clearing the scheduler entity, the same number of `RunInTest: Hi there` as in the log, will always be same on the AI, but it is not the case. Yes it builds up after refresh, but that is when one is using a lot of run_ins at once.

The AI needs more work, and as ReneTode eluded to its on our radar, but as per your bug, nope I didn't notice it.

Regards

**Comment by ReneTode** [comment]
> The scheduler is being removed, but will only be noticed after a refresh.

i read his answer the same as my experience.
refreshing doesnt remove it.
the amount grows and grows, and with my amount off callbacks in a few hours AD starts having trouble.

when i tested it the amount grew to a few thousand callbacks in a few hours.

not only the AI is affected, memory grows also. and AD slows down.
this is a severe problem.

**Comment by Odianosen25** [comment]
Hmmmm, that’s interesting as I am not exactly getting the same thing. I admit without a refresh it does grow. But after a refresh it starts again and grows. But this is for only the entities created by the scheduler.

As per his entry which is within the apps tab, what he described I still don’t get it. I am on the latest dev presently as I thought it was maybe because I hadn’t upgraded after the release; but I am not getting it.

@acockburn can you weigh in on this, and any thoughts on your side?

Regards

**Comment by ReneTode** [comment]
it was in marz that i tested it, and i asked you to try and you needed to update, remember?
then i stepped back to a dev from februar.

i did check if it was the AI only.
i looked up the schedular entities in the AI and afterwards in a test app i checked if that entity existed.
even hours after it had run, the entity still existed.

so i am 100% sure its not an AI problem, but its somewhere in AD.

**Comment by ReneTode** [comment]
to help i can tell you that the problem isnt there in the dev that i downloaded on 25-2-2020
so its a change after that time that created the trouble.

and the problem was there when i tried to update the dev on 29-3-2020

so a change somewhere between those dates is responsible.

**Comment by Odianosen25** [comment]
Ok I am officially confused which is ironic being a dev. Until @acockburn responds, I really don't know what to say. I will keep testing, and update when I find something else.

**Comment by acockburn** [comment]
Hi all - thanks for the analysis so far. I have taken a look and am seeing the issue. It seems like a couple of related bugs. I have fixed one, and will put that in dev, which will prevent the callbacks building up in the AUI, but they are still building up somewhere else as you get a bunch more when you reload.

Watch this space!

**Comment by roflcoopter** [comment]
Thanks for looking in to it! I am away til monday, i can provide more details then if necessary

**Comment by acockburn** [comment]
Just commited the second fix to dev if anyone wants to try it out - I'll push a new AD release with the fix next weekend when I return home if I can get some verification that this fix worked

**Comment by roflcoopter** [comment]
Sorry this took so long but i finally got around to updating and testing. Works great!
Thanks a lot.
