### ISSUE TITLE
Setting gauge widget low, med, high color

### ISSUE THREAD

**Issue by grubis** [AppDaemon/appdaemon#1010]
Instructions are not clear on how to set the Low_Color, Med_Color and High_Color:
"Note that unlike other widgets, the color settings require an actual color, rather than a CSS style."
I've tried "green", "#00ff00", calling an rgba function... not sure how this feature works. Also, how are the low, med, high ranges defined.

**Comment by acockburn** [comment]
The latest (dev) docs have been fixed to add this information.
