### ISSUE TITLE
AttributeError: module 'serial' has no attribute 'Serial'

### ISSUE THREAD

**Issue by mishave** [AppDaemon/appdaemon#1020]
Running:
```
 Add-on: AppDaemon 4
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.2.6
 You are running the latest version of this add-on.
 System: Raspbian GNU/Linux 10 (buster)  (armv7 / raspberrypi4)
 Home Assistant Core: 0.113.1
 Home Assistant Supervisor: 229
```

Appdaemon config:
```
system_packages: []
python_packages:
  - hass-apps
  - gspread
  - oauth2client
  - apiclient
  - pyserial
init_commands: []

```

Unable to execute serial through Appdaemon using pyserial

getting the follwoing error:
```
  File "/config/appdaemon/apps/serial.py", line 11, in initialize
    ser = serial.Serial(
AttributeError: module 'serial' has no attribute 'Serial'
```

code being used is:
```
import appdaemon.plugins.hass.hassapi as hass
import serial

class SerialCall(hass.Hass):



  def initialize(self):
    self.log("openSerial")

    ser = serial.Serial(
        port = '/dev/ttyACM0',
        baudrate = 9600,                # 9600 bauds
        bytesize = serial.SEVENBITS,    # 7bits
        parity = serial.PARITY_EVEN,    # even parity
        stopbits = serial.STOPBITS_ONE, # 1 stop bit
        xonxoff = False,                # no flow control
        timeout = 1
        )
    self.log("yep")
    for i in range(10):
        # read a data line
        x = ser.readline()
        # clean the string
        x = x.decode('utf-8').rstrip()
        # split the fields
        c=x.split(' ')
        # log (for the moment) one of the data
        if c[0] == "STINTS":
            self.log("%s: %s", c[0], c[1])

    ser.close()
```

**Comment by ReneTode** [comment]
this is not a problem from appdaemon but from the addon.
for that you need to ask frenck who created the addon.

**Comment by mishave** [comment]
> this is not a problem from appdaemon but from the addon.
> for that you need to ask frenck who created the addon.

Interesting, would you happen to have a serial library suggestion that works with AppDaemon?

**Comment by ReneTode** [comment]
hmm, i was to fast.
in the past the hassio addon docker didnt have access to the serial port (i dont know if that is changed now)
thats why i reffered to the creator from the addon.

but looking at it closer its probably a python error that you made.

you called your py file serial. and you import serial.
the result is that you import your own file and not the library.

rename your py file and the import will go as expected and the attribute error should disappear.
(and if access to the serial port is openened for the addon you should get access to it)

**Comment by mishave** [comment]
thanks again @ReneTode no luck as of yet when changing the naming system. I might get started command_line as a workaround in case I don't hear anything back. 

Also good pick up forgot to add the version 4 there.

https://community.home-assistant.io/t/home-assistant-community-add-on-appdaemon-4/163259/70?u=mishavee indicates that in Release v0.2.0 access was given to the serial ports perhaps its the way I'm going about the implementation.

@frenck are you able to shed some light on this?

Also while I'm at it if I want to use a library native to python i.e. JSON I should be able to implement this via import json at the start right? without the need to include it in the configuration as it's included in python. that's another kettle of fish to work on if I get pass this.

**Comment by ReneTode** [comment]
did you restart AD after you renamed the file?
and did the error change? (it should at least have changed a bit)

because im pretty sure that it is your import that goes wrong.

indeed you can use native python libs just by importing.

**Comment by mishave** [comment]
@ReneTode thank you for following that up, I just gave it another crack and its kicked off with no issues, I think you may have hit the nail on the head with the naming issues. I appropriately name it:

```
HopesAndDreams:
    module: whyIsSerialDumb
    class: pleaseWork
```

with the follwoing code:
```
import appdaemon.plugins.hass.hassapi as hass
import serial
import json

class pleaseWork(hass.Hass):



  def initialize(self):
    self.log("openSerial")
    ser = serial.Serial(
        port = '/dev/ttyACM0',
        baudrate = 9600,                # 9600 bauds
        bytesize = serial.SEVENBITS,    # 7bits
        parity = serial.PARITY_EVEN,    # even parity
        stopbits = serial.STOPBITS_ONE, # 1 stop bit
        xonxoff = False,                # no flow control
        timeout = 1
        )
    buffer = ""
    
    while True:
        try:
                buffer = ser.readline()
                self.log(buffer)
                doc = json.loads(buffer)
    
                read_b1 = doc["b1"]
                read_b2 = doc["b2"]
    
                read_s1 = doc["s1"]
                read_s2 = doc["s2"]
                
                self.log(read_b1)
                buffer = ""
        except json.JSONDecodeError:
                self.log("Error : try to parse an incomplete message")
```

and everything is working just fine. spent a solid three days on that!

Thought I should post the code in case anyone else is having the same issue :)

**Comment by mishave** [comment]
as @ReneTode pointed out the file naming issue, after correcting I had to restart Appdaemon and the server.
