### ISSUE TITLE
Docker hub 'latest' tag not pointing to latest release.

### ISSUE THREAD

**Issue by aneisch** [AppDaemon/appdaemon#1026]
Unsure if this is intentional, but the `latest` tag is currently the `4.0.3` build.

**Comment by acockburn** [comment]
I just released 4.0.5 - could you check if it is fixed now please?

**Comment by aneisch** [comment]
It doesn't appear to be fixed. 

IMAGE: latest
Last updated: 5 months ago by acockburn
DIGEST: b3929a881e8d
OS/ARCH: linux/amd64
COMPRESSED SIZE: 118.64 MB

**Comment by Tuckie** [comment]
Same problem for me: https://hub.docker.com/r/acockburn/appdaemon/tags?page=1&name=latest

**Comment by sillyfrog** [comment]
I also came across this - went to fix an issue and realized it was already fixed, just `latest` was not pointing to `4.0.5`.

**Comment by clyra** [comment]
+1. same problem here. I had to use acockburn/appdaemon:4.0.5 to get the real latest one.

**Comment by acockburn** [comment]
This should be fixed now,
