### ISSUE TITLE
Run_minutely et al failing

### ISSUE THREAD

**Issue by GeoffCampbell** [AppDaemon/appdaemon#1029]
I have various methods that I want to call on a timed basis, using the run_minutely/run_hourly/run_daily functions. Every time the system hits a trigger time, I get a whole slew of errors in the log regarding deprecated calls.

I'm quite open to this being a coding error on my part. I'm pretty new to both Python and AppDaemon (although not to programming more generally), but I've puzzled over it for several days without getting anywhere.

>>> Expected behaviour

My test code looks like this, which should fire once a minute and log the current time:

class OctopusTestbed(hass.Hass):

def initialize(self):
    self.log("Octopus scheduled test initialising...")
    ts_start = datetime.time(8, 6, 0)
    self.run_minutely(self.Scheduled(), ts_start)
    
def Scheduled(self):
    ts_now = datetime.datetime.now()
    self.log("Scheduled task run at: " + str(ts_now))

>>> Actual behaviour

What I see in the logs at the first trigger time is this:

/usr/lib/python3.8/site-packages/appdaemon/main.py:133: DeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead
pending = asyncio.Task.all_tasks()
/usr/lib/python3.8/site-packages/aiohttp/connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
hosts = await asyncio.shield(self._resolve_host(
/usr/lib/python3.8/site-packages/aiohttp/locks.py:21: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
self._event = asyncio.Event(loop=loop)
/usr/lib/python3.8/asyncio/events.py:81: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
self._context.run(self._callback, *self._args)
/usr/lib/python3.8/asyncio/events.py:81: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
self._context.run(self._callback, *self._args)
Exception in thread thread-0:
Traceback (most recent call last):
File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
self.run()
File "/usr/lib/python3.8/threading.py", line 870, in run
self._target(*self._args, **self._kwargs)
File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 874, in worker
callback = "{}() in {}".format(funcref.name, name)
AttributeError: 'NoneType' object has no attribute 'name'

**Comment by ReneTode** [comment]
you got 1 error in your code, which can cause this:
```
self.run_minutely(self.Scheduled(), ts_start)
```
in that line you call a function and not a callback. which causes trouble.
the line should be:
```
self.run_minutely(self.Scheduled, ts_start)
```

**Comment by GeoffCampbell** [comment]
You're quite right, that works fine.  Thanks, and also thanks for going easy on the novice  :-)
