### ISSUE TITLE
Adminstration front end tables are difficult to use

### ISSUE THREAD

**Issue by iprak** [AppDaemon/appdaemon#1046]
The tables are all laid out with no width so important details are lost in ellipsis:
![image](https://user-images.githubusercontent.com/6459774/94002353-6798a980-fd5f-11ea-91eb-20b0bffc20bf.png)

Assigning widths to columns with limited content would allow the more useful content to be more visible:
![image](https://user-images.githubusercontent.com/6459774/94002463-8a2ac280-fd5f-11ea-80c5-30e491206b31.png)

I have some local changes and can polish them for a PR if seems like a good idea.

**Comment by ReneTode** [comment]
Andrew likes the width to be adjusted by the table width.
in the future i suspect it will be adjustable.

assigning width in general isnt usefull, because it depends on the wishes from the users.
for example, for me the appname should be as long as possible.

**Comment by InduPrakash** [comment]
The columns don't have any widths assigned, so all columns get equal widths. And so appName column won't grow to expand to its content. This auto width assignment doesn't make the UI usable. 

Definitely Fired/Executed/Pinned/Thread are all counts and they don't need to have the same width as App/Kwarg/Execution time/etc. Fixed width can be assigned to columns whose content is well identified, the rest columns will get the left over width equally divided which should definitely give a better presentation.

**Comment by InduPrakash** [comment]
Additionally, some sort of column resizing can be introduced which would allow the user to adjust the widths for better visibility.

**Comment by ReneTode** [comment]
if you use fixed size for excecution time, it will take up space from the appname.
make the screen smaller and nothing from appname is left.
and you also need to take fontsize and zoomlevels into account, just as different fonts.

fixing it is a good option if it is configurable. which it will be in the future.
resizing in the screen is also on the todo list.

by the way expanding automaticly based on content is also no option.
in my case appname would take up most of the table ;)

**Comment by ReneTode** [comment]
i also resized, but as you can see i would need different sizes then you.
![admin resized](https://user-images.githubusercontent.com/20782113/94024370-9e021300-fdb7-11ea-8334-ff520a44ba7a.jpg)

**Comment by InduPrakash** [comment]
Ahh I was not clear. I only proposed said fixed size for Fired/Executed/Pinned/Thread which are all counts.

The current outcome is based on resolution.  Yes it could happen that the outcome is not to user preference but column resizing could be added to allow changing column widths.

Zoom level should not change the column dimensions.

If user configuration of column widths is planned then this would be unnecessary.

**Comment by ReneTode** [comment]
i know that user configuration was at the wishlist.
but i have no clue when it will be done, because the list of things to do is long and the devs have very busy lives.

**Comment by acockburn** [comment]
This version of the AUI was really just an experiment. The AUI is being completely re-written using a modern web framework, with better sizing as an explicit goal.
