### ISSUE TITLE
Strange exception happens several times per day

### ISSUE THREAD

**Issue by Bensonaa** [AppDaemon/appdaemon#1049]
Hi. Appdaemon is awesome. I am getting this odd exception that I can't figure out. Happens on several apps and when it happens that app stops working completely it seems. There doesn't seem to be a pattern as to when it happens. Always the same error except the thread is different each time. Any ideas? Running Hass.Io on RPI 3b+.

Exception in thread thread-8:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/site-packages/appdaemon/appdaemon.py", line 577, in worker
    callback = "{}() in {}".format(funcref.__name__, name)
AttributeError: 'NoneType' object has no attribute '__name__'

**Comment by ReneTode** [comment]
can you post 1 app in which it happens?

**Comment by Bensonaa** [comment]
Of course. See below.

```
class security(hass.Hass):
    def initialize(self):
        self.lookup = {'device_tracker.life360_andrew': 'Andrew', 
                               'device_tracker.life360_carly': 'Carly', 
                               'group.family': 'Family', 
                               'device_tracker.andrew_bt': 'Andrew'}`
        self.run_daily(self.lockstate('lock'), self.parse_time('22:00:00'))
        for item in ['device_tracker.life360_andrew', 'device_tracker.life360_carly', 'group.family', 'device_tracker.andrew_bt']:
            self.listen_state(self.switcher, item)

    def lockstate(self, state):
        if state == 'lock':
            self.call_service('lock/lock', entity_id='lock.front_door')
            self.log('locked front door')
        else:
            self.call_service('lock/unlock', entity_id='lock.front_door')
            self.log('unlocked front door')
    
    def switcher(self, entity, attibute, old, new, kwargs):
        if old == new:
            pass
        elif new == 'not_home' and entity == 'group.family':
            self.lockstate('lock')
            self.log('everyone left')
        elif new == 'home' and entity != 'group.family' and self.get_state('lock.front_door') != 'unlocked':
            self.lockstate('unlock')
            self.log('{} got home'.format(self.lookup[entity]))
        else:
            pass
```

**Comment by ReneTode** [comment]
```
       self.run_daily(self.lockstate('lock'), self.parse_time('22:00:00'))
```
that is your problem.
self.lockstate('lock') isnt a callback but a function.
so you need to use:
```
       self.run_daily(self.lockstate, self.parse_time('22:00:00'))
```
another error that you got is:
```
    def lockstate(self, state):
```
this cant be used as callback for a run_daily.
the callback signature from run_daily (and all other schedulars) is:
```
    def lockstate(self, kwargs):
```
if you want to pass an arg to a callback then you can use:
```
self.run_daily(self.lockstate, self.parse_time('22:00:00'), state = 'lock')
```
in the callback you can access that info by using:
```
if kwargs["state"] = "lock":
```
calling the callback from switcher then should be done like:
```
self.run_in(self.lockstate, 0, state = 'unlock')
```

i hope this makes you see that you were using things the wrong way, so that you can correct that.
if you got other questions i advise you to come to our discord channel, where we can help you more.

**Comment by Bensonaa** [comment]
That does make sense. I wasn't picking up the differences between a callback and a function. But I get it now. I can easily modify to use kwargs instead. I'll do that tonight. I am confident that this will resolve the issue. Thanks for taking the time Rene.
