### ISSUE TITLE
iFrame not showing properly on tablet

### ISSUE THREAD

**Issue by mspace00** [AppDaemon/appdaemon#1050]
**Problem/Motivation**

iFrame not showing properly on tablet. When using an iFrame to stream mjpeg camera feed, the desktop browser works perfectly (Firefox and Chrome). On a Samsung tab A the iFrame shows black with download button and play icon.

**Expected behavior**

See iFrame behave on tablet the same as on desktop browser

**Actual behavior**

iFrame shows all black with play icon and download button. Verified on Samsung browser, Chrome, and Fully Kiosk.

**Steps to reproduce**

stream an mjpeg stream thru iFrame on a tablet

**Comment by ReneTode** [comment]
i suspect thats a problem from the tablet browser.
its configured to not show a video when a page is loaded.
i think you should lookup the browser settings.

**Comment by mspace00** [comment]
I can confirm that it is browser related (Firefox works as expected) and it appears the issue is occurring in browsers using Webview. 

On a working browser the iFrame shows the title and video is streaming, and the options are pause, mute, and full screen. On Webview browsers, title is NOT shown, iFrame is black with play icon (clicking does nothing), and options are mute, full screen, and download. Pressing play does sometimes start the video, device dependent.

**Comment by ReneTode** [comment]
it probably also depends on the webview version.
on my galaxy tab 4 it works like expected.

but i know there are settings for your browser that you can change. and i know that there exists a setting that makes that videostreams are not automaticly started.

so its possible you can get rid of your problem by changing a setting. there is nothing that can be done in appdaemon to change that behaviour.

**Comment by mspace00** [comment]
Thank you ReneTode,

Would you be able to tell me you webview version? Running that version might solve my issue!

**Comment by ReneTode** [comment]
like i said its probably a setting from webview that you need to change, so running a different one might not help.

but i looked it up and FK tells me that i run webview 85.0.4183.127
