### ISSUE TITLE
fire_event: event data limitation [Change request]

### ISSUE THREAD

**Issue by Oekn5w** [AppDaemon/appdaemon#1057]
due to the structure within the `fire_event` function, the data sent along with the event is restricted to not have `namespace` or `event` in it. I'd suggest to change the function (and the hass plugin function) so that the data sent along can be passed as dictionary, not as individual arguments.

In the use-case I had, I tested an automation and had to emulate an IKEA dimmer for said automation. This sends the button pressed, held or let go in the `event` tag in the data. I worked around it.

Should this change be implemented? It might possible be breaking existing automations. So maybe implement it in a separate function or handle a single dictionary specially. From what I see in `events.py` and `hassplugin.py` the additional arguments are handled as dictionary anyway.

**Comment by ReneTode** [comment]
normally you fire an event in a specified namespace and you listen to that event in that same namespace.
so AD knows in which namespace an event takes place.
and to see an event with listen_event you specify the event.

so i dont see where namespace and event are not used with fire_event.

if i remember correct its just the ikea stuff that create a problem by using the same keywords as AD.

**Comment by Odianosen25** [comment]
I am closing this, as this won't be done I am afraid. Unless you can submit code @Oekn5w for this, I am of the view the devs won't look into it.

But if you really want to do it, its possible to "hack" it whereby you get the plugin's object and fire the event the way you like it. 

Regards
