### ISSUE TITLE
docker 'latest' image not co-tagged with a fixed tag 

### ISSUE THREAD

**Issue by wsw70** [AppDaemon/appdaemon#1069]
I am trying to pin my current `latest` image (`b3929a881e8d`) to a specific tag (to manually update from now on when `latest` changes) but it seems that this tag does not correspond to a "fixed" one. 

![image](https://user-images.githubusercontent.com/1345886/98386711-cf296080-2050-11eb-9fa5-ebb770b042b4.png)

Could it be possible, during the build, to add a fixed version number as the tag, in addition to `latest`?

**Comment by acockburn** [comment]
As of 4.1.0 this should be the case. If I've misunderstood what you are asking for please feel free to re-open.
