### ISSUE TITLE
Add time_fired, to the callbacks from listen_event() 

### ISSUE THREAD

**Issue by PremiumUsername** [AppDaemon/appdaemon#1072]
When using ```listen_event()```, the callbacks does not contain the ``` time_fired ``` argument that exist in HA. It would be nice if that piece of information could be included in the callback arguments somehow (as a standalone argument or part of the dictionary with the other event data). 

I think this is a general issue for all listen_event() callbacks, but if it is not, it is at least true for deconz events.

**Comment by Odianosen25** [comment]
Hello @PremiumUsername,

Apologies for the last response. When using `listen_event`, all data from HA is included as given by HA.

If that data is not there, then HA is not giving it. Or has this issue been solved already?

DO kindly let me know, so I could possibly close this issue.

regards

**Comment by PremiumUsername** [comment]
I just checked, nothing has changed. If you monitor events under developer tools in HA, you can see this for a ZHA event:

```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "04:cf:8c:df:3c:75:c0:10",
        "unique_id": "04:cf:8c:df:3c:75:c0:10:3:0x0012",
        "device_id": "f8f5d7a50d1141f290ec24ffafbf9369",
        "endpoint_id": 3,
        "cluster_id": 18,
        "command": "3_single",
        "args": {
            "button": 3,
            "press_type": "single",
            "attr_id": 85,
            "value": 1
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-21T10:31:53.118534+00:00",
    "context": {
        "id": "e9c2113a90b214c5fb4ecdc84f1bccbf",
        "parent_id": null,
        "user_id": null
    }
}
```

AD sees this:
```
locals: {'self': <try_out.TryOut object at 0x7587b688>, 'event': 'zha_event', 'data': {'device_ieee': '04:cf:8c:df:3c:75:c0:10', 'unique_id': '04:cf:8c:df:3c:75:c0:10:3:0x0012', 'device_id': 'f8f5d7a50d1141f290ec24ffafbf9369', 'endpoint_id': 3, 'cluster_id': 18, 'command': '3_single', 'args': {'button': 3, 'press_type': 'single', 'attr_id': 85, 'value': 1.0}}, 'kwargs': {'__thread_id': 'thread-6'}}

```

So `time_fired` is not forwarded.

**Comment by ReneTode** [comment]
the problem in this is that changing that has 2 easy choices but
1) moving all data 1 level up gives breaking changes for every event user. not a nice choice, because it would break an extreme amount of apps
2) add time_fired as extra arg, but then origin and context should be added also and every time HA adds or changes something AD needs maintainance.

the more difficult solution is to move all extra args from HA to the data
so that time_fired will be included in the data from the data dir from HA.
but if that is done, the names should be changed. because HA has chosen this structure probably for a reason and maybe in some data from devices there is a time_fired also.

so i think the best solution would be to translate:
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "04:cf:8c:df:3c:75:c0:10",
        "unique_id": "04:cf:8c:df:3c:75:c0:10:3:0x0012",
        "device_id": "f8f5d7a50d1141f290ec24ffafbf9369",
        "endpoint_id": 3,
        "cluster_id": 18,
        "command": "3_single",
        "args": {
            "button": 3,
            "press_type": "single",
            "attr_id": 85,
            "value": 1
        }
    },
    "origin": "LOCAL",
    "time_fired": "2021-01-21T10:31:53.118534+00:00",
    "context": {
        "id": "e9c2113a90b214c5fb4ecdc84f1bccbf",
        "parent_id": null,
        "user_id": null
    }
}
```
to
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "04:cf:8c:df:3c:75:c0:10",
        "unique_id": "04:cf:8c:df:3c:75:c0:10:3:0x0012",
        "device_id": "f8f5d7a50d1141f290ec24ffafbf9369",
        "endpoint_id": 3,
        "cluster_id": 18,
        "command": "3_single",
        "args": {
            "button": 3,
            "press_type": "single",
            "attr_id": 85,
            "value": 1
            "hass_origin": "LOCAL",
            "hass_time_fired": "2021-01-21T10:31:53.118534+00:00",
            "hass_context": {
                "id": "e9c2113a90b214c5fb4ecdc84f1bccbf",
                "parent_id": null,
                "user_id": null
           }
}
```

**Comment by Odianosen25** [comment]
This is actually an issue that has been raised several times, and I think its not so much that difficult to be addressed.

We just have to agree on the final format and its something I can quickly get done in dev is we all agree.

Rather than put it in `args`, I will rather move them all to a single level inside, so that's `data`, with a single `_` in front of them.

So it becomes

```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "04:cf:8c:df:3c:75:c0:10",
        "unique_id": "04:cf:8c:df:3c:75:c0:10:3:0x0012",
        "device_id": "f8f5d7a50d1141f290ec24ffafbf9369",
        "endpoint_id": 3,
        "cluster_id": 18,
        "command": "3_single",
        "args": {
            "button": 3,
            "press_type": "single",
            "attr_id": 85,
            "value": 1
        },
    "_origin": "LOCAL",
    "_time_fired": "2021-01-21T10:31:53.118534+00:00",
    "_context": {
        "id": "e9c2113a90b214c5fb4ecdc84f1bccbf",
        "parent_id": null,
        "user_id": null
        }
    },
}
```
I will have to pass it via Andrew though, before anything can take place.

Regards

**Comment by Odianosen25** [comment]
Ok just had a chat with Andrew and this is what he approved of
```
{
    "event_type": "zha_event",
    "data": {
        "device_ieee": "04:cf:8c:df:3c:75:c0:10",
        "unique_id": "04:cf:8c:df:3c:75:c0:10:3:0x0012",
        "device_id": "f8f5d7a50d1141f290ec24ffafbf9369",
        "endpoint_id": 3,
        "cluster_id": 18,
        "command": "3_single",
        "args": {
            "button": 3,
            "press_type": "single",
            "attr_id": 85,
            "value": 1
        },
    "metadata" {
          "origin": "LOCAL",
          "time_fired": "2021-01-21T10:31:53.118534+00:00",
          "context": {
              "id": "e9c2113a90b214c5fb4ecdc84f1bccbf",
              "parent_id": null,
              "user_id": null
              }
       },
    },
}
```
Will attempt a PR for this this week.

Regards

**Comment by ReneTode** [comment]
i cant argue with that when it is in args.
but people will expect it in the data var.
but as long as the data var isnt changed nothing will break.

**Comment by Odianosen25** [comment]
This is now in dev
