### ISSUE TITLE
Azure package is deprecated

### ISSUE THREAD

**Issue by freezeboy** [AppDaemon/appdaemon#1078]
Hi,

Your requirements.txt file is still depending on `azure` package which is deprecated, and now Microsoft has split it into multiple modules so it should be updated

**Comment by Odianosen25** [comment]
Hello @freezeboy,

Apologies for the late response, and thanks for the update. Is it possible for you to kindly submit a PR for this? As someone actually assisted in getting this side of things done.

Kind regards

**Comment by freezeboy** [comment]
Hi

I can provide a change set in this file but as I don't use azure myself, i won't be able to provide version constraints

**Comment by Odianosen25** [comment]
Ok, no worries, just do what you can and we will take it up from there.

Kind regards
