### ISSUE TITLE
Depreciated warnings in log file

### ISSUE THREAD

**Issue by Bas-Man** [AppDaemon/appdaemon#1101]
Running on Hassio. When I restart AppDaemon 4 I get the following warning in the logs.

From logs:
2020-12-15 22:44:17.187047 INFO AppDaemon: AppDaemon is stopped.
/usr/lib/python3.8/site-packages/appdaemon/main.py:133: DeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead
pending = asyncio.Task.all_tasks()
/usr/lib/python3.8/site-packages/aiohttp/connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
hosts = await asyncio.shield(self._resolve_host(
/usr/lib/python3.8/asyncio/events.py:81: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
self._context.run(self._callback, *self._args)
/usr/lib/python3.8/asyncio/events.py:81: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
self._context.run(self._callback, *self._args)
/usr/lib/python3.8/site-packages/aiohttp/connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
hosts = await asyncio.shield(self._resolve_host(

**Comment by tirkarthi** [comment]
The loop parameter has been removed in Python 3.10 : https://bugs.python.org/issue42392
