### ISSUE TITLE
AppDaemon Administration Logs strips out any angle brackets

### ISSUE THREAD

**Issue by matejdro** [AppDaemon/appdaemon#1102]
Following code:

```
self.log("Hello <World>")
```

Will just print out `Hello` on the Administration page, with all content inside angle brackets trimmed out.

This is with Appdaemon 4.0.5 running via official Docker image.

**Comment by ReneTode** [comment]
"<World>" is in HTML a field.
the AI sees the log as an HTML page.

the AI is still a work in progress.
it will take quite some work to make sure that the log is presented correctly when there are things in it that HTML sees as code.
