### ISSUE TITLE
secrets.yaml not working

### ISSUE THREAD

**Issue by PanMat** [AppDaemon/appdaemon#1104]
Hi,

It seems that appdaemon apps are not able to use sensitive info in HA's secrets.yaml file.
Please see thread at https://community.home-assistant.io/t/appdaemon-secret-file-not-working-closed/261103 fro actual screenshots and examples. 

HTH 
pankaj

**Comment by ReneTode** [comment]
answered on the forum.

AD secrets are working, this is a user error or a HA restriction.

**Comment by Odianosen25** [comment]
Since this issue has been solved on the forum, will be closing.

Thanks
