### ISSUE TITLE
start app causes apps to run multiple times.

### ISSUE THREAD

**Issue by ReneTode** [AppDaemon/appdaemon#1117]
when you start an app that is already running the app starts to run again.
that needs to be prevented.

on the same time when an app isnt terminated correctly the app shouldnt be started again.

note for @Odianosen25 you can read back the conversation we had in discord.

**Comment by Odianosen25** [comment]
Thanks this helps

**Comment by Odianosen25** [comment]
@ReneTode so fixed your issues #1189. Once @acockburn approves my approach, then will merge it. Though fixed the starting of apps when they stopped anyway

**Comment by Odianosen25** [comment]
Ok this is fixed in present dev
