### ISSUE TITLE
apps directory file monitoring reports inaccessible hidden files 

### ISSUE THREAD

**Issue by nottledim** [AppDaemon/appdaemon#1122]
The monitoring of py and yaml files in the apps dir for additions and changes picks up and continuously reports errors accessing emacs lock files.    On linux emacs uses lock files to protect  buffers being editied.  They are named beginning .# and as such are by convention hidden files.  

The problem is this reporting pollutes the appDaemon log files with pointless messages e.g:
```
2021-01-19 15:13:53.378342 WARNING AppDaemon: Unable to read app /conf/apps/.#occusim.py: [Errno 2] No such file or directory: '/conf/apps/.#occusim.py' - skipping
```
Could I suggest you ignore all files in apps directory on linux systems where the name begins with a dot  (aka period).

**Comment by Odianosen25** [comment]
Ok @nottledim,

Have merged it to dev, so can install dev and all should be good.
Will be closing this now, and if it is not fixed, do re-open it.

Regards

**Comment by nottledim** [comment]
I'm struggling to be sure but I've just checked out 8c0f4f6 and running it, it doesn't seem to be fixed.  The git log has  "Prevent the loading of hidden folders" so I assume it's there.  My git skills are pretty poor so anything could happen :-(

**Comment by Odianosen25** [comment]
If you only want the one with the ignore, what you need to checkout is [5119013](https://github.com/AppDaemon/appdaemon/commit/5119013e3bc9ab51c08b68c15cf39f04900c1c6e).

Or better still, you can just install the present dev.

Regards

**Comment by nottledim** [comment]
I tried dev and I've tried 5119013 and they're all the same.  
```
2021-01-21 15:26:10.851922 WARNING AppDaemon: Unable to read app /home/dick/tmp/appdaemon/conf/apps/.#notify.py: [Errno 2] No such file or directory: '/home/dick/tmp/appdaemon/conf/apps/.#notify.py' - skipping
```

You can test it by creating symlink e.g:
```
 ln -s pigs@fly.1756:1611227799 .#pigs.py
```
in /conf/apps then of course 
```
rm .#pigs.py
```

**Comment by Odianosen25** [comment]
Ah your issue is quite different, will be re-opening this for a proper fix.

**Comment by nottledim** [comment]
And I was so impressed by the speed of the fix :-)   Thanks, much appreciated.

**Comment by Odianosen25** [comment]
Try this @nottledim,

https://github.com/AppDaemon/appdaemon/pull/1127

Regards
