### ISSUE TITLE
Improve saving user defined namespace to disc

### ISSUE THREAD

**Issue by katonage** [AppDaemon/appdaemon#1126]
Symptoms:
When using user defined namespace with writeback: hybrid, AD throws "WARNING AppDaemon: Excessive time spent in utility loop: 8039.0ms, 16.0ms in check_app_updates(), 8023.0ms in other" very often. Stochastically, in every few minutes. That is frightening on the one hand, but also floods log and thus prevents proper logging.
see also: https://github.com/AppDaemon/appdaemon/issues/834#issuecomment-758965787  and https://github.com/AppDaemon/appdaemon/issues/1125#issue-790368897
Changing the user defined namespace to performance clears the warning. So it is suspicious that:
utility_loop.py  line172 self.AD.state.save_hybrid_namespaces() takes too much time.
To workaround this I set the namespace to writeback: performance. Create an app to do the storing of namespace to the disk:
```
import appdaemon.plugins.hass.hassapi as hass
import datetime

class Save_Namespace_Main(hass.Hass):
    "Saves StorageNamespace do disk."
    
    def initialize(self):

        self.autolistener=self.run_every( self.rep_save_namespace, self.get_now(), 30) #saving frequency

    def rep_save_namespace(self, kwargs):
        s2 = datetime.datetime.now().timestamp()
        self.save_namespace( namespace="StorageNamespace")
        e2 = datetime.datetime.now().timestamp()
        save_duration = (int((e2 - s2) * 1000) / 1000) * 1000
        self.log("NameSpace storing: " + str(save_duration) + "ms")
        
```
This produced me the following output to the admin console:
2021-01-20 22:53:22.066251 INFO namespace_saver: NameSpace storing: 41.0ms
2021-01-20 22:52:52.027886 INFO namespace_saver: NameSpace storing: 2.0ms
2021-01-20 22:52:22.026853 INFO namespace_saver: NameSpace storing: 2.0ms
2021-01-20 22:51:52.029805 INFO namespace_saver: NameSpace storing: 2.0ms
2021-01-20 22:51:22.029736 INFO namespace_saver: NameSpace storing: 2.0ms
2021-01-20 22:50:55.908676 INFO namespace_saver: NameSpace storing: **3870.0ms**
2021-01-20 22:50:23.591543 INFO namespace_saver: NameSpace storing: **1555.0ms**
2021-01-20 22:49:52.027973 INFO namespace_saver: NameSpace storing: 2.0ms
2021-01-20 22:49:22.029538 INFO namespace_saver: NameSpace storing: 2.0ms
2021-01-20 22:48:52.026244 INFO namespace_saver: NameSpace storing: 3.0ms
2021-01-20 22:48:22.025662 INFO namespace_saver: NameSpace storing: 1.0ms
2021-01-20 22:47:52.032416 INFO namespace_saver: NameSpace storing: 7.0ms
2021-01-20 22:47:22.035123 INFO namespace_saver: NameSpace storing: 7.0ms
2021-01-20 22:46:52.080902 INFO namespace_saver: NameSpace storing: 58.0ms
It is shown that namespace saving sometimes takes unreasonable long time.

System: 
I use a standard RPI4 hardware with an SD card and RFlink. I use HA with the official RPI 64 distribution, HA core-2021.1.4, OS 5.9, Ad4 0.3.2 Addon, AD 4.0.5. I use 1 namespace, I have only 6 entities whose state changes only a few times a day.

Possible resolution:
Improve namespace saving to check in CPU if anything has changed since the last storage operation, and access disk only if it is necessary. Since the utility loop is usually 1sec, entities within this timeframe rarely change, so most of the disk IO could be omitted.

**Comment by ReneTode** [comment]
but dont forget: you found a symptom from an underlying problem.
your I/O is to busy and to slow at the times those warnings come.
if you got that regular then you should find out what keeps your I/O so busy, and see if you can solve the problem there.
because that problem can cause other issue elsewhere as well.

**Comment by katonage** [comment]
True.

meanwhile i improved the workarounder app. Checking difference is fairly easy. I could do more argument checks.

```
import appdaemon.plugins.hass.hassapi as hass
import datetime
#
# main save_namespace_app App
# regularly checks changes to a namespace. if difference found, saves data to disc.
# that is a workaround for writeback: hybrid performance problems.
#
# Args:
#  namespace: string name of the namespace to watch and store
#  log: boolean, if true log message is displayed if storage is performed

class Save_Namespace_Main(hass.Hass):
    "Saves namespace regularly do disk."
    
    def initialize(self):
        self.datastore=[]
        
        self.donamespace=self.args['namespace']
        self.dolog=self.args['log']
        
        self.autolistener=self.run_every( self.rep_save_namespace, self.get_now(), 10)
        self.log("Namespace " + self.donamespace + ' storage watch started. Log: ' + str(self.dolog) )

    def rep_save_namespace(self, kwargs):
        cdata = self.get_state( namespace = self.donamespace)
        
        if cdata == self.datastore: 
            #self.log(self.donamespace + " storage skipped.")
            return 
        
        s1 = datetime.datetime.now().timestamp()
        self.save_namespace( namespace = self.donamespace )
        s2 = datetime.datetime.now().timestamp()
        save_duration = (int((s2 - s1) * 1000) / 1000) * 1000
        
        self.datastore=cdata
        
        if self.dolog:
            self.log(self.donamespace + " stored in: " + str(save_duration) + "ms")
```

**Comment by ReneTode** [comment]
seems good.
only 1 remark:
```
        self.autolistener=self.run_every( self.rep_save_namespace, self.get_now(), 10)
```
should be
```
        self.autolistener=self.run_every( self.rep_save_namespace, "now", 10)
```
because get_now() can be in the past when the system is slow when initialise is performed.

**Comment by Odianosen25** [comment]
So will be closing this, and @katonage do reopen if need be
