### ISSUE TITLE
Accessing last_changed data from a widget

### ISSUE THREAD

**Issue by Tam-Lin** [AppDaemon/appdaemon#1128]
I'm opening an issue because I didn't get a useful response when I posted on the HomeAssistant forums; I'm looking through the code, but javascript isn't currently something I have much knowledge of.

Basically, I'm trying to display the last_changed value in a widget; I'm unable to do so.  I think that this is because last_changed isn't exactly an attribute of the Home Assistant entity; it's something that Home Assistant provides automatically.  However, AppDaemon clearly has knowledge of this attribute, as it shows up in the AppDaemon admin panel.

So, I'm trying to figure out if I'm missing something somewhere, and it is possible to use last_changed in a widget, or if I need to dig into the code more and see if I can figure out a way to expose it in widget form.

**Comment by ReneTode** [comment]
there are some others that have it, and it is on the forum, just from a long time ago.

if you want it as a single widget, then you could make a template sensor that shows the time_changed.

if you want it shown on existing widgets, then you will need to change the javascript.
