### ISSUE TITLE
Errors when asctime omitted from log format

### ISSUE THREAD

**Issue by nottledim** [AppDaemon/appdaemon#1129]
So I don't want to put time in logs when using systemd because systemd puts it in anyway. Removing it from logs format: causes a recursive mayhem:
```
logs:
  main_log:
     format: "{levelname:<8} {appname:<10}: {message}"
```

```
Traceback (most recent call last):
Jan 22 12:26:34 mimas python[111338]:   File "/var/lib/appdaemon/appdaemon2/appdaemon/logging.py", line 154, in emit
Jan 22 12:26:34 mimas python[111338]:     "asctime": record.asctime,
Jan 22 12:26:34 mimas python[111338]: AttributeError: 'LogRecord' object has no attribute 'asctime'
Jan 22 12:26:34 mimas python[111338]: During handling of the above exception, another exception occurred:
```

**Comment by acockburn** [comment]
Yes, the ASCTIME field is required for the formatter to support time travel, and omitting it causes an error to be logged which in turn has no asctime fields so it tries to emit an error ...

You could try including asctime in your format but setting the `date_format` to blank or something innocuous.

**Comment by nottledim** [comment]
On 22 January 2021 19:11:39 Andrew Cockburn <notifications@github.com> wrote:
>
> Yes, the ASCTIME field is required for the formatter to support time 
> travel, and omitting it causes an error to be logged which in turn has no 
> asctime fields so it tries to emit an error ...
> You could try including asctime in your format but setting the date_format 
> to blank or something innocuous.
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.

It's not easy being a programmer is it 😂

I devised that workaround too. Maybe a note in the docs.

Many thanks

**Comment by Odianosen25** [comment]
Thanks for answering @acockburn,

If your issues is sorted @nottledim, can you kindly close this issue?

Regards

**Comment by nottledim** [comment]
Pondering this I'm thinking (wibni) the logs facility should have an output to system logger (syslog) capability (it is a daemon).  If that were to exist it would then be reasonable to inhibit output to syslog when in time warp mode and it would also make sense and be possible for the default log format for syslog to omit asctime.

**Comment by ReneTode** [comment]
> the logs facility should have an output to system logger 

isnt that when STDOUT is used?

**Comment by nottledim** [comment]
Systemd certainly diverts stdout and stderr to journald by default. Traditionally on unix logging is  via the syslog daemon .  Naturally it's much more complex :-)
For example this is the config from the zigbee2mqtt daemon that gives an idea of what can be done:
```log_output:
    - console
    - file
  # Optional: syslog configuration, skip values or entirely to use defaults. Only use when 'syslog' in 'log_output' (see above)
  log_syslog:
    host: localhost # The host running syslogd, defaults to localhost.
    port: 123 # The port on the host that syslog is running on, defaults to syslogd's default port.
    protocol: tcp4 # The network protocol to log over (e.g. tcp4, udp4, tls4, unix, unix-connect, etc).
    path:  /dev/log # The path to the syslog dgram socket (i.e. /dev/log or /var/run/syslog for OS X).
    pid: process.pid # PID of the process that log messages are coming from (Default process.pid).
    facility: local0 # Syslog facility to use (Default: local0).
    localhost: localhost # Host to indicate that log messages are coming from (Default: localhost).
    type: 5424 # The type of the syslog protocol to use (Default: BSD, also valid: 5424).
    app_name: Zigbee2MQTT # The name of the application (Default: Zigbee2MQTT).
```
I think my initial issue arises because time-stamping messages is normally delegated to the logging channel but appDaemon time travel conflicts with that idea.  I was just trying to contrive a way to flag that easily on the assumption that time travel messages are probably not something that you'd want put in the system log.

**Comment by ReneTode** [comment]
its just a matter of thinking i guess.

the basic choice is made and every other option is available though workarounds.
the way it is now, you can have time travel messages in syslog or in any other log, just like you can have everything else you want where you want it, and with a workaround even how you want it.

simular to what you can do in zigbee2mqtt you can do in AD:

```
logs:
  mainlog: # no file specified, so goes to console
    format: ... 
  file_log:
    filename: ...
    format: ...
```

**Comment by nottledim** [comment]
I don't disagree with you.  What I need to do can be done.  Thanks for your comments.
