### ISSUE TITLE
namespace required when using register_service()?

### ISSUE THREAD

**Issue by dekiesel** [AppDaemon/appdaemon#1138]
Hi,

I have two apps, one emitter and one listener. This is just to grasp the concept of registering a service.

Emitter:

```
import hassapi as hass
class Emitter(hass.Hass):
    def initialize(self):
        self.call_service("listener/received", test="Works, YAY!")
```

Listener:

```
import hassapi as hass
class Listener(hass.Hass):
    def initialize(self):
        self.register_service("listener/received", self.received)

    def received(self, plugin, domain, service, data):
        self.log(f"{data=}")
```

This leads to an error:

```
2021-01-27 14:37:38.665130 INFO AppDaemon: Initializing app emitter using class Emitter from module emitter
2021-01-27 14:37:38.697875 WARNING HASS: Error calling Home Assistant service default/listener/received
2021-01-27 14:37:38.698711 WARNING HASS: Code: 400, error: 400: Bad Request
```

I luckily found [this](https://community.home-assistant.io/t/error-400-when-call-service/243544) issue on the HA forums. 

I added `namespace=` to `register_service()` and `call_service()` like this:

Emitter:
```
import hassapi as hass
class Emitter(hass.Hass):
    def initialize(self):
        self.call_service("listener/received", test="Works, YAY!!",namespace='testnamespace')
```

Listener:
```
import hassapi as hass
class Listener(hass.Hass):
    def initialize(self):
        self.register_service("listener/received", self.received, namespace = 'testnamespace')

    def received(self, plugin, domain, service, data):
        self.log(f"{data=}")
```

Which then shows the expected output in the logfile:

```
2021-01-27 14:48:08.868854 INFO AppDaemon: Reloading Module: /conf/apps/sequential_state_changer/debug/emitter.py
2021-01-27 14:48:08.876166 INFO AppDaemon: Initializing app emitter using class Emitter from module emitter
2021-01-27 14:48:08.896254 INFO listener: data={'test': 'Works, YAY!'}
```

Is `namespace` required when using services or am I using the functions incorrectly? The docs don't say that they are necessary so I assume I am not doing it right.

**Comment by Odianosen25** [comment]
@dekiesel,

Not that it is required, but when dealing with HA namespace, its advised not to register a service call within it.

So just create a user defined namespace and use that, or on the other hand, if not using the `default` namespace, keep it in there.

Regards

**Comment by dekiesel** [comment]
@Odianosen25 

So as long as I don't use the `default` namespace I am good, is that right?

**Comment by Odianosen25** [comment]
> So as long as I don't use the default namespace I am good, is that right?

If its not being used by HA. If its used by HA (that is you didn't specify a namespace in the Hass config), don't use `default`.

By the way using the example you just gave above, will not work in future as it shouldn't be possible so will be disabled by next release.

Regards

**Comment by dekiesel** [comment]
To be future proof would it then be best to set a namespace for HA in `appdaemon.yaml`?

```
appdaemon:
  plugins:
    HASS:
      type: hass
      namespace: ha
```

**Comment by Odianosen25** [comment]
Yes that is right, but I will use instead

```
appdaemon:
  plugins:
    HASS:
      type: hass
      namespace: hass
```

**Comment by dekiesel** [comment]
With that setting my apps can't find my HA entities in the namespace `default`. Does that mean I have to manually adjust all my apps to use `hass`?


It seems it would be a better idea to not change the namespace in `appdaemon.yaml` and use the method that works from my first post because you (probably) have more entities than custom registered services. But you say that possibility is being removed in the next release. Is that really the intended usage: Manually set the namespace for each app that wants to use HA entities?

**Comment by Odianosen25** [comment]
Ah you do have a good point which I did forget about. By default the namespace will use the default and not hass.

Since that is the case, to future prove just create a new namespace and have your custom services in there. That way you are fine no matter what.

If you are using the dev version, there is an api to create namespaces but I don’t think for this, that level of complexity is required.

Just create a user defined namespace, and use that to store your services.

regards

**Comment by dekiesel** [comment]
Thanks,

 I added this to my `appdaemon.yaml`:
```

  namespaces:
    custom_services:
      writeback: safe

```

And changed the emitter and listener to use `namespace='custom_services'`, so far it works :) Thanks for the assistance!!!

One last point: Is there an explanation about the `writeback` parameter somehwere? I guess it is how often the entities in the namespaces are saved to the disk?

**Comment by Odianosen25** [comment]
> One last point: Is there an explanation about the writeback parameter somehwere?

Yes [here](https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html?highlight=User%20defined%20namespace#user-defined-namespaces)

> I guess it is how often the entities in the namespaces are saved to the disk?

Yes True. 

Glad I could help and regards. Kindly close the issue when done.
