### ISSUE TITLE
Socket.io can't be used in version 0.4.0 

### ISSUE THREAD

**Issue by skannea** [AppDaemon/appdaemon#1140]
After upgrading AD 4 to 0.4.0 all numbers and icons are missing in all my HAdashboards.
The reason seems to be that it is no longer possible to use the socket.io option in appdaemon.yaml:

```
http: 
  transport: socketio
```
The reason I am not using websockets (which is default) is that I am using iOS clients ( iPad and iPhone ) for remote access to the HAdashboards.
In combination with Nginx ( Nginx Proxy Server add-on for HA ) set up with user/password authorization, websockets can't be used. 

This is logged when starting the AD add-on:
 
```
...
[cont-init.d] 01-log-level.sh: executing... 
[cont-init.d] 01-log-level.sh: exited 0.
[cont-init.d] appdaemon.sh: executing... 
[cont-init.d] appdaemon.sh: exited 0.```
Add-on version: 0.4.0
 You are running the latest version of this add-on.
 System: HassOS 4.15  (armv7 / raspberrypi4)
 Home Assistant Core: 2021.1.5
 Home Assistant Supervisor: 2021.01.7
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
[cont-init.d] 00-banner.sh: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
[20:49:30] INFO: Starting AppDaemon...
/usr/lib/python3.8/site-packages/appdaemon/__main__.py:133: DeprecationWarning: Task.all_tasks() is deprecated, use asyncio.all_tasks() instead
  pending = asyncio.Task.all_tasks()
/usr/lib/python3.8/site-packages/aiohttp/connector.py:964: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  hosts = await asyncio.shield(self._resolve_host(
/usr/lib/python3.8/site-packages/aiohttp/locks.py:21: DeprecationWarning: The loop argument is deprecated since Python 3.8, and scheduled for removal in Python 3.10.
  self._event = asyncio.Event(loop=loop)
The client is using an unsupported version of the Socket.IO or Engine.IO protocols (further occurrences of this error will be logged with level INFO)
...
```
This is logged (for each API call, I guess) by the client ( Chrome or Edge browser on Windows ) 

```
VM2793:1 GET http://192.168.0.111:5050/socket.io/?EIO=3&transport=polling&t=NT0Fjlu 400 (Bad Request)
(anonymous) @ VM2793:1
window.XMLHttpRequest.send @ main.js?attr=-MhlPDGlhq6D7Mdgw7l04b9nZsnpdwK9bObFSmZ5ne6Tr-RmiigE6S7SsUwo2FJbVHpqB-HDpo50BzkOn7AxOA:3024
i.create @ socket.io.js:7
i @ socket.io.js:7
o.request @ socket.io.js:7
o.doPoll @ socket.io.js:7
r.poll @ socket.io.js:7
r.doOpen @ socket.io.js:7
r.open @ socket.io.js:7
r.open @ socket.io.js:6
r @ socket.io.js:6
r @ socket.io.js:6
r.open.r.connect @ socket.io.js:6
r @ socket.io.js:6
r @ socket.io.js:6
r @ socket.io.js:6
SocketIOStream @ stream.js:288
Stream @ stream.js:214
DashStream @ dashboard.js:137
(anonymous) @ carheat_init.js:123
j @ jquery-3.1.1.min.js:2
k @ jquery-3.1.1.min.js:2
setTimeout (async)
(anonymous) @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
fire @ jquery-3.1.1.min.js:2
i @ jquery-3.1.1.min.js:2
fireWith @ jquery-3.1.1.min.js:2
ready @ jquery-3.1.1.min.js:2
R @ jquery-3.1.1.min.js:3

```

**Comment by ReneTode** [comment]
you probably mean addon version 0.4.0 (which should contain AD 4.0.5)
it would help to know from what you updated, if your previous addon version also contained AD 4.0.5, this is not something from AD but from the addon.

**Comment by skannea** [comment]
From what I remember the version was 3.2. Is there a log to look into to find out?
I found these log snippets from yesterday. I guess it is before and after update.

```
2021-01-26 19:23:40.060059 INFO AppDaemon: AppDaemon Version 4.0.5 starting
2021-01-26 19:23:40.061515 INFO AppDaemon: Python version is 3.8.5

021-01-26 19:32:37.585150 INFO AppDaemon: AppDaemon is stopped.
2021-01-26 19:33:37.566203 INFO AppDaemon: AppDaemon Version 4.0.5 starting
2021-01-26 19:33:37.566714 INFO AppDaemon: Python version is 3.8.7

```

**Comment by ReneTode** [comment]
ok, then you can see that the appdaemon version hasnt changed.
so the problem lies in the addon, so youll need to contact Frenck, because we have nothing to do with the addon.

**Comment by skannea** [comment]
I understand.
Thank you.

**Comment by frenck** [comment]
Actually...

AppDaemon pins: 

https://github.com/AppDaemon/appdaemon/blob/e7e0976fb46a5e4e0e3b492d8022f4154215c924/requirements.txt#L15

That version has a loose pin on:

https://github.com/miguelgrinberg/python-socketio/blob/610ee2cf1fe615b0c8ef229417dcd8e1ddf877c1/setup.py#L33

Causing AppDaemon now to install an incompatible version of Engine.io, since AppDaemon doesn't pin it.

This is not an add-on issue, but a pinning issue of AppDaemon that has outdated dependencies.

**Comment by ReneTode** [comment]
if it worked with python 3.8.5 and now isnt working anymore after an update to python 3.8.7 then its the python update that caused the problem.

if thats the case i would state that appdaemon isnt compatible with python 3.8.7 (yet)

**Comment by frenck** [comment]
Your last response makes no sense. Did you read my message above it?

**Comment by frenck** [comment]
Let me help. At this point, the Socket.io Javascript library included en vendors here in AppDaemon dates from 2018. Its version 2.1.1.

See:

https://github.com/AppDaemon/appdaemon/blob/ac6de7dce88f32be32f1c64c2c368d279b019dff/appdaemon/assets/javascript/socket.io.js#L2

Furthermore, AppDaemon pins Python package: `python-socketio==4.4.0` and dates from 2019.

See: 

https://github.com/AppDaemon/appdaemon/blob/e7e0976fb46a5e4e0e3b492d8022f4154215c924/requirements.txt#L15

So far so good. Python packages `python-socketio==4.4.0`, depends on `python-engineio>=3.9.0`. Which means any version above 3.9.0.

See:

<https://github.com/miguelgrinberg/python-socketio/blob/610ee2cf1fe615b0c8ef229417dcd8e1ddf877c1/setup.py#L33>

The latest version of `python-engineio` is `4.0.0`, which will be installed on a fresh environment, as it matches the `>=3.9.0` condition listed above.


However, that version of engineio isn't compatible with either of the clients listed above.


If you are looking for more information on this, you can read this really long thread I just found on the same subject.

<https://github.com/miguelgrinberg/python-socketio/issues/578>


Conclusion; it isn't a Python version. It is a pinning issue, as I already pointed out in my first response.

**Comment by frenck** [comment]
Here another screenshot from the upstream documentation:

![image](https://user-images.githubusercontent.com/195327/106069757-614a7d80-6103-11eb-8095-48310b9196d7.png)

Showing protocol version 4 of engine IO (which isn't pinned and the one being installed in the current dependency policies of AppDaemon), isn't compatible with the Javascript & Python Socket IO client.

**Comment by frenck** [comment]
Nevermind. @skannea Go ahead and close this issue. I'll add another patch to the add-on. I'm not even sure why I wasted my time here.
