### ISSUE TITLE
Error in cancel_event_callback is not logged

### ISSUE THREAD

**Issue by skannea** [AppDaemon/appdaemon#1143]
This problem was observed in issue #1141.
source: events.py
method:  cancel_event_callback 
Trying to cancel a non-existing event listener should give an error, warning or exception.

**Comment by ReneTode** [comment]
as @Odianosen25 stated in that issue, the function isnt working at all in the mqtt plugin, so off course it doesnt give a warning.
and he also stated that the problem was corrected in dev.
so i expect that when it works it gives an warning or exception.

**Comment by skannea** [comment]
@ReneTode  No, there is no error detection code in cancel_event_callback.
And my guess is that cancel_event_callback really was called but with bad data. There was no match with regged callbacks, the callback was not removed, but no error was issued, the bad data was not detected, and mqtt plugin error was not observed.
But I can be wrong. In any case this has to be investigated.

**Comment by ReneTode** [comment]
@Odianosen25 said:
> Yes you are right the cancel event listener in MQTT doesn’t work. If you log both handlers, you will see it’s an awaitable and not an expected hex string. This has been fixed in dev, so unless you use dev or await the next release, this issue will persist I am afraid.

from that i can only conclude that after it has been repaired, the function functions the same way as the cancel_listen_event from ADapi or hass_api.
and they error out when you use a wrong handler.

**Comment by Odianosen25** [comment]
Fixed so will be closing this as its in the latest dev
