### ISSUE TITLE
Time scheduling

### ISSUE THREAD

**Issue by tcheronneau** [AppDaemon/appdaemon#1144]
Hey,

I've searched a bit but did not found out anywhere what I wanted to achieve so I'm posting there even if I'm not sure it should be the place. 
I would want to achieve some action based on time (turn off some lights, manage heating etc...). 
I cannot find anything related to trigger time based. 

Is there a way to do so with AppDaemon ? 

Thanks,
Thomas.

**Comment by ReneTode** [comment]
run_hourly(), run_daily(), run_at(), run_in(), run_at_sunset(), run_at_sunrise(), run_every(), run_minutely()
all available in the docs.
https://appdaemon.readthedocs.io/en/latest/index.html

**Comment by tcheronneau** [comment]
Thanks a lot I must have put the bad keyword to search that !
