### ISSUE TITLE
Unpin Astral version

### ISSUE THREAD

**Issue by wernerhp** [AppDaemon/appdaemon#1167]
Astral was [pinned to](https://github.com/AppDaemon/appdaemon/blob/e7e0976fb46a5e4e0e3b492d8022f4154215c924/requirements.txt#L1) `astral==1.10.1` since [4.0.3 (2020-02-29)](https://appdaemon.readthedocs.io/en/stable/HISTORY.html?highlight=astral#id3) to _"prevent a bug in the latest v2 astral"_.  The [latest release](https://github.com/sffjunkie/astral/releases) at the time (20 Jan 2020) seems to be pre-v2 so maybe it was an unstable branch at the time.

There's no information on what the bug was, so can't verify if it's been fixed, but there'a new version (`2.2`) of `astral` [released 20 May 2020](https://github.com/sffjunkie/astral/releases).  Can it please be unpinned/bumped up so we can use the new features.

Updating the package in AppDaemon config results in AppDaemon to fail to start.  Looks like the `astral` packages have been restructured.

[1.10.1](https://github.com/sffjunkie/astral/blob/1.10.1/src/astral.py) 
```
    self.location = astral.Location(("", "", latitude, longitude, self.AD.tz.zone, elevation))
```

[2.2](https://github.com/sffjunkie/astral/blob/2.2/src/astral/location.py) 
```
    self.location = astral.location.Location(("", "", self.AD.tz.zone, latitude, longitude))
```

[astral Documentation](https://astral.readthedocs.io)
[astral.location.Location](https://astral.readthedocs.io/en/latest/package.html?highlight=Location(#astral.location.Location))

Found this branch [dependabot/pip/astral-2.2](https://github.com/AppDaemon/appdaemon/tree/dependabot/pip%2Fastral-2.2) and [commit](https://github.com/AppDaemon/appdaemon/commit/fcb1f5b12459d2929739b422437e38a1d7dba4e7) with a [failed build](https://github.com/AppDaemon/appdaemon/runs/1849301964).

**Comment by Odianosen25** [comment]
Ok merged
