### ISSUE TITLE
Build and push fails

### ISSUE THREAD

**Issue by wernerhp** [AppDaemon/appdaemon#1171]
Lots of failed builds in https://github.com/AppDaemon/appdaemon/actions

Error seems to be in the Build and push stage
```
buildx call failed with: error: failed to solve: rpc error: code = Unknown desc = unexpected status: 403 Forbidden |  
-- | --
```

Found [this post](https://github.com/docker/build-push-action/issues/238#issuecomment-732076215).  Seems like the runner may be runnig out of space. 

https://gitmemory.com/issue/docker/build-push-action/238/748332465

Building the image locally results in a `868.04 MB` image and takes forever to build.

[Using Alpine can make Python Docker builds 50× slower](https://pythonspeed.com/articles/alpine-docker-python/)

https://github.com/AppDaemon/appdaemon/issues/1073

Proposal: Use `python:3.8-slim`

**Comment by Odianosen25** [comment]
Yeah I have read that article before, thanks for sharing again.

I guess this is a very valid point why we may have to consider reverting to slim.

But will have to discuss it with the others. Are you on our Discord server?

Regards

**Comment by wernerhp** [comment]
I joined the Discord server now.

**Comment by acockburn** [comment]
We moved to semaphore for CI - I could never get the GitHub builds to work, semaphore worked first time.
