### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by fabaff** [AppDaemon/appdaemon#1217]
It would be nice if there would be a new release. Especially because of the dependencies which are outdated in 4.0.5.

Thanks

**Comment by acockburn** [comment]
Hi Fabian, we've been working through a huge number of PRs and updated dependencies recently to try and get a release out so your reminder is timely :)

I'm hoping to get a new release out in the next week or two.

**Comment by acockburn** [comment]
Since you asked Fabien:

https://community.home-assistant.io/t/announcement-appdaemon-4-0-6/292258

:)
