### ISSUE TITLE
4.0.6 Release missing on GitHub

### ISSUE THREAD

**Issue by frenck** [AppDaemon/appdaemon#1221]
Hi!

I just saw the announcement of AppDaemon 4.0.6, however, it is missing on the GitHub releases.

Could the right tag be added? This allows for comparing and reviewing changes in a patch release like this.

![image](https://user-images.githubusercontent.com/195327/111913427-53afd500-8a6e-11eb-8ee2-2a6a34d45be1.png)

**Comment by acockburn** [comment]
It should have been tagged already - let me take a look.

**Comment by acockburn** [comment]
OK, new IDE without the checkbox selected to push the tags. Should be there now.
