### ISSUE TITLE
Question: Version policy

### ISSUE THREAD

**Issue by frenck** [AppDaemon/appdaemon#1222]
Small question regarding the release/versioning policy of AppDaemon.

It seems like the patch release bump from 4.0.5 -> 4.0.6, several new features and breaking changes are shipped.

Hence, my question would be: What does the major, minor and patch release scope for AppDaemon, I could not find any documentation on that. Is there a standard followed?

**Comment by acockburn** [comment]
No, as you have correctly identified, we don't have a firm policy.  Would you care to suggest one we could use (I presume HASS has one)? if it would assist you with your appdaemon integrations?

**Comment by frenck** [comment]
Home Assistant uses datever with a patch number (which is kinda different). However, the AppDaemon version number feels "semver" (although that doesn't have to be?).

Nevertheless, in general, I think one should not ship breaking change in a patch release. One should be able to apply patches without issues.

**Comment by acockburn** [comment]
Fair comment - I'll put some thought into a more consistent versioning policy moving forward.

**Comment by acockburn** [comment]
Here is the official policy - thanks for calling this out:

https://appdaemon.readthedocs.io/en/latest/INSTALL.html#appdaemon-versioning-strategy
