### ISSUE TITLE
[Bug] get_history() fails in 4.0.6

### ISSUE THREAD

**Issue by ivdimitro** [AppDaemon/appdaemon#1223]
Hello, 
I am using the docker version of appdaemon "acockburn/appdaemon:latest"
After the update to 4.0.6 my get_history() calls are failing with the following error: 

`2021-03-22 12:15:23.030432 WARNING bath_v_manager: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/appdaemon/threading.py", line 890, in worker
    funcref(self.AD.sched.sanitize_timer_kwargs(app, args["kwargs"]))
  File "/conf/apps/valve_manager.py", line 67, in manage
    "   " + "avg_temp: " + "{:.2f}".format(self.get_average_temperature()) +
  File "/conf/apps/valve_manager.py", line 29, in get_average_temperature
    history = self.get_history(self.sensor_current_temp, start_time = start_time)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/utils.py", line 197, in inner_sync_wrapper
    f = run_coroutine_threadsafe(self, coro(self, *args, **kwargs))
  File "/usr/local/lib/python3.8/site-packages/appdaemon/utils.py", line 308, in run_coroutine_threadsafe
    result = future.result(self.AD.internal_function_timeout)
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 439, in result
    return self.__get_result()
  File "/usr/local/lib/python3.8/concurrent/futures/_base.py", line 388, in __get_result
    raise self._exception
  File "/usr/local/lib/python3.8/site-packages/appdaemon/plugins/hass/hassapi.py", line 29, in coro_wrapper
    return await coro(*args, **kwargs)
TypeError: get_history() takes 1 positional argument but 2 were given`

The code that causes the error is: 

`start_time = datetime.datetime.now() - datetime.timedelta(minutes=self.args["history_interval"])
 history = self.get_history(self.sensor_current_temp, start_time = start_time)`

It has not been changed since 4.0.4, when I first wrote it. I also checked the documentation and the API seems is the same so it should still work. 
Any suggestions if this bug in 4.0.6 or should I change something? 
Thanks.

**Comment by ReneTode** [comment]
i think you need to change it to
```
self.get_history(entity_id = self.sensor_current_temp, start_time = start_time)
```
possibly because entity_id was a positional argument before and not anymore.

**Comment by Odianosen25** [comment]
@ivdimitro,

As @ReneTode just said, its a breaking change in 4.0.6. Make the change and it should be all good.

Regards

**Comment by ReneTode** [comment]
> As @ReneTode just said, its a breaking change in 4.0.6

oops, but not mentioned as breaking change ;)

**Comment by ivdimitro** [comment]
> > As @ReneTode just said, its a breaking change in 4.0.6
> 
> oops, but not mentioned as breaking change ;)

Definitely breaking ;) 

Thanks for the quick replies. All fixed now.

**Comment by Odianosen25** [comment]
Oh no its a breaking change from 4.0.4 to 4.0.5. So it doesn't belong to 4.0.6 as a breaking change.

Glad all solved for you @ivdimitro

**Comment by ReneTode** [comment]
> Oh no its a breaking change from 4.0.4 to 4.0.5. So it doesn't belong to 4.0.6 as a breaking change

i see, its indeed mentioned there. my error i didnt look close enough. forget i said anything ;)

**Comment by ivdimitro** [comment]
I quickly tested 4.0.4 and 4.0.5 and I also discovered that it was not working. I guess I started using appdaemon earlier than 4.0.4 :). I will fix the title. 
I have automatic upgrade script for my containers but I guess it wasn't working till now.

**Comment by ivdimitro** [comment]
Hi, after reverting to latest I am getting different error: 
`2021-03-22 14:11:01.022145 ERROR HASS: ------------------------------------------------------------
2021-03-22 14:11:01.023962 ERROR HASS: Unexpected error during get_history
2021-03-22 14:11:01.024154 ERROR HASS: ------------------------------------------------------------
2021-03-22 14:11:01.025368 ERROR HASS: Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/appdaemon/plugins/hass/hassplugin.py", line 559, in get_history
    api_url = await self.get_history_api(**kwargs)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/plugins/hass/hassplugin.py", line 614, in get_history_api
    start_time = as_datetime(kwargs, "start_time")
  File "/usr/local/lib/python3.8/site-packages/appdaemon/plugins/hass/hassplugin.py", line 610, in as_datetime
    return self.AD.tz.localize(args(key)).replace(microsecond=0)
TypeError: 'dict' object is not callable`

This is part of the fix for get_history() introduced in 4.0.6. 

My code is the same as above + plus the fix: 
`        start_time = datetime.datetime.now() - datetime.timedelta(minutes=self.args["history_interval"])
        history = self.get_history(entity_id = self.sensor_current_temp, start_time = start_time)`

**Comment by Odianosen25** [comment]
Yes @ivdimitro,

That is a bug and will release a fix for that asap.

For now can you kindly revert as you said, apologies about this.

Regards

**Comment by ivdimitro** [comment]
Thanks for the help. Running 4.0.5 for now.

**Comment by Odianosen25** [comment]
This has been fixed in the present dev, and will be released over the weekend.

**Comment by ivdimitro** [comment]
Thanks a lot. It is working correctly in 4.0.7

**Comment by Odianosen25** [comment]
You welcome @ivdimitro
