### ISSUE TITLE
AppDaemon get_history call and parsing the return value

### ISSUE THREAD

**Issue by Lumpusz** [AppDaemon/appdaemon#1227]
Hi,

I tried to find documentation as to how to properly parse the `get_history` result.

I call this function from my script:
`self.get_history(entity_id=HISTORY_SENSOR, days=5)`

If the sensor does not have history, I get back:
`[]`

If it has some history, I get back:
`[[{'entity_id': 'sensor.irrigation_weather_history', 'state': 'light snow', 'attributes': {'date': '20210319', 'max_temp': 6.15, 'rain': 0.76}, 'last_changed': '2021-03-23T15:17:18+00:00', 'last_updated': '2021-03-23T15:17:18+00:00'}, {'entity_id': 'sensor.irrigation_weather_history', 'state': 'broken clouds', 'attributes': {'date': '20210320', 'max_temp': 6.09, 'rain': 0.0}, 'last_changed': '2021-03-23T15:17:19+00:00', 'last_updated': '2021-03-23T15:17:19+00:00'}, {'entity_id': 'sensor.irrigation_weather_history', 'state': 'clear sky', 'attributes': {'date': '20210321', 'max_temp': 6.69, 'rain': 0.0}, 'last_changed': '2021-03-23T15:17:19+00:00', 'last_updated': '2021-03-23T15:17:19+00:00'}, {'entity_id': 'sensor.irrigation_weather_history', 'state': 'broken clouds', 'attributes': {'date': '20210322', 'max_temp': 7.12, 'rain': 0.0}, 'last_changed': '2021-03-23T15:17:19+00:00', 'last_updated': '2021-03-23T15:17:19+00:00'}]]`

Why is the return value a two dimensional list? If I filter on entity I would expect a one dimensional list, with the history, if it is for all entities, I would expect something like this:
`['entity_1': [{'history_1: ...},{'history_2': ...}], 'entity_2' :[...]]`

Can someone explain how this is assembled, and what is the correct algorithm to parse the response?

**Comment by Odianosen25** [comment]
@Lumpusz,

Well that’s a good point. But we don’t control how that is given to us, as it’s literally taken from HA and fed back through.

Regards

**Comment by Lumpusz** [comment]
> @Lumpusz,
> 
> Well that’s a good point. But we don’t control how that is given to us, as it’s literally taken from HA and fed back through.
> 
> Regards

I see. Can you explain though what is the proper way to parse the response? I had cases when I had multiple lists embedded in the top level list, both containing dicts of the same entity. Do I choose the first one ore the Nth one?

**Comment by Odianosen25** [comment]
Really neither can I help with that I am afraid.

You will just have to log the responses, and based on how it comes in, parse the data.

Regards

**Comment by Lumpusz** [comment]
One more anomaly I detected is that I don't get back the entire history:
For the same call I get back 4 records, but in the DB I have 5:
`SELECT count(*) FROM states WHERE entity_id='sensor.irrigation_weather_history'`
This query returns 5, and in the appdaemon script the first records is not returned. Even without the `day` filter, I get back 4 records.

**Comment by Odianosen25** [comment]
@Lumpusz,

yeah I understand what you are saying. As I had said earlier, we just passing over what HA is giving us. I am not sure what more to do really. Can you try an api request directly to HA and see if the results are different?

regards

**Comment by Odianosen25** [comment]
Closing this now @Lumpusz
