### ISSUE TITLE
Appdaemon does not work on some browsers

### ISSUE THREAD

**Issue by Zylazy** [AppDaemon/appdaemon#1232]
Some days ago I have noticed that the dashboard could not be displayed anymore. Inspecting the page I have noticed that the problem is in the compiled application.js file in the OnStateUpdate function. There is a syntax error in the line:
            self.timeout = setTimeout(() => set_view(self, self.state), delay_time * 1000);

It works fine using Chrome, but gives error and stop working in IE (but who cares), AND Fully Kiosk Browser (what I am using).

**Comment by acockburn** [comment]
Thanks for reporting - we have a fix for this particular issue in dev already, and we will be doing a release this weekend.
