### ISSUE TITLE
`clientid` to use in `dash_navigate`

### ISSUE THREAD

**Issue by ajitam** [AppDaemon/appdaemon#1276]
(Sorry if this is not the right place to put this, but I can't find any community/chat for Appdaemon)

I' trying to use https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html#appdaemon.adapi.ADAPI.dash_navigate

but I can find the `clientid` since I have multiple dashboards (devices) and I want to change only one of them.

Thx

**Comment by ReneTode** [comment]
our chat: https://discord.gg/wrdqRK6

you can use deviceid, not clientid
and you can set the device id by adding it to the url.
https://appdaemon.readthedocs.io/en/latest/DASHBOARD_CREATION.html#setting-a-deviceid

**Comment by ajitam** [comment]
I'm so sorry about this. everywhere I searched I searched for `clientid` instead of `clientid`.
Thank you
