### ISSUE TITLE
When trying to start docker container: standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by Hendri-88** [AppDaemon/appdaemon#1298]
When trying to run;

docker run --rm -it -p 5050:5050 \
  -e HA_URL="http://192.168.x.x:8123" \
  -e TOKEN="HAToken" \
  -e DASH_URL="http://192.168.x.x:5050" \
  acockburn/appdaemon:latest

I get the following error;
standard_init_linux.go:211: exec user process caused "exec format error"

Running:
Operating System: Ubuntu 20.04.1 LTS
Kernel: Linux 4.9.230-35
Architecture: arm64

Docker version:
19.03.8

When using bubuplanet/appdaemon container starts, but app does not work.

Please advice.

**Comment by ReneTode** [comment]
please show the entire log from the moment you try to start appdaemon till it goes wrong.

**Comment by Hendri-88** [comment]
![image](https://user-images.githubusercontent.com/86837491/124384324-e8aea500-dcd0-11eb-96bd-fb692e118c94.png)

**Comment by Hendri-88** [comment]
There is not alot of extra info ;)

**Comment by ReneTode** [comment]
i ment the AD log, but i guess thats never started.
but i need to call @Odianosen25 for this, because i have no exp with docker.

**Comment by ruifung** [comment]
That's probably because the latest tag isn't multi-arch yet.

And I'm assuming your odroid device is an ARM based device, so it's incompatible with the latest tag for now.

Seems like the 4.1.0has multi-arch support for ARM though it's not been "released" yet, so use the :dev tag if you want that, or if you want the latest "release" which is 4.0.8, you need to build the image yourself. Which is what I did to get it running on my pi 4.

**Comment by Hendri-88** [comment]
Hi @ruifung,
My device is indeed ARM64, as stated in the starting post.
I will try the :dev tag, and check if the container will start then.
Is there a roadmap available when the :latest will be ARM64 compatible?

**Comment by ReneTode** [comment]
> Is there a roadmap available when the :latest will be ARM64 compatible?

no

**Comment by ruifung** [comment]
> 
> 
> Hi @ruifung,
> My device is indeed ARM64, as stated in the starting post.
> I will try the :dev tag, and check if the container will start then.
> Is there a roadmap available when the :latest will be ARM64 compatible?

Honestly, if you want the latest official release, just clone the repo and just docker build it... or point your compose file at it using build instead of image. That's what I do.

**Comment by acockburn** [comment]
Hopefully in the next release of the pipeline is working correctly.

**Comment by Hendri-88** [comment]
I have setup a working app now in AppDaemon, thanks for the tip of using :dev.
Where could i check if the :latest supports my device?
Could i get a notification about this?

**Comment by ruifung** [comment]
You can check on Docker Hub? Like, under tags it lists all the supported arch for each tag.

**Comment by Hendri-88** [comment]
Thnx, I will periodically check the Docker Hub!
