### ISSUE TITLE
New release for python 3.9 fix?

### ISSUE THREAD

**Issue by dekiesel** [AppDaemon/appdaemon#1303]
Hi,

could you release a new version containing fix [change Task.all_tasks() to asyncio.all_tasks() for python 3.9](https://github.com/AppDaemon/appdaemon/commit/bb82b6d668b564709a5c7c9925a01dadb18d78e3)?

Currently it looks like appdaemon is broken if you use the latest release (4.0.8) and python 3.9.

>AttributeError: type object '_asyncio.Task' has no attribute 'all_tasks'

**Comment by frenck** [comment]
I support this message, would love to be able to bump to Alpine 3.14

**Comment by acockburn** [comment]
We have made this fix in dev and it will be available in the next release.

@frenck - sure thing, we'll look into updating the docker image too for that release.

**Comment by dmitriy5181** [comment]
Same problem with appdaemon 4.0.8 and python 3.9. Can be fixed by applying the bb82b6d668b564709a5c7c9925a01dadb18d78e3 manually to installed released version. Any ETA for a new release, though?

**Comment by frenck** [comment]
I can no longer keep up the maintenance of the add-on at this point, as Alpine 3.14 is on Python 3.9.
Can't complete generic add-on improvement rollouts, can't close up known CVEs.

This currently affects around ~40K active installations of the AppDaemon add-on.

Any insight on when we can expect Python 3.9 support to be released?

**Comment by acockburn** [comment]
In comment above I meant to say a 3.9 docker image not Alpine 3.14 - new AD will be released later today.

**Comment by frenck** [comment]
> In comment above I meant to say a 3.9 docker image not Alpine 3.14

The community add-ons are on Alpine.

> new AD will be released later today.

🎉  Thank you!
