### ISSUE TITLE
When app's thread dies, kill app

### ISSUE THREAD

**Issue by Odianosen25** [AppDaemon/appdaemon#1306]
When an app's thread dies, the app should be stopped before attempting to re-create the thread again. This way giving the user time to fix the issue.

**Comment by ReneTode** [comment]
actually it would even be better:

- app comes in trouble (for whatever reason)
- stop app (if possible)
- if last time that app was restarted is longer then set delay
- restart app (if possible)

**Comment by Odianosen25** [comment]
> if last time that app was restarted is longer then set delay

That's gonna be interesting to do really, but I guess should be available from the app's entity.

When you say delay, what exactly is meant and why?

**Comment by ReneTode** [comment]
i think there should be a default delay from lets say 10 sec. before and app can be restarted twice.
and that delay should probably be configurable (as main setting, and or app setting)

why?

because then the app wont go into a restarting loop anymore when it dies strangely.

**Comment by Odianosen25** [comment]
> because then the app wont go into a restarting loop anymore when it dies strangely.

If that's the case, then it's better handled within the threading module

**Comment by ReneTode** [comment]
you cant handle it on thread level, because (as you know) you can have several apps in 1 thread.
