### ISSUE TITLE
listen_event applies filtering using keyword arg "timeout"

### ISSUE THREAD

**Issue by ruifung** [AppDaemon/appdaemon#1308]
As per the documentation, the "timeout" kwarg is supposed to remove the listener after a specified period,

However if it's specified, it also applies to event filtering, meaning that if the event data has a timeout parameter (i.e. for push notifications) it will apply filtering to it and reject the event.

Perhaps any parameter used for appdaemon's operation should not be applied to filtering incoming events as this seems to be contrary to what is described in the documentation.

Either that, or perhaps the filtering dictionary could be made explicit rather then a kwargs parameter that may result in keyword name conflicts with appdaemon arguments.

**Comment by ReneTode** [comment]
perhaps you should clarify more.

if you use timeout in a listener, the listener will stop listening, but the event will still be there.
AD doesnt reject events at all.
so if you got 2 listeners:
```
self.listen_event(self.cb1, event="some event")
self.listen_event(self.cb2, event="some event", timeout = 30)
```
in the first 30 seconds both CBs will be called, and after 30 seconds only cb2 will be fired.

**Comment by Odianosen25** [comment]
@ruifung,

Then why not avoid using `timeout` in the event being fired?

This could honestly be fixed by simply removing the `timeout` keyword when registering the callback, but if done here we will have to do it for everything and that's not exactly a good strategy in my opinion.

So ensure the event doesn't have it, and if it can't be helped let us know.

Kind regards

**Comment by ruifung** [comment]
@Odianosen25 because the event is a push notification action response from the home assistant companion app, and timeout is used there as to tell the android app that this notification will time out. And the response event to the action sends back all the data sent to create the notification, which does include the timeout.

So yeah, the timeout data key is specified in https://companion.home-assistant.io/docs/notifications/notifications-basic/#notification-timeout. So I don't exactly control the naming of keywords in the events.

@ReneTode Register with a timeout, then send a event with a data entry also named "timeout". AD will register the listener with a timeout, and then proceed to filter the event's timeout attribute against the timeout kwarg.

**Comment by Odianosen25** [comment]
Since that’s the case, then I guess the “timeout” will need to be removed from kwargs when listening to the event.

kind regards

**Comment by ruifung** [comment]
Just to be clear, are you talking about my apps not using timeout when listening or are you talking about in AD to remove it from the kwarg dict before passing it on..?

**Comment by Odianosen25** [comment]
> Just to be clear, are you talking about my apps not using timeout when listening

Nope

> you talking about in AD to remove it from the kwarg dict before passing it on

Yep

**Comment by ReneTode** [comment]
conflicting keywords will always exist.

but this event is a service that is used to notify a mobile app.
its not there to listen for it in AD.
for that you can create any other event.

so allthough you CAN listen for that event, i dont think you SHOULD listen for it.
if you create apps in AD, then that is more a service in HA that you call from AD then that you listen for it.

**Comment by ruifung** [comment]
@ReneTode  How else are you supposed to respond to the action on the notification. The event is for a *response* from the notification. I.e. mobile app -> HA -> AD

**Comment by Odianosen25** [comment]
@ruifung,

for now a simple workaround will be to not use the “timestamp” keyword in the listen api, and do it old style of you want it to be removed after a while by following the sequence:

- Listen for the event 
- Get the handle and store it
- Use a run_in for the time you want to remove the listen event (can add the handle as a keyword actually)
- When the scheduler runs, cancel the listen event
- 

That way you still get what you want, until we decide how to resolve this.

**Comment by Odianosen25** [comment]
@ruifung,

Fix now in dev so will be losing this, and we will be releasing a new version of AD this weekend.

Regards
