### ISSUE TITLE
Unknown namespace (appdaemon)

### ISSUE THREAD

**Issue by dekiesel** [AppDaemon/appdaemon#1309]
Hi,

since I updated to 4.0.8 (from 4.0.5) this doesn't seem to work anymore:

`self.call_service("production_mode/set", mode=True, namespace="appdaemon")
`
Result:

`today at 13:48:05 2021-07-19 13:48:05.955106 WARNING AppDaemon: Unknown namespace (appdaemon) in call_service from proddev_toggle`

From what I can gather from the changelogs there have been some changes to namespaces, but the [docs](https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html) still say that the `call_service` should work.

Any idea what I could try?

**Comment by Odianosen25** [comment]
@dekiesel,

The API has been updated and try:

```
self.call_service("production_mode/set", mode=True, namespace="admin")
```

Regards

**Comment by dekiesel** [comment]
That did it, thanks!
