### ISSUE TITLE
Bug: set_state() removes all attributes no matter how you set the replace flag 

### ISSUE THREAD

**Issue by ihaettypo** [AppDaemon/appdaemon#1318]
It seems when under the default namespace (hass plugin), no matter how you set the _**replace**_ flag, the behavior would always be to replace/reset the whole attributes object. For example, all of the following code will result in an empty attributes object for the entity _light.light_1_ (which is created by set_state() in appdaemon):

`self.set_state("light.light_1", state = "on")`

`self.set_state("light.light_1", state = "on", replace=False)`

`self.set_state("light.light_1", state = "on", replace=True)`

Meanwhile, this bug does not exist when under user defined namespaces, such as:

`self.set_state("light.light_1", state = "on", namespace: "my_namespace")`

**Comment by Odianosen25** [comment]
@ihaettypo,

When dealing with the `HASS` plugin, its a HA way that any `set_state` will over ride all the previous data in the entity. That is why I believe the docs does state that the `replace` flag is only for internal AD entity only.

So to properly set the state in `HASS`, you need to get all the attributes in the entity as a dict, then update the dict and use the data to `set_state` again and that should do what you want.

Regards

**Comment by ihaettypo** [comment]
Hi @Odianosen25 ,

Thanks for the quick reply. I understand the issue now.

However, is it possible that you guys add another layer under the hood to help deal with the inconveninence? I'm currently using `self.set_state("light.light_1", state = "on", attributes=self.get_state("light.light_1", attribute="all")["attributes"])` to get it to work properly. But when you need to only update one of the attributes, you need to first get the attributes, then check if the target attribute exsists, then update it and write the whole thing back. 

I mean, is it possible that you can get deal with it within the plugin, and make the "replace" mechanism work the same across namespaces?

**Comment by ReneTode** [comment]
there are way more problems with setting the state from HASS entities.
in general its advised not to use it at all unless its for a sensor that is created by AD.

why would you want to use set_state to change the state from a light?
thats why there are services, so my advise is to only change the state by using services.

**Comment by Odianosen25** [comment]
@ihaettypo,

I am closing this issue, as just follow @ReneTode's advise on this. Can re-open is having other issues related to this.

Regards
