### ISSUE TITLE
Workaround for millisecond timing? 

### ISSUE THREAD

**Issue by dekiesel** [AppDaemon/appdaemon#1340]
Hi,

I have a zigbee wall switch to which I'd like to add double/triple click functionality. 

Ideally the automation would wait 500ms after the first click to see whether I click the same button a second time. If I don't it reports one click to home assistant and if I do it waits another 500ms to see whether I click the same button a third time. If I don't it reports two clicks (three if I do click it a third time).

According to [this issue](https://github.com/AppDaemon/appdaemon/issues/26) ADs internal resolution is one second and changing that would require a lot of work. 

My question is whether there is a workaround for my specific case which can be done in appdaemon. I know I can do it on HA, but all my automations are in AD and I'd like to keep it that way. 

Thank you for your input!

**Comment by ReneTode** [comment]
no workaround needed.

just the right listen_state and save a timestamp in the app and compare that with the previous timestamp

and you quote an issue from 4 years ago, since then AD has changed a lot.

**Comment by dekiesel** [comment]
That was my first impulse too, but the issue is how do I stop waiting after 500ms if `run_in` doesn't support sub second precision?

Let's say my `listen_state` listens for button clicks: how can it stop waiting after 500ms? I don't know if there'll be 1,2 or 3 clicks so I need a timeout.

**Comment by ReneTode** [comment]
```
def cb(...):
   if self.previousclick_ts < now() - 500ms:
       self.single_click_handle = self.run_in(self.cb_singleclick, 0.5)
  else:
       self.run_in(self.cb_doubleclick, 0)
       self.cancel_timer(self.single_click_handle)
```
 this will start singleclick after 0.5 seconds, and doubleclick immediatly.
 simular constructions can be used for tripleclick.
 
 the waiting isnt stopped in the run_in, but in the listen_state CB.
 and run_in supports sub second (allthough that is always difficult to a certain precision, because its python and the run_in needs to be scheduled, and that will always take time)
 
 if you want more help feel free to get to our discord.

**Comment by dekiesel** [comment]
Ah, thanks I didn't know run_in now supports sub second precision. [The docs](https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html) still say `integer` and `seconds`, so I assumed sub second precision wasn't possible.

It's fine that it's off by a few milliseconds, I just think 500 feels to long.

Thanks for the insight and thanks for the code, much appreciated!

**Comment by ReneTode** [comment]
waiting half a second after you click isnt that long. 
making it shorter will probably make it less reliable, but you can play with it.
good luck
