### ISSUE TITLE
Rework REST Service Calls to AD

### ISSUE THREAD

**Issue by Odianosen25** [AppDaemon/appdaemon#1344]
REST service calls to AD should do the following
- Return 202 to the user to indicate still processing and a resultId
- Should not wait for the service call to be completed
- The user can use the returned id to collect the result later if interested 
- The result of the call should be kept for the user for a maximum time of `x` minutes
- The the user doesn't pick it up, it destroys it

**Comment by acockburn** [comment]
Please issue a PR for these ;)
