### ISSUE TITLE
register_endpoint fails since version 4.0.1

### ISSUE THREAD

**Issue by danhei** [AppDaemon/appdaemon#1354]
Hello,

since version 4.1.0 register_endpoint() does not work when more than one app registers endpoints and one of these apps is restarted. It always says that the endpoint is already registered to another app (which is not true). The endpoints are correctly registered (and deregistered) and there are no duplicate endpoint names.

I had a look at the file http.py:

```
async def register_endpoint(self, cb: Callable, endpoint: str, name: str, **kwargs: Optional[dict]) -> str:

        handle = uuid.uuid4().hex

        # first we check to ensure that endpoint not been used before
        for name in self.app_endpoints:
            for _, handle_data in self.app_endpoints[name].items():
                if handle_data["endpoint"] == endpoint:
                    # it exists already so don't let it pass
                    raise AttributeError(f"The given endpoint '{endpoint}' already exists and used by {name}")

        if name not in self.app_endpoints:
            self.app_endpoints[name] = {}

        self.app_endpoints[name][handle] = {"callback": cb, "endpoint": endpoint, "kwargs": kwargs}

        return handle
```
`name` is defined twice: as function parameter and as variable of the for loop. Could this be a bug?

**Comment by Odianosen25** [comment]
@danhei,

That is a good point. 

Can you kindly make a PR to fix this?

Kind regards
