### ISSUE TITLE
run_daily ignores the clock change

### ISSUE THREAD

**Issue by tobi-bo** [AppDaemon/appdaemon#1378]
Last weekend my time zone changed from summer time (CEST) to winter time (CET). I have an alarm clock app in AppDaemon that is started with run_daily at the set alarm time.
In my logs I can see that the Alarm time is set right with self.run_daily(callback, "07:30:00"), but with the time change the callback was actually called at 8:30 (one our later, because the clock was shifted from 3:00 back to 2:00 at night).

Here are my logs, related to this:
```
2021-10-31 00:28:21.203164 INFO wecker: Starten des Weckers um 07:30:00.
2021-10-31 08:30:00.239348 INFO wecker: Scheinwerfer-Delay gestartet, Duration: 00:10:00, Estimated End: 2021-10-31 08:40:00.221765+01:00
```

I would expect run_daily to take the time change into account in this case, since the time (07:30:00) was specified explicitly. Or at least there should be a switch for run_daily to achieve this behavior.

**Comment by ReneTode** [comment]
the time change is still not perfect. but its hard to test, because it only happens once a year.

**Comment by angelnu** [comment]
It also happened this year - a daily alarm set at 6:45 before the time change triggered one hour later.

I checked the callbacks in the UI and I found something quite curious:

- "morning" daily schedules are wrong - they are all one hour too late
- "evening" daily schedules (22:00, 22:01) - they are correct.

So there might be some code correcting the schedules that only "fix" some of them. Will go through the schedule to see if I find any suspicious code.

**Comment by acockburn** [comment]
This is a known issue and will be fixed at some point. We have other issues open for it so closing this one,
