### ISSUE TITLE
ML package sklearn and pickle not loaded

### ISSUE THREAD

**Issue by aportillagithub** [AppDaemon/appdaemon#1389]
Hi all. I’m trying to use an already trained model saved with pickle and using it in appdaemon app. I’m having problems importing pickle and scklearn to load and use model from file inside appdaemon (hassio).
Can anyone tell if it’s even possible?
Thanks.

**Comment by ReneTode** [comment]
youll need to put the packages that you want to use in the requirements from the addon.
and its possible that pickle and scklearn need other packages that you then also need to add to requirements.

when you had AD as standalone installed it would just need pip ... but in docker and in the addon it all goes through the requirements.
