### ISSUE TITLE
Question: Should I avoid firing `state_changed` events?

### ISSUE THREAD

**Issue by dekiesel** [AppDaemon/appdaemon#1411]
I have a button (via zigbee2mqtt) that only publishes `on` and `brightness_up`.

I wanted to add double/triple/n-click behaviour and wrote an app that collects all button-pushes in a certain timeframe and then fires a `state_changed` event with the number of times the button has been pushed.

Example code:

```
kwargs={'entity_id': my_buttons_entity_id,
       'new_state': {'state': f'pushed_{nr_of_times_pressed}'}
}
self.fire_event('state_changed',**kwargs)
```

This leads to appdaemon saying (in `events.py`, line 234, version 4.0.8):

```
if data["data"]["new_state"]==data["data"]["old_state"]
KeyError: 'old_state'

```
For the time being I 'fixed' this by adding an empty `old_state`:
```
kwargs={'entity_id': my_buttons_entity_id,
       'new_state': {'state': f'pushed_{nr_of_times_pressed}'},
       'old_state': {'state': ''}
}
self.fire_event('state_changed',**kwargs)
```

The reason I am putting my state into a dict formed like this is because I have other apps that expect the data to be in a dict in `new_state`.

But I am wondering if I am voiding certain checks that are there for a very good reason?

Thanks for any help.

**Comment by ReneTode** [comment]
i wouldnt use an custom state changed event.
why dot you just use the set_state() function?

**Comment by dekiesel** [comment]
If I remember correctly the issue with these buttons was that they don't send an `on_release`-message, meaning that I can only catch repeated pushes of the button by monitoring the event.

I'll fire a custom event (like `my_state_changed`) then.

**Comment by ReneTode** [comment]
you can still monitor the event like you do, but this:
```
kwargs={'entity_id': my_buttons_entity_id,
       'new_state': {'state': f'pushed_{nr_of_times_pressed}'}
}
self.fire_event('state_changed',**kwargs)
```

is actually trying the same as:
```
self.set_state('my_buttons_entity_id', state = f'pushed_{nr_of_times_pressed}')
```
the only difference is that it uses a service that is actually looking at the state and uses that to create the old state.
after that you used set_state, you still can listen for the state_changed event like you did before, because set_state also fires that event.
