### ISSUE TITLE
self.log() with python type() logging a blank

### ISSUE THREAD

**Issue by jim999** [AppDaemon/appdaemon#1416]
First of all apologies if I am logging this incorrectly - first time for me

if I test if for the python type then the test works
if I write the response to the log then it is blank as shown in actual log output where I would have expected what is shown in
expected log output

if type(self.args["group"])==list:
self.log(">>>> {} its a list {}".format(type(self.args["group"]),self.args["group"]))

apps.yaml content ---

test_expand:
> module: test_expand_group:
> class: test_expand_group
> group: [group.all_lights,]
> logging: True

actual log output:
2021-12-14 08:41:50.529586 INFO test_expand_group: >>> its a list ['group.all_lights']

expected log output:
2021-12-14 08:41:50.529586 INFO test_expand_group: >>><class 'list'> its a list ['group.all_lights']

**Comment by ReneTode** [comment]
it depends on where you look.
in the log there is <class 'list'>
but if you view the log in a webpage (where the log is shown 1 on 1) html hides it because its a command.

**Comment by jim999** [comment]
Thanks, I can see it in the addon log in homeassistant
