### ISSUE TITLE
self.listen_state bug when using entity=

### ISSUE THREAD

**Issue by Travis-Prall** [AppDaemon/appdaemon#1429]
I upgraded app-daemon today and noticed all my code where I declared my variables, I used entity= in self.listen_state, was not working and seemed to move entity into an attribute. My debug log showed it was listening to everything.

Example:
self.listen_state(self.some_function, entity=light.front)

VS

self.listen_state(self.some_function, light.front)

Removing the declared variable entity fixed it ,but still an unexpected behavior.

[The documentation](https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html?highlight=self.listen#appdaemon.adapi.ADAPI.listen_state)

**Comment by Odianosen25** [comment]
Hello @Travis-Prall,

I guess you are using the `dev`, as if that is the case, as much as we greatly appreciate it for trying it out, in the next release there are a couple of breaking changes which unfortunately includes what you noticed am afraid.

Going forward we will be standardizing the way entities are declared from using `entity` to `entity_id`.

Kindly update your code and it should all work.

Kind regards

**Comment by Odianosen25** [comment]
Will b closing this @Travis-Prall,

Do open if more issues arise
