### ISSUE TITLE
"Entity xx created in namespace: default" 3.0.5->4.1.0

### ISSUE THREAD

**Issue by hhaim** [AppDaemon/appdaemon#1430]
When moving from 3.0.5 -> 4.1.0

1. This is the warning  ```Entity xx created in namespace: default``` in the log
2. The attributes are cleared (because appd is wrongly creating the variable without the info)
3. This is the code that creates the "new" variable

```
       self.call_service('variable/set_variable', variable=var,value=val)
``

4. in 3.0.5 there is no issue
5. didn't find a way to disable this auto-creation and didn't find the reason it happen

what am I missing?

**Comment by Odianosen25** [comment]
Hello @hhaim,

Yes in 4.1.0 we do have that bug, and I want to believe you mean creating the entity in the `hass` namespace

This has been fixed in the latest dev, which will hopefully be released before the end of the year.

Kind regards

**Comment by hhaim** [comment]
@Odianosen25 that was fast. Thanks. 
Yes, I mean in  ```hass``` namespace. 
Now I see that even in 3.0.5 there is a false warning in this regards 
``` WARNING AppDaemon: xxx: Entity xxx not found in AppDaemon``` 
But everything works fine. so I believe it is a false 
What does this warning mean? (it is there in latest too)

**Comment by Odianosen25** [comment]
@hhaim,

Well I happed to be online when the question came in :).

As for the warning, before running a `set_state` AD first checks if the entity exists, and gives a warning to that effect. It will work, but its just a simple warning.

if you don't like it (like your truly), use the `add_entity` api first to create it, then use the `set_state`. Fact is the `add_entity` only works for AD's internal entities and will not propagate that to Hass, but as you said it still works.

regards

**Comment by Odianosen25** [comment]
@hhaim.

Will be closing this pls, reopen if not satisfied
