### ISSUE TITLE
kwargs in some service calls has wrong type hints

### ISSUE THREAD

**Issue by matejdro** [AppDaemon/appdaemon#1433]
In a recent release, type hints have been added to the kwargs of some of the service calls:

https://github.com/AppDaemon/appdaemon/blob/d74408cc9e60b11055a0b7ae3986d74de5ecb24c/appdaemon/adapi.py#L1673

However, those type hints are incorrect. What kwargs type hint should be is a hint for type of each individual parameter, not a dict of all parameters.  With current type hints, appdaemon expects every service argument to be a dictionary, which causes IDE warnings:

![image](https://user-images.githubusercontent.com/507922/147441799-c6075b8f-e094-4217-b060-f093f34583ec.png)

These hints should be type of `Optional[Any]`. I can make a PR to fix this if desired.

**Comment by Odianosen25** [comment]
Hello @matejdro,

Thanks for using dev and spotting this, though kind of weird missed. But I have updated the code, to reflect what you said.

kind regards
