### ISSUE TITLE
`self.listen_state(self.state_update, entity="xxx")` no longer filters to the `xxx` entity.

### ISSUE THREAD

**Issue by evanpurkhiser** [AppDaemon/appdaemon#1443]
In 4.2.1 it appears that calling `listen_state` with a specific entity specified causes other entities to be listened too.

I have the following code

```py
    def initialize(self):
        self.listen_state(self.state_update, entity="climate.apartment")

    def state_update(self, _entity, _attr, prev, new, kwargs):
        self.log('testing', _entity, _attr, prev, new, kwargs)
```

I would expect `_entity` to only ever be `climate.apartment`, but I am seeing logs that look like this

```
2022-01-03 13:39:22.086238 WARNING AppDaemon: message: testing, args: ('sensor.air_purifier_motor_speed', 'state', '352', '351', {'entity': 'climate.apartment', '__thread_id': 'thread-5'})
```

where did `sensor.air_purifier_motor_speed` come from?

**Comment by evanpurkhiser** [comment]
It appears that the API for `listen_state` has changed, [the `entity` parameter has been renamed to `entity_id`](https://github.com/AppDaemon/appdaemon/pull/1415/files#diff-b11861a48a2785244de71f88e342fde3b10650e4969df26fa396386e7bd4de2eR1252)

**Comment by evanpurkhiser** [comment]
Will leave it to a maintainer to close this issue. Not sure if the project should be concerned about an API breaking change.

**Comment by Odianosen25** [comment]
Hello @evanpurkhiser,

yes it’s been changed from entity to entity_id and it’s been duly documented as a breaking change in the release note.

will be closing this, and reopen if needed

regards

**Comment by evanpurkhiser** [comment]
Ah okay, I didn't realize breaking changes would be included in a minor version bump.

Thanks for your work @Odianosen25! Glad that it's consistent now!

**Comment by ReneTode** [comment]
@evanpurkhiser then perhaps you should read the docs:
https://appdaemon.readthedocs.io/en/latest/INSTALL.html#updating-appdaemon

it tells exactly where you can expect breaking changes ;)
