### ISSUE TITLE
AttributeError: 'ADAPI' object has no attribute 'get_entity'

### ISSUE THREAD

**Issue by prof7bit** [AppDaemon/appdaemon#1449]
Trying to follow the documentation as described here:

https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html#entity-class

but the method get_entity() does not seem to exist.

My code:

````python
class Automations(hass.Hass):

    def initialize(self):
        self.adapi = self.get_ad_api()
        self.light_esstisch = self.adapi.get_entity("light.esstisch")
````
I also cannot seem to find this method in the Hass class itself.

```
2022-01-07 14:09:18.575262 WARNING automations: Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/appdaemon/app_management.py", line 165, in initialize_app
    await utils.run_in_executor(self, init)
  File "/usr/lib/python3.9/site-packages/appdaemon/utils.py", line 308, in run_in_executor
    response = future.result()
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/appdaemon/apps/automations.py", line 9, in initialize
    self.light_esstisch = self.adapi.get_entity("light.esstisch")
AttributeError: 'ADAPI' object has no attribute 'get_entity'
```

This is either a documentation issue or I am just too stupid to read it correctly and figure out how on earth to get a reference to the entity or something else is wrong.

**Comment by ReneTode** [comment]
this will only work with new style apps. (not inheriting from hass, but from adbase.
https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html

**Comment by prof7bit** [comment]
It seems last night my home assistant has made an update of the plugin according to the logs, now I have 4.2.0 and now my above code is working as intended. I probably had an old version when I installed it yesterday.

I am closing this issue.
