### ISSUE TITLE
Minor Breaking Change

### ISSUE THREAD

**Issue by Matchlighter** [AppDaemon/appdaemon#1450]
Came home tonight to many of my AppDaemon apps working funky (HASS auto update). Tracked it back to https://github.com/AppDaemon/appdaemon/commit/6935880cd098c8aaf236203b2b3a711e5c78b70d where `entity` arguments were changed to `entity_id`. This affected a number of `listen_state()` calls where I have usually used it as a kwarg (`listen_state(callback, entity="")`). This may be more my fault being overly verbose, but wanted to make a call out.

**Comment by Odianosen25** [comment]
@Matchlighter,

Yeah we did make a change to that, and yeah received different complaints already 😬. 

Next time we will try to make such changes less well disturbing.

**Comment by Matchlighter** [comment]
🤦‍♂️ I didn't check the resolved issues first. Thanks and sorry for the noise!
