### ISSUE TITLE
FR: expose home assistant devices to appdaemon

### ISSUE THREAD

**Issue by frog32** [AppDaemon/appdaemon#1455]
Today appdaemon concentrates around home assistant entities. To allow for some maintenance oriented applications it would be great to expose home assistant devices as well.

These two things would be possible and would deliver a much cleaner user experience compared to going through the entities:
- track all devices that have a battery and alert if the battery is too low or if the device is offline entirely
- alert if a device is missing (failed device, broken integration...)

**Comment by Justihar** [comment]
Not really sure if what you're looking for is possible as far as working directly with devices or if there would really be any benefit as the entities is what you really need to work with. You can always use get_state to pull a list of entities and determine which entities have batteries by entity name and/or the attributes associated, collect a list of those entities and monitor the battery levels.
