### ISSUE TITLE
render_template appears to be broken on 4.2.0

### ISSUE THREAD

**Issue by jreed509** [AppDaemon/appdaemon#1457]
I'm using the home assistant addon and recently updated to the latest version. Calls to `hass.render_template()` appear to be broken after the upgrade to Appdaemon 4.2.0. All calls to this function seem to return `None`

For example calling `self.render_template("{{ is_state('sun.sun', 'above_horizon')}}")` should return a bool, but instead returns `None` after the latest update. I'm not seeing any error/warning messages in the logs after this call - just the incorrect response.

This call seems to work fine on prior versions.

**Comment by Justihar** [comment]
This is a bug due to the update to the way call_service works.

**Comment by Odianosen25** [comment]
@jreed509,

This is now fixed in dev and will be released this weekend. So closing this ticket for now
