### ISSUE TITLE
listen_state on person entity keeps triggering

### ISSUE THREAD

**Issue by josephkiser04** [AppDaemon/appdaemon#1466]
Recent changes with app deamon seems to have a bug with the listen state on a person entity. I have had a presence detection system for quite some time that listens for state changes to a person entity and upgrading to the latest version it seems that the state changes get repetitively triggered.  If you try running the code below you will see the issue.

```
class TestRoutine(hass.Hass):
    def initialize(self):
        self.listen_state(self.test_routine_cb, 'person.person')

    def test_routine_cb(self, *kwargs):
        # Print to log.
        self.log('I am here!')
```

**Comment by ReneTode** [comment]
your code is wrong.
the callback signature from listen state is:
```
def test_routine_cb(self, entity, attribute, new, old, kwargs):
```

**Comment by josephkiser04** [comment]
@ReneTode It was my understanding that passing the entity with no attribute listens to all attribute changes on the entity. In this instance I am interested mostly in listening to the main attribute (person state) and for any changes that happen also that the arguments for attribute, new, and old are all optional. This logic does work in my current code and has for a long time. If I use the exact same code in the latest release I get constant calls to test_routuine_cb. I am assuming there is something on the entity (not necessarily the main attribute) that keeps trigging the method since I am listening to all attribute changes. Is there a way to listen for ONLY the main attribute on a person entity?

**Comment by Klikini** [comment]
This started happening to me (but for an input_boolean) with version 4.2.0.

**Comment by ReneTode** [comment]
replace 
entity="input_boolean.lighting_override"
with
entity_id="input_boolean.lighting_override"
or just
"input_boolean.lighting_override"
and your problem is gone

**Comment by Klikini** [comment]
@ReneTode Replacing `entity` with `entity_id` seems to have fixed it, thanks!

@josephkiser04 Try calling `self.listen_state(self.test_routine_cb, entity_id='person.person')`

**Comment by josephkiser04** [comment]
@ReneTode @Klikini thank you so much for the suggestions sorry it took a bit to get back been super busy lately. Changing to entity_id solved my problem as well. Not sure what changed in recent versions that might have changed the behavior here. Since the issue at hand seems to be fixed I can close the ticket here but I didn't know if I should keep this open as it does seem to be a behavior change in some way so it may be something to look at. Let me know if you would like me to close or feel free to close. Thanks again!

**Comment by ReneTode** [comment]
it was a breaking change in the last release (see docs)

so you can close it (i cant ;) )

**Comment by josephkiser04** [comment]
Thanks for pointing that out I did not see it. And thank you all again for the help!
