### ISSUE TITLE
Make AppDaemon more resilient when removing log files

### ISSUE THREAD

**Issue by henning-meinhardt** [AppDaemon/appdaemon#1470]
When physically removing the logfile that is currently shown on AppDaemon's UI, the latest log messages are still present even if you switch to some other log and back to the one you just removed. Worse, when doing a full page reload no more logs can be shown, the drop down box to chose the logfile from is empty. AppDaemon does not recover from a logfile disappearing.

I'd like to be able to clear logs by just removing the logfile.

**Comment by acockburn** [comment]
AppDaemon has built in capabilities for log file rotation and self deletion of log files - please use those capabilities instead of manual deletion. Having said that I don’t know how appdaemon would handle an automatic rotation although I suspect it would be OK after a refresh …

**Comment by henning-meinhardt** [comment]
@acockburn I'm looking for a way to either "mark" a specific line in the existing logs or clean it up completely in order to know where to start reading. I'm aware of logfile rotation, but unless there is an API that allows me to explicitly trigger that operation I can't make use of it. I'd like to control when the log is cleared out. Is there an API not contained in the latest documentation?

**Comment by Justihar** [comment]
There are probably better ways to handle what you're trying to accomplish but one thing you might want to try is doing an echo "" > /path/to/existing/log/file. AD utilizes Python's built in logging module which takes advantage of various file and stream handlers. Removing the log file while all of that is loaded into memory as you've pointed out, definitely creates an issue.

A few alternatives would be to create a custom log file for your specific application or you can write some arbitrary thing to the log file so you know where to start looking forward like:

```self.log("------------------ START HERE ---------------------")```

**Comment by ReneTode** [comment]
or  self.log(" ")
50 times, so that the log in the AI looks empty.

**Comment by henning-meinhardt** [comment]
accepted ;-)
