### ISSUE TITLE
Start appdaemaon docker unable to lock database

### ISSUE THREAD

**Issue by HansMolenveld** [AppDaemon/appdaemon#1471]
I  running Appdaemon in docker on raspberry pi. The latest version (AppDaemon Version 4.2.1). The first logging i get the following:
ERROR: Unable to lock database: Permission denied
ERROR: Failed to open apk database: Permission denied
For the rest docker is running normally 
When I put a requirements file for additional packages in conf directory also these packages want install. I think it has to do with the 2 logs above.
Docker compose:
  appdaemon:
    container_name: appdaemon
    image: acockburn/appdaemon
    privileged: true
    hostname: appdaemon
    depends_on: 
       - homeassistant
    volumes:
       - /home/pi/Docker/appdaemon/conf:/conf
       - /etc/localtime:/etc/localtime
       - /home/pi/Docker/shared:/tmp
    ports:
      - 5050:5050
    environment:
      - TZ=Europe/Amsterdam
    user: 1000:1000
    restart: always    
    labels:
      - autoheal=true
      - "traefik.enable=true"
      - "traefik.docker.network=homeautomation_backend"
    networks:
      - backend

**Comment by contagon** [comment]
I believe it's because your container is running as a non root user, so can't install the required packages. Removing the user line in your docker compose will fix this, although may cause issues elsewhere.

**Comment by HansMolenveld** [comment]
Thank you that did the trick. I overlooked it.

Regards Hans

**Comment by graelo** [comment]
For the record, this message relates to the APK database (the container is based on alpine).

- for Docker users, @contagon gave the answer above.
- for podman users, you should unset the `--userns=...` argument in your `podman run` command so that the container's user is root. More info [here](https://www.redhat.com/en/blog/understanding-root-inside-and-outside-container)
