### ISSUE TITLE
Missed events with listen_event

### ISSUE THREAD

**Issue by Biotronic** [AppDaemon/appdaemon#1474]
Using a [Heatit Z-Push](https://heatit.com/product/9296/heatit-z-push-button-8-black) switch, I'm occasionally not getting callbacks for events (zwave_js_value_notification).

It seems to happen only with KeyHeldDown and KeyReleased events, but it's possible it happens with Keypressed as well (no matching event to check for, so testing is more tedious).

This happens with code as simple as this:
```
import hassapi as hass

class Lights(hass.Hass):
    def initialize(self):
        self.listen_event(self.zwave_event, "zwave_js_value_notification")

    def zwave_event(self, event_name, data, kwargs):
        self.log("zwave_event({}, {})".format(data, kwargs))
```

Happens on roughly 1 event in 20.

Running Home Assistant 2021.12.10,  AppDaemon 4 (0.8.1), on a Raspberry Pi 4

**Comment by ReneTode** [comment]
AD gets the events from HA in a stream, so to see if its AD or not you need to set up a simular check in HA to make sure that the events are actually send from HA to AD.

**Comment by Biotronic** [comment]
Oops, I forgot to mention: I made an automation to test it as well, and have been unable to recreate the issue there.

**Comment by ReneTode** [comment]
as far as i know its impossible that AD doesnt get events that HA does, unless there is a problem with the connection between AD and HA, which you would notice in your logs.

the easiest way to test and make sure is like this:

create an input boolean in HA
create an automation in HA that goes to on when the event is generated.

then change your test app to:
```
import hassapi as hass

class Lights(hass.Hass):
    def initialize(self):
        self.listen_event(self.zwave_event, "zwave_js_value_notification")
        self.listen_state(self.boolean_changed, "input_boolean.yours", new="on")

    def zwave_event(self, event_name, data, kwargs):
        self.log("zwave_event({}, {})".format(data, kwargs))

    def boolean_changed(self, entity, attribute, new, old, kwargs):
        self.log("zwave event changed the boolean")
        self.turn_off("input_boolean_yours")
```
when you use that you should see that you only get boolean_changed in the logs, when you also got the event announcement.

**Comment by ReneTode** [comment]
that could be by design.

keyHeldDown most likely keeps coming untill you release the button.
probably with a certain amount of time in between.

**Comment by Biotronic** [comment]
Nope, just the one KeyHeldDown, regardless of how long I hold it down - I have to calculate the exact duration if I want it (and that's why missing an event is so bad - if there was a sequence I could just step values for each event). Thanks for the help, though. :)
