### ISSUE TITLE
Instructions need to be updated

### ISSUE THREAD

**Issue by pebblebed-tech** [AppDaemon/appdaemon#1476]
Need add "--network="host"" to the initial docker [docker  instructions](https://appdaemon.readthedocs.io/en/latest/DOCKER_TUTORIAL.html) to get appdaemon to work if HA is running in docker as well. Otherwise it will not connect and you get the 5 second disconnect

**Comment by andreibursuc97** [comment]
Thank you for the info, saved me a lot of time because I could not figure out why appdaemon would not connect to home assistant

**Comment by acockburn** [comment]
Added to the docs
