### ISSUE TITLE
Error message in AppDaemon 

### ISSUE THREAD

**Issue by RGarrett93** [AppDaemon/appdaemon#1481]
Hi,

I am fairly new to AppDaemon but trying to get it to execute a simple py script that relies on a python package (Anki Vector SDK) that I have installed via configuration tab - I have also confirmed it is working: If I use Portainer to access the AppDaemon container after it has installed the package, I can run a simple py script (see below) via the console that sends Hello World to Vector.

```
import anki_vector


def main():
    args = anki_vector.util.parse_command_args()
    with anki_vector.Robot(args.serial) as robot:
        print("Say 'Hello World'...")
        robot.behavior.say_text("Hello World")


if __name__ == "__main__":
    main()
```

Now if I try to do the same via AppDaemon with a modified py script for when I fire an event called
```
VECTOR_EVENT
```
It will crash and go in a loop.

```
import appdaemon.plugins.hass.hassapi as hass
import anki_vector

class VectorWorld(hass.Hass):
  def initialize(self):
      self.listen_event(self.vector_event, "VECTOR_EVENT")
      
  
  def vector_event(self, event_name, data, kwargs):
      self.log("Vector SDK...")
      args = anki_vector.util.parse_command_args()
      with anki_vector.Robot(args.serial) as robot:
          robot.behavior.say_text("Hello World")
```

### This is an extract from the logs:
_2022-02-20 16:22:42.180979 INFO vector_test: Vector SDK..._
**_usage: appdaemon [-h] [-s [SERIAL]]_**
**_appdaemon: error: unrecognized arguments: -c /config/appdaemon -D INFO_**
_2022-02-20 16:22:42.714415 CRITICAL AppDaemon: Thread thread-0 has died_
_2022-02-20 16:22:42.721532 CRITICAL AppDaemon: Pinned apps were: ['vector_test']_
_2022-02-20 16:22:42.722532 CRITICAL AppDaemon: Thread will be restarted_

What does the above in bold mean?

**Comment by ReneTode** [comment]
```
args = anki_vector.util.parse_command_args()
```
this line most likely listens to arguments that you can give in the commandline, and that cant be used in appdaemon.

most likely you will need something like:
```
import appdaemon.plugins.hass.hassapi as hass
import anki_vector

class VectorWorld(hass.Hass):
  def initialize(self):
      self.listen_event(self.vector_event, "VECTOR_EVENT")
      
  
  def vector_event(self, event_name, data, kwargs):
      self.log("Vector SDK...")
      #args = anki_vector.util.parse_command_args()
      serial_number = "what you would have provided at the commandline"
      with anki_vector.Robot(serial_number) as robot:
          robot.behavior.say_text("Hello World")
```

**Comment by RGarrett93** [comment]
Thanks for getting back to me so quick, I will give that a go.

I found the command line arguments

util.py
```
def parse_command_args(parser: argparse.ArgumentParser = None):
    """
    Parses command line arguments.
    Attempts to read the robot serial number from the command line arguments. If no serial number
    is specified, we next attempt to read the robot serial number from environment variable ANKI_ROBOT_SERIAL.
    If ANKI_ROBOT_SERIAL is specified, the value will be used as the robot's serial number.
    .. code-block:: python
        import anki_vector
        import argparse
        parser = argparse.ArgumentParser()
        parser.add_argument("--new_param")
        args = anki_vector.util.parse_command_args(parser)
    :param parser: To add new command line arguments,
         pass an argparse parser with the new options
         already defined. Leave empty to use the defaults.
    """
    if parser is None:
        parser = argparse.ArgumentParser()
    parser.add_argument("-s", "--serial", nargs='?', default=os.environ.get('ANKI_ROBOT_SERIAL', None))
    return parser.parse_args()
```

**Comment by RGarrett93** [comment]
@ReneTode [ReneTode](https://github.com/ReneTode)

That worked great, I'm having a connection timeout issues remotely to Vector (needs waking up) but that's unrelated to AppDaemon.
Looks like, it should work though once I sort out the internal issue.

I am very grateful for your help - I will have fun writing some scripts to have Vector interact with my Home Automations.
