### ISSUE TITLE
listen_state: oneshot and timeout both try to cancel the handle

### ISSUE THREAD

**Issue by mementum** [AppDaemon/appdaemon#1486]
AppDaemon: `4.0.2`
If one uses both `oneshot=True` and `timeout=x`, if the event is called before the `timeout` expires, `oneshot` will cancel the handle.

When the `timeout` expires there will be a second attempt to cancel the handle. This is not service affecting, but it is reflected as a warning to the user in the `main log`

Ideally there should only be one cancellation attempt.

**Comment by Odianosen25** [comment]
Hello @mementum,

This is fixed in dev right now, so if in a hurry, can run the dev.

If you fine, can you kindly close pls?

Regards

**Comment by mementum** [comment]
Not in a hurry, just came across it when playing with a state listener that cancels a timer if an event is fired or get expired via the timeout.

Closing it!!!

Thanks
