### ISSUE TITLE
mqtt_subscribe is not working

### ISSUE THREAD

**Issue by bremor** [AppDaemon/appdaemon#1499]
Hi,

Long time user of AppDaemon, and love the framework and all the effort that has been put in.

I am having an issue using the mqtt_subscribe helper function on v4.2.1, it is giving the following error:
`appdaemon.exceptions.ServiceException: ('Unknown service (%s/%s/%s) in call_service from %s', 'default', 'mqtt', 'subscribe', 'somfy')`

My code looks like this:
```
import mqttapi as mqtt

class Somfy(mqtt.Mqtt):

    def initialize(self):

        self.adapi = self.get_ad_api()

        self.mqtt_subscribe("test/#")

```

I have tried using the alternative method and get a similar error:
`self.call_service("subscribe", topic = "somfy/#", namespace = "mqtt")`
gives the error
`ValueError: ('Invalid Service Name: %s', 'Subscribe')`

**Comment by bremor** [comment]
The alternate method works, I just had an error, it's just the helper method that doesn't work
`self.call_service("mqtt/subscribe", topic = "somfy/#", namespace = "mqtt")`

**Comment by Odianosen25** [comment]
Hello @bremor,

your code is fine, just state at the start you didn’t set the namespace for mqtt. So have something like 

`self.set_namespace(“mqtt”)`

**Comment by bremor** [comment]
Thanks @Odianosen25, that did the trick! I really appreciate the time to help. Thank you.
