### ISSUE TITLE
How to secure dashboard?

### ISSUE THREAD

**Issue by tiagodj** [AppDaemon/appdaemon#1503]
Hi, first I'd like to congrats for this amazing project! I finally can find a use for the devices I have laying around. :)

I created a little dashboard for my ipad, and one of the widgets is to unlock the door.

My concern is that anyone in my wifi network is able to access the dashboard and thus, unlock the doors. So a potential attack could be done even from outside the house since there's wifi coverage there.

I'd like to know if it is possible to restrict access to the dashboards.

For example, configure so that only specific mac addresses can access specific dashboards, or a token password that is added to the dashboard url query parameter.

Any security measure at this point would be welcome. :)

Thanks!

**Comment by Odianosen25** [comment]
Hello @tiagodj,

Dashboard only supports the use of simple passwords for now unfortunately, which usually once entered, that's the end.

I am assuming you want it for only certain aspects rights like the door lock?

What you could do is when the dashboard is opened and someone wants to open the door, create an app that only allows to control the door is the right code is entered; but such features should already be supported in some smart locks already.

Regards
