### ISSUE TITLE
App name not included in warning message when trying to compare str and int using lambda 

### ISSUE THREAD

**Issue by Aephir** [AppDaemon/appdaemon#1511]
I had an app with a listen_state:

```
self.listen_state(self.callback, "sensor.power_consumption", constrain_state=lambda x: x < 100)
```

where I had forgotten to convert the state to a float. I got this in the log:

```
2022-05-22 20:42:52.002306 WARNING AppDaemon: Could not evaluate state check due to '<' not supported between instances of 'str' and 'int'
```

But no indication of which App caused it. Solved (for me) on Discord ([here](https://discord.com/channels/334725674575200257/516637309118971928/978009397731155978)), but referencing the app in the logs would be very helpful.

**Comment by Odianosen25** [comment]
Fixed in dev
