### ISSUE TITLE
docker: Has anybody sent a picture via telegram?

### ISSUE THREAD

**Issue by dekiesel** [AppDaemon/appdaemon#1519]
I am running AD in one container and HA in another one.

Using matplotlib I created a graph that I'd like to send to myself via telegram.

I wrapped the graph in a `io.BytesIO`-object but HA doesn't like it:

```
2022-06-10 11:46:00 WARNING (SyncWorker_2) [homeassistant.components.telegram_bot] '<_io.BytesIO object at 0xb1c63d70>' are not secure to load data from!

```

I then considered writing the file to disk but as I said, two different containers.

My current idea is writing an AD-app that just connects to my bot, but I am not sure that's the best way to go.

If anybody has a better idea please let me know.

**Comment by dekiesel** [comment]
Hi @Odianosen25,

For the moment I mounted a named volume in both containers and use that to send data from one to the other. Works well.

HAs configuration.yaml lets you whitelist different folders so I didn't need to misuse www.

Would you share your implementation? I considered trying it myself but I have zero asyncio-knowledge. It'd be great to get the message-id back when sending a message without the extra hoops of catching the event.

**Comment by dekiesel** [comment]
Hi @Odianosen25 ,

I figured you'd use `python-telegram-bot` which just switched to asyncio, but nontheless thank you very much!

**Comment by dekiesel** [comment]
Hi @Odianosen25 ,

I meant your custom implementation of a telegram bot in appdaemon, I thought that's what you meant you had done, did I misunderstand you?

**Comment by Odianosen25** [comment]
Hello @dekiesel,

Yes I have a custom implementation in AD of a Telegram Bot, at the same I had initially done what you were just trying to do with HA.
