### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by DaveDixon** [AppDaemon/appdaemon#1521]
On this page 
  https://github.com/AppDaemon/appdaemon/blob/aaabc65ca62b9f7c09a6fa42029ec20648a825aa/docs/DASHBOARD_INSTALL.rst
There is a broken link "AppDaemon Installation Documentation".
At the bottom there is also a broken link to "External Commands".

On this page
  https://github.com/home-assistant/hadashboard
There is a broken link to the "HADashboard page" on the Home Assistant Website.
The last three links on the page are also broken.

**Comment by acockburn** [comment]
Hi there- these docs are intended to be read after processing on readthedocs - the links work correctly when they are deployed there.
