### ISSUE TITLE
Split apps.yaml

### ISSUE THREAD

**Issue by alsig** [AppDaemon/appdaemon#1546]
Hi,

My apps.yaml is getting rather large, partly because I have many apps and partly because I use a lot of arguments for my apps. I would like to split it into multiple yaml files, is this possible?

Best Regards
/Jens

**Comment by Justihar** [comment]
You can break up your apps into separate YAML files. As long as the YAML files are within the apps directory, AD will recursively search through the apps directory for those files. Here is a link from the docs with some information on that: https://appdaemon.readthedocs.io/en/dev/APPGUIDE.html#configuration-of-apps

**Comment by alsig** [comment]
Sorry for my delayed response.

Thanks for your response, it worked perfectly, thanks
