### ISSUE TITLE
app_config not getting the newest value

### ISSUE THREAD

**Issue by ihaettypo** [AppDaemon/appdaemon#1554]
So in one app, I listen to the log and when any app added/changed/deleted log message detected I try to get the updated self.app_config, but it seems the list returned were from before the app added/changed/deleted event happened.

For example, at first the self.app_config was:
{
app_a: { ...},
app_b: {...}
}

After changed the name of app_b to app_c, the log sent a message "app_b changed". Inside the callback function which listens to this message, I tried to fetch the self.app_config again, the list it returned was still:
{
app_a: { ...},
app_b: {...}
}

Not:
{
app_a: { ...},
app_c: {...}
}
as it supposed to be.

Maybe this is a thread thing? How can I get the newest configs then?

**Comment by acockburn** [comment]
What do you want to achieve? self.app_config is intended to be an internal variable, but as you say it may be a race condition/threading issue.
