### ISSUE TITLE
Keep fa and mdi icons up-to-par with HA

### ISSUE THREAD

**Issue by JoostAB** [AppDaemon/appdaemon#1562]
By default I would like to use the `use_hass_icon` directive for all my widgets for consistency. But sometimes I have an icon related to an entity that does not exist in AD because of the version used in AD. For example the mdi:fan-auto icon. The AD widget stays blank in such a case.
I must then either change the icon in HA to an older (less desirable) one, or use a different one in AD.

**Comment by acockburn** [comment]
I need to look into an automated way to do this ... closing this particular issue, but noted.
