### ISSUE TITLE
This is the best project ever.

### ISSUE THREAD

**Issue by jlpouffier** [AppDaemon/appdaemon#1573]
_This is not an issue, please safely close it once you read it._

You guys are awesome.
AppDeamon is a love letter to home automation, and its interactions with home Assistant are amazing.

The first app that I created took me some time just to get used to this new way or writing automations, but from this point, it was impossible to go back to what HA propose natively.

A few years ago, here I am, 100% of the "logic" of my home assistant instance is handled my AppDeamon, I enjoy so much writing these apps.... so much more than YAML-based automations.

Thx guys ! A lot.

(My [apps](https://github.com/jlpouffier/home-assistant-config/tree/master/appdaemon/apps), in case you are interested)

**Comment by acockburn** [comment]
Thanks for your kind words - we really appreciate it!

**Comment by rockkoca** [comment]
It's a really nice project!!!
