### ISSUE TITLE
modes 

### ISSUE THREAD

**Issue by getawaymen1979** [AppDaemon/appdaemon#1574]
Hey,
I cant use bolow codes,Also how can I do this "input_select.house_mode"
Thanks

morning:
  widget_type: mode
  icon_on: fa-clock-o
  icon_off: fa-clock-o
  title: Morning
  entity: input_select.house_mode
  mode: Morning
  script: script.morning

day:
  widget_type: mode
  title: Day
  icon_on: fa-sun-o
  icon_off: fa-sun-o
  entity: input_select.house_mode
  mode: Day
  script: script.day

evening:
  widget_type: mode
  title: Evening
  icon_on: fa-moon-o
  icon_off: fa-moon-o
  entity: input_select.house_mode
  mode: Evening
  script: script.evening

night:
  widget_type: mode
  title: Night
  icon_on: fa-star-o
  icon_off: fa-star-o
  entity: input_select.house_mode
  mode: Night
  script: script.night

**Comment by acockburn** [comment]
I'm sorry, I don't understand what you are asking 0 what is the problem, what insult working, what errors are you getting? Also, please post your config file using code blacks so we can check the formatting.
