### ISSUE TITLE
[Suggestion] - Better logs when using variable names already assigned

### ISSUE THREAD

**Issue by Aephir** [AppDaemon/appdaemon#1580]
I've tried this a few times now, some where feel pretty dumb about it (in a sleep-deprived instance, naming a function `set_state`, and wondering why the internal `set_state` wasn't working), others where I would have to have dug quite deep to have any idea about it (thanks Home Assistant community!).

Is it not possible to have the logs state things like this? That you're using an assigned variable name?

**Comment by acockburn** [comment]
That's a difficult one - I think the real answer is better IDE support which I will look into. Overriding is a common python technique so I shouldn't really be policing it in AD.
