### ISSUE TITLE
Allow setting a unique ID

### ISSUE THREAD

**Issue by wernight** [AppDaemon/appdaemon#1599]
Entities in Home Assistant [must have a unique ID](https://www.home-assistant.io/faq/unique_id) (usually called `unique_id` in HA Yaml config). This is necessary to customise for example the name of the entity. However using `set_state()` there seems to be no way to set that. Setting `unique_id` as an attribute doesn't work.

Same rest done before by someone else: https://community.home-assistant.io/t/can-you-give-an-entity-created-by-set-state-in-appdaemon-an-unique-id/485513

**Comment by acockburn** [comment]
The ID of an entity is setup outside the scope of its state. We are using MQTT discovery as the post says to work around this. We can help you with details in our discord channel.

**Comment by wernight** [comment]
The issue is that entities created from AppDaemon are reported by HA as not having a `unique_id` so I cannot customiz them in HA using the UI.

**Comment by acockburn** [comment]
Agreed, but if you use MQTT discovery, as suggested, to create the entities you can create a unique ID. However, using MQTT discovery you can also do all of the customization programmatically in AD without needing to manually edit the UI. This is the recommended way to create entities in AD.
