### ISSUE TITLE
Listening for mqtt wildcard topics doesn't work

### ISSUE THREAD

**Issue by foxy82** [AppDaemon/appdaemon#1601]
I'm trying to listen to an MQTT wildcard topic but nothing I do seems to work:

The docs suggest the last one should work: https://appdaemon.readthedocs.io/en/latest/MQTT_API_REFERENCE.html#appdaemon.plugins.mqtt.mqttapi.Mqtt.listen_event

```
self.mqtt = await self.get_plugin_api("MQTT")
# Single topic works:
self.mqtt.listen_event(self.mqtt_event, "MQTT_MESSAGE", topic="frigate/stats")

# Doesn't work
self.mqtt.listen_event(self.mqtt_event, "MQTT_MESSAGE", wildcard="frigate", namespace='mqtt')
# Doesn't work
self.mqtt.listen_event(self.mqtt_event, "MQTT_MESSAGE", wildcard="frigate/#", namespace='mqtt')
```

**Comment by Odianosen25** [comment]
@foxy82,

can you remove the namespace from the 3rd example given and see if it works?

**Comment by Odianosen25** [comment]
Hello @foxy82,

Any updates on this? As for me it works just fine so not sure what’s happening with yours?

**Comment by foxy82** [comment]
Hey - still not working for me.

**Comment by bbrendon** [comment]
Also, if you could explain how to subscribe to wildcards, that would be useful as well :)

**Comment by acockburn** [comment]
Just pushed a potential fix to Dev - could you try it please?
