### ISSUE TITLE
apps.yaml - arguments truncated

### ISSUE THREAD

**Issue by madchap** [AppDaemon/appdaemon#1603]
Hi,

I have a weird issue with `apps.yaml` and the app's argument.

For example:
```
my_app:
  my_test_number: 12345678.000
```

When the app runs, the value from `self.args[my_test_number]` will be `12345678.0` and not the one specified. I tried various ways to still get it raw, but could not figure it out.

NB: The `my_test_number` could also be passed through a hassio secret, the problem is the same.

Thanks for your help and the unbelievable quality of the product! (both HA and AppDaemons!)

**Comment by Odianosen25** [comment]
@madchap ,

yeah it’s a yaml issue and not AD in particular. To get it all, so put in the number as string; that is close them using quotation “”.

**Comment by madchap** [comment]
Indeed.. that's what happens when you change the wrong file when trying out alternatives :-D Thanks @Odianosen25.
