### ISSUE TITLE
Docker container exited with code 0 

### ISSUE THREAD

**Issue by fachu-09** [AppDaemon/appdaemon#1607]
When i run this command to start appdaemon i got this output and the container exit with code 0:

`docker run --name=appdaemon --rm -it acockburn/appdaemon:latest --env-file /home/ubuntu/home-assistant/.env -v /etc/localtime:/etc/localtime:ro -d -v /home/ubuntu/sata/appdaemon/:/conf`

Output:

fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/aarch64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/aarch64/APKINDEX.tar.gz
OK: 894 MiB in 69 packages
appdaemon 4.2.1

**Comment by acockburn** [comment]
Please re-run with the latest image and the exact instructions here:

https://appdaemon.readthedocs.io/en/latest/DOCKER_TUTORIAL.html#testing-your-system
