### ISSUE TITLE
The image is running under root account

### ISSUE THREAD

**Issue by PavelD** [AppDaemon/appdaemon#1608]
Hello,

I was solving issue with ownership on mounted drives and it ends with running container as non-privileged user.
As the image was failing when i set user externally I did following tiny extension of your docker image.

```FROM acockburn/appdaemon:latest

RUN adduser  -u 1000 appdaemon -D && addgroup appdaemon wheel && \
    apk add sudo && echo "%wheel ALL=(ALL:ALL) NOPASSWD: ALL" > /etc/sudoers.d/wheel && chmod 0440 /etc/sudoers.d/wheel && \
    sed -i -e "s/apk add/sudo apk add/g" /usr/src/app/dockerStart.sh

USER appdaemon
```

I hope it will be interesting for you and other users as well.

Current solution has a few limitations:
* Update of `dockerStart.sh` is done directly in the Dockerfile as I did just extension of existing image
* UserId / groupId is hardcoded and if someone will run it with own id's it will fail as home is not writable for others
* Allowing full access via sudo with no password is not adding any extra security - it can be easily limited.

Is it something you want to have in your image?

**Comment by acockburn** [comment]
Hi there - this would be good as a PR, but please note hat we have made significant changes to the docker image over the last few days.
