### ISSUE TITLE
Appdaemon causes Client exceeded max pending messages at HA restart

### ISSUE THREAD

**Issue by vaibhav2912** [AppDaemon/appdaemon#1614]
Hello,

I noticed that Appdaemon add-on causes this message to show up when home assistant restarts.

> Logger: homeassistant.components.websocket_api.http.connection
> Source: components/websocket_api/http.py:132
> Integration: Home Assistant WebSocket API (documentation, issues)
> First occurred: 9:15:22 PM (8 occurrences)
> Last logged: 9:15:22 PM
> 
> [140476941476304] Client exceeded max pending messages [2]: 2048

It only occurs once at the restart.
I also noticed that HA restart takes longer with Appdaemon enabled vs disabled.

When Appdaemon add-on is disabled, this error doesn't occur.

I tried asking this on the forum but couldn't get any answers. So posting here.

Has anyone seen this and know how to fix this?

Regards,
Vaibhav

**Comment by vaibhav2912** [comment]
This is the latest error on HA startup

> Logger: homeassistant.components.websocket_api.http.connection
> Source: components/websocket_api/http.py:157
> Integration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
> First occurred: 12:18:36 AM (1 occurrences)
> Last logged: 12:18:36 AM
> 
> [140449756601824] Client unable to keep up with pending messages. Stayed over 512 for 5 seconds. The system's load is too high or an integration is misbehaving

**Comment by acockburn** [comment]
This doesn't happen outside of the mass add-on that I am aware of. We are looking into a new bass plugin that will be more efficient and may help with this.
