### ISSUE TITLE
Unable to build opencv-python

### ISSUE THREAD

**Issue by ianustec** [AppDaemon/appdaemon#1620]
Hi,
thank you for the project.

We are trying to dev a script that using opencv (cv2) to process an image from HA camera.

The packages we are instating are: imutils - opencv-python - numpy
but the build of opencv fails.
We tried adding ninja as pip package and not works. We tried also as system package ninja-build and not works too.

The board we use is an RPI 4.

The following last part of logs. 

Thanks in advance
 

`[.....]

 Building wheels for collected packages: opencv-python
 Building wheel for opencv-python (pyproject.toml): started
 Building wheel for opencv-python (pyproject.toml): finished with status 'error'
 error: subprocess-exited-with-error
  
 × Building wheel for opencv-python (pyproject.toml) did not run successfully.

 │ exit code: 1
  ╰─> [66 lines of output]

      --------------------------------------------------------------------------------
      -- Trying "Ninja" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-bgp_q11y/opencv-python_0972cb86407441d9be1a3ace2f87c710/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Ninja" generator - failure
      --------------------------------------------------------------------------------
      
      
      
      --------------------------------------------------------------------------------
      -- Trying "Unix Makefiles" generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
      -- Configuring incomplete, errors occurred!
      See also "/tmp/pip-install-bgp_q11y/opencv-python_0972cb86407441d9be1a3ace2f87c710/_cmake_test_compile/build/CMakeFiles/CMakeOutput.log".
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying "Unix Makefiles" generator - failure
      --------------------------------------------------------------------------------
      
      ********************************************************************************
      scikit-build could not get a working generator for your system. Aborting build.
      
      Building Linux wheels for Python 3.10 requires a compiler (e.g gcc).
      But scikit-build does *NOT* know how to install it on alpine
      
      To build compliant wheels, consider using the manylinux system described in PEP-513.
      Get it with "dockcross/manylinux-x64" docker image:
      
        https://github.com/dockcross/dockcross#readme
      
      For more details, please refer to scikit-build documentation:
      
        http://scikit-build.readthedocs.io/en/latest/generators.html#linux
      
      ********************************************************************************
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
Failed to build opencv-python
  ERROR: Failed building wheel for opencv-python
ERROR: Could not build wheels for opencv-python, which is required to install pyproject.toml-based projects
[10:16:52] FATAL: [31mFailed installing package opencv-python[0m
s6-rc: warning: unable to start service init-appdaemon: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
prog: fatal: stopping the container.
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
`

**Comment by mion00** [comment]
I think in the log the following lines can help you:
```
  Building Linux wheels for Python 3.10 requires a compiler (e.g gcc).
  But scikit-build does *NOT* know how to install it on alpine
  
  To build compliant wheels, consider using the manylinux system described in PEP-513.
  Get it with "dockcross/manylinux-x64" docker image:
```

There needs to be `gcc` installed as a system package (using the `apk` package manager of Alpine, since it seems that open-cv need to build the native C extensions.
I would like to help if possible but I need some more information about you setup.
How are you running AppDaemon? As a Python package inside a venv or with Docker?

**Comment by ianustec** [comment]
> I think in the log the following lines can help you:
> 
> ```
>   Building Linux wheels for Python 3.10 requires a compiler (e.g gcc).
>   But scikit-build does *NOT* know how to install it on alpine
>   
>   To build compliant wheels, consider using the manylinux system described in PEP-513.
>   Get it with "dockcross/manylinux-x64" docker image:
> ```
> 
> There needs to be `gcc` installed as a system package (using the `apk` package manager of Alpine, since it seems that open-cv need to build the native C extensions. I would like to help if possible but I need some more information about you setup. How are you running AppDaemon? As a Python package inside a venv or with Docker?

Hi, AppDaemon is running as Add-On in Home Assistant
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.5  (aarch64 / raspberrypi4-64)
 Home Assistant Core: 2023.2.5
 Home Assistant Supervisor: 2023.01.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
```

**Comment by acockburn** [comment]
Just to add that the AppDaemon add-on uses a custom docker image that we have no input to, so we can't really assist by any changes on the APpDaemon side.

**Comment by LeoI5** [comment]
I use opencv with simple config of add-on:
system_packages:
  - py3-opencv
