### ISSUE TITLE
Switched from rasp pi to N2+ and Appdaemon WON'T START

### ISSUE THREAD

**Issue by aparker21** [AppDaemon/appdaemon#1634]
I changed over from a Raspberry Pi to an Odroid N2+.  I had to import every backup I ever created in order for everything to function correctly.  I have gotten almost everything up and running correctly except for appdaemon.  I am having trouble getting my appdeamon to Start.  The IP address of the new machine did change so I adjusted that in the appdaemon.yaml file.  My long-live token is still the same.  Does anyone have any idea how to fix this?  Do I need to create a new token?  Do I need to uninstall Appdaemon and reinstall??  I would like to fix this withouth reassigning a token or reinstalling the app, but if that is the only fix I certainly will.

**Comment by acockburn** [comment]
We would know more if you posted a log so we can see what is causing AD not to start.

**Comment by aparker21** [comment]
This is the AppDaemon log:

s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: AppDaemon
 Python Apps and Dashboard using AppDaemon 4.x for Home Assistant
-----------------------------------------------------------
 Add-on version: 0.11.0
 You are running the latest version of this add-on.
 System: Home Assistant OS 9.4  (aarch64 / odroid-n2)
 Home Assistant Core: 2023.1.7
 Home Assistant Supervisor: 2022.12.1
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-appdaemon: starting
s6-rc: info: service init-appdaemon successfully started
s6-rc: info: service appdaemon: starting
s6-rc: info: service appdaemon successfully started
s6-rc: info: service legacy-services: starting
s6-rc: info: service legacy-services successfully started
[12:49:00] INFO: Starting AppDaemon...

**Comment by aparker21** [comment]
The log does not change if I click Start again.  It has said 12:49:00 for the last 3 hours

**Comment by aparker21** [comment]
The appdaemon.log shows this:  2023-01-24 14:32:36.949343 WARNING HASS: Disconneceted from Home Assistant, retrying in 5 seconds.

There is nothing in the error.log

**Comment by acockburn** [comment]
OK, you need to enable DEBUG in AppDaemon - that will give you a stack trace and reason for disconnecting. I don't use the HASS add-on however so I am not sure how to do that. The flag you need to pass to AD is `-D DEBUG`

**Comment by aparker21** [comment]
I fixed the issue.  I saw a thread on Discord about rebooting the entire system.  I tried it and it worked!!
