### ISSUE TITLE
Debugging in vscode

### ISSUE THREAD

**Issue by djo4ever** [AppDaemon/appdaemon#1635]
Hello,
Is there a way debugging is possible in vscode?
breakpoints, watch variables etc?

**Comment by djo4ever** [comment]
I was able to get it working.

For people that want to acomplish the same thing:
1) install 'remote - ssh' extension
2) Configure extension with the host you want to connect to.
3) create launch.json with the following conten (adjust accordenly)


`{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Appdeamon: Debug Current File",
            "type": "python",
            "request": "launch",
            "module": "appdaemon",
            "args": [
                "-c",
                "/mnt/hass/appdaemon",
                "-D",
                "INFO"
            ],
            "console": "integratedTerminal",
            "stopOnEntry": true,
            "justMyCode": false
        },
    ]
}`

**Comment by julianbraun** [comment]
@djo4ever thank you for your instruction.

I just have a question with point 5.
Where do I have to create the launch.json file?

**Comment by poggenpower** [comment]
Regarding the launch.json this should be in your workspace root. vscode will also ask you to create it if you start the debugger or if you enter the debug workbench you have a button to create one - if not exists. 
Start with a simple debugging tutorial from you tube or so and then adopt this to appdaemon, this should give you the background to use it efficient. 
At the end adddaemon debugging is standard python debugging. The main trick is `"justMyCode": false` to get into all codeparts, that are imported as packages.
