### ISSUE TITLE
terminate() not called when docker container is stopped/restarted

### ISSUE THREAD

**Issue by dekiesel** [AppDaemon/appdaemon#1636]
I am not sure whether this is a bug or a feature request, but I'd be really happy if `terminate()` was called when the container stops/restarts, if that is possible.

Consider an app terminatecalled_app:

Yaml:
```
terminatecalled_app:
  module: terminate_called
  class: TerminateCalled
```

py:

```
import hassapi as hass
import globals

class TerminateCalled(hass.Hass):
    def initialize(self):
        self.log("initialized")

    def terminate(self):
        self.log("terminate called")
```

When this app is reloaded by AD `terminate(self)` is called as it should:

`2023-01-26 10:33:02.604607 INFO terminatecalled_app: terminate called`

But when the docker container AD runs in is stopped/restarted `terminate(self)` isn't called.

It'd be great if that feature could be added because I need to write data to disk when the container is restarted.

**Comment by dekiesel** [comment]
It seems [docker stop](https://docs.docker.com/engine/reference/commandline/stop/) sends SIGTERM first, so in Theory it should be possible.

**Comment by acockburn** [comment]
AppDaemon already responds correctly to a SIGTERM with an orderly shutdown including terminating apps and correctly calling the `terminate()` function. It could be that Docker is getting impatient and sending s SIGKILL before AD has finished - a log file of the shutdown should help figure out if that id the case.

**Comment by dekiesel** [comment]
Thanks for the answer. You are right:

```
Jan 26 10:26:12 raspberrypi dockerd[867]: time="2023-01-26T10:26:12.789457380+01:00" level=info msg="ignoring event" container=c57273337cbdb84bc1ec00329c2cc138c14359b6b134ab67b82d9f1736d064cf module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
Jan 26 10:33:53 raspberrypi dockerd[867]: time="2023-01-26T10:33:53.433980252+01:00" level=info msg="Container failed to exit within 10s of signal 15 - using the force" container=d7544257a915c984b7b30d307598104e5eb2c85a215929515e44ab7cc11a8616
Jan 26 10:33:53 raspberrypi dockerd[867]: time="2023-01-26T10:33:53.540131001+01:00" level=info msg="ignoring event" container=d7544257a915c984b7b30d307598104e5eb2c85a215929515e44ab7cc11a8616 module=libcontainerd namespace=moby topic=/tasks/delete type="*events.TaskDelete"
```

Which is weird since it doesn't even take close to 10sec for the container to come down... I'll play around with the timeout option, unless you have a better idea?

**Comment by dekiesel** [comment]
Changing the timeout to 30s worked (at least during last nights reboot).

For everybody stumbling onto this issue later (or me in the future): I added this to the container-config in my stacks `docker-compose.yaml`:

`stop_grace_period: "30s"`
