### ISSUE TITLE
State of the Project: Releases for the small things

### ISSUE THREAD

**Issue by markusressel** [AppDaemon/appdaemon#1646]
Hi there,

first of all, this is a really awesome project. It keeps my wife and me very happy in our little apartment home.

I know that maintaining projects like this is really hard. I try to do it myself and it just keeps getting harder every year. Splitting personal free time between projects like this, family, friends and hobbies is always a tough choice, and money (github f.ex. sponsoring) doesn't make it any easier.

Having said that, I would really like to see an update for appdaemon, since the last release is over a year old by now. Some small release for some basic dependency updates and python version migrations would already be great, just to see that the project isn't dead. I (and probably others as well) don't really need a ton of new features, just stability improvements, bugfixes and the like. Having to abandon appdaemon simply because it is getting too old would be a real shame. Afaik there isn't really an alternatives to it, and migrating to Home Assistant YAML files or the GUI... well it would suck. :sweat_smile: 

I have seen that there were some commits during the past year, so I assume its not dead, just on a very tight time-budget. I can understand that, and I would also like to help out with some small things if possible and/or necessary. I have to admit though, that I already am struggling to keep my projects alive and well too, so don't expect any wonders :smile: . While I know its not easy to find honest and hard working people to collaborate on a project like this, it could really help splitting the load, like it does for Home Assistant itself.

Thx for reading :heart:

**Comment by acockburn** [comment]
Thanks for your concern – I can assure you that AD is alive and well and not going anywhere, not least because I recently moved into a new house and I am automating like crazy. Time is always an issue, I have a much more demanding job than when I started AD, and I’m spending a lot of time actually using it instead of developing it. Having said that, I am working towards a release soon – merging PRs for updates, I added a fix to the scheduler last weekend, so watch this space. In the meantime, we have a small but reasonably active Discord server here

https://discord.gg/q3P3qVkE

Drop in for a chat and to share experiences, there are usually few people around.

**Comment by markusressel** [comment]
Well, you still using your own project is great to hear! 😄 
I will make sure to check out the discord.

I want to emphasize tough that my main point is still the release cycle. I think if making releases was easy (not sure how easy it is currently), and release notes would actually be part of the github release page (there are bots for this), or at least a link to the documentation, I think it would make the project appear much more alive and probably attract a lot of users that might be scared away by old releases and "unpolished" update notes. Even I was starting to get worried even though the currently latest release works pretty darn well on a daily basis.

Thx for the quick response! ❤️

**Comment by acockburn** [comment]
We have a release going out later today, and I have added some verbiage explains the slow release cycle to the docs as well as pointing folks to the discord server. IF you could point me into the right direction for your suggestion of updating notes on the discord page via bots I'll take a look at that too.

**Comment by markusressel** [comment]
I have seen that on discord, very exciting! I really appreciate you giving this a second though :rocket: 

While posting release notes using a bot is a great idea, imho it should not be required to join the discord server to see release notes. I am not really a discord user and only use it for projects like this to stop by in really rare cases. Not because I don't care, but because GitHub (or Gitlab or whatever else) is usually enough for me to have a meaningful discussion that can also be seen by anyone else lateron, which can be great for documenting things. So I cannot really give advice on bot usage for discord.

However, since you are hosting this project on GitHub, I would suggest to look into using [Release Drafter](https://github.com/release-drafter/release-drafter). I use it for all of my projects, and while it doesn't provide the most detailed release notes, it at least gives a reasonable summary of all of the things that happened (given that PR titles are maintained well) and makes release notes look aright with pretty much 0 effort.

**Comment by acockburn** [comment]
Thanks – I wasn’t suggesting discord as a venue for this I agree that it isn’t the nest place, but your pointer to release drafter is appreciated and I’ll look into it!

**Comment by acockburn** [comment]
Just to clarify - I misspoke in my previous comment when I said Discord - I meant GitHub, so thanks for the info!

**Comment by acockburn** [comment]
Closing this for now - but we are taking your suggestions on board.
