### ISSUE TITLE
Missing documentation (latest)

### ISSUE THREAD

**Issue by angvoreeth** [AppDaemon/appdaemon#1648]
When accessing the documentation, there are missing paragraphs. See below.

The workaround is to choose another release version.

URL : [https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html](url)

**Missing paragraphs:**

<img width="1096" alt="image" src="https://user-images.githubusercontent.com/88553661/220143049-366fce70-08cd-4b35-b090-4c5f608a7b17.png">

**Comment by acockburn** [comment]
Thanks for the heads up - this should be fixed now.
