### ISSUE TITLE
Improve packaging system

### ISSUE THREAD

**Issue by mion00** [AppDaemon/appdaemon#1657]
The `requirements.txt` file is used in a bit confusing way. It it usual practice for this file to contain all the dependencies present in the project virtualenv, created using `pip freeze > requirements.txt`, so that the virtualenv can be easily re-created by any developer locally using `pip install -r requirements.txt.`
But this file is also used as the `install_requires` inside `setup.py`, creating a bit of a conflict.
If one installs the appdaemon locally with `pip install .`, then run `pip freeze > requirements.txt`, the `requirements.txt` file is modified, since all the transitive dependencies are also loaded, as is expected. So the question is: shouldn't the declaration of the project dependencies be moved in a more appropriate place, separate from `requirements.txt`?

## Proposed solution
I propose to more crealry declare the project dependencies, by upgrading the way we use the Python packaging system.
At the moment the package is created from the `setup.py`, read by `setuptools` when building the package.
The way to package applications has changed a lot over the years. Nowadays if one were to follow the official [Python packaging guide](https://packaging.python.org/en/latest/tutorials/packaging-projects/), the recommended setup is to use a `pyproject.toml` to describe all the metadata of the project, including the build tool and the project dependencies.
I suggest we move from the current `setup.py` to a more modern and "standard" solution, by migrating to a `pyproject.toml` file to contain all the project dependencies.

**Comment by acockburn** [comment]
I'm happy to move in this direction - will this also work with dependabot, and what changes will be required for my PyPi build process? (if any) - I currently just run setup.py the run twine to upload, I presume this will continue to work but setup.py may require some changes?

**Comment by acockburn** [comment]
Carlo, just as a placeholder, I recently had to split out dependencies for makethedocs because it choked on the standard requirements.txt, something to do with Jinja. It now has its own requirements.txt file, which is effectively orphaned from the actual projects requirements. This was true before your changes. Any thoughts on how to address this in a better way? Or do we just manually update it from time to time?

**Comment by mion00** [comment]
Sorry do you mean `readthedocs`?

**Comment by acockburn** [comment]
Oops, yes, sorry

**Comment by mion00** [comment]
OK I have seen that `requirements` file, let's see if #1664 helps.

**Comment by acockburn** [comment]
Just merged it - I'll check the RTD build and let you know

**Comment by acockburn** [comment]
<img width="830" alt="image" src="https://user-images.githubusercontent.com/9850788/221959932-11a5da2e-0647-4eaa-b9f2-ba78749ff0a5.png">

**Comment by acockburn** [comment]
Looking good :)

**Comment by acockburn** [comment]
I'd like to add Python 3.11 to the coverage - now we have a proper system in place I know how to do it, and I'll try updating RTD to use 3.11 too. Let me know if you have any objections

**Comment by mion00** [comment]
Well, I don't have any. Feel free to experiment. You know, if something breaks the fix is just a `git revert` away! :smirk:

**Comment by acockburn** [comment]
Thanks - this is looking really good :)

**Comment by acockburn** [comment]
It worked!

A couple of warnings though:

<img width="830" alt="image" src="https://user-images.githubusercontent.com/9850788/221962989-ecacaa38-920d-46dc-9b22-f223abe0f90e.png">

**Comment by acockburn** [comment]
Reckon I can fix this one too ...

**Comment by acockburn** [comment]
Hmm, maybe not - those 2 directives don't seem to be anywhere in the AD repository so not sure how they are being picked up.

**Comment by mion00** [comment]
The Github pipeline executes the instructions defined in the `steps` directive. Each step defines a Github Action (the `uses` field points to the Github repo containing the action that is downloaded and executed as part of the pipeline)
These warnings are generated by the Action themselves, the only way we can fix them is notify the Github repo that is the author of the action, so that they release a new version with the fix that we can then use here.

**Comment by acockburn** [comment]
Ahh, got it, so these are likely issues in the Black or Flake8 repositories then.

**Comment by mion00** [comment]
> Ahh, got it, so these are likely issues in the Black or Flake8 repositories then.

It seems to stem from the `actions/setup-python` step: https://github.com/AppDaemon/appdaemon/actions/runs/4296807613/jobs/7488985591#step:3:8

We are using version 3 of that action, while I see the latest is 4. Maybe they already fixed that warning in the new release.

**Comment by acockburn** [comment]
That fixed it so I think we are done here!
