### ISSUE TITLE
Dev: unused azure dependencies?

### ISSUE THREAD

**Issue by mion00** [AppDaemon/appdaemon#1659]
The following dependencies are listed inside the `requirements.txt`:
https://github.com/AppDaemon/appdaemon/blob/5ed6da4dd8b84a4274e63b0420c5e05eabbd6de1/requirements.txt#L21-L25

But inside the appdaemon src code there is no mention of any import of this modules. Thus are they really required or can they be eliminated?

**Comment by acockburn** [comment]
These were added when we implemented the Azure pipeline, They are not required for AppDaemon but I assume the Azure CI requires them?

**Comment by mion00** [comment]
The Azure CI pipeline "simply" executes the commands we have told it to do:
https://github.com/AppDaemon/appdaemon/blob/7b03124d70ade5882ee81a7cc773695a70baf741/azure-pipelines.yml#L20-L29

At the moment the `requirements.txt` is used to install the Python modules that Appdaemon uses (line 22), and since these specific azure modules are not used a part of Appdaemon source code, I sees no reason to include them.

**Comment by acockburn** [comment]
OK, I’ll remove them and see if it breaks 😉

**Comment by acockburn** [comment]
Build completed OK in Azure so I think we're good on this one,
