### ISSUE TITLE
Rows of cameras break the layout.

### ISSUE THREAD

**Issue by ruffle-b** [AppDaemon/appdaemon#1737]
### What happened?

If I have multiple rows of cameras in a layout the grid gets very confused. This should simply be two rows of two cameras.

![shot1](https://user-images.githubusercontent.com/10534491/229185905-1e663e48-53da-408e-b219-1e19bd9d0130.png)

Looking at the HTML, the grid positions being generated are wrong.

![shot2](https://user-images.githubusercontent.com/10534491/229186199-dbd18dbc-3947-4719-ae94-55af806acffe.png)

If I manually change the data-col and data-row for the second and third camera widgets then it works.

![shot3](https://user-images.githubusercontent.com/10534491/229186628-6a5acd3e-bbbe-480a-9249-abeca1d31959.png)

![shot4](https://user-images.githubusercontent.com/10534491/229186729-3f9c4189-18fd-44fc-a8a6-d9f97dd96006.png)

### Version

4.2.3

### Installation type

Docker container

### Relevant log output

```sh
N/A
```

### Relevant code in the app or config file that caused the issue

```sh
Here's my .dash file:

##
## All Cameras Dash
##

title: All Camera Panel
widget_dimensions: [87, 87]
widget_size: [1, 1]
widget_margins: [2, 2]
columns: 8

reception_camera:
  widget_type: camera
  title: ""
  entity: camera.reception
  base_url: http://10.1.1.208:8123
  stream: "on"
patio_camera:
  widget_type: camera
  title: ""
  entity: camera.patio
  base_url: http://10.1.1.208:8123
  stream: "on"
officedoor_camera:
  widget_type: camera
  title: ""
  entity: camera.officedoor
  base_url: http://10.1.1.208:8123
  stream: "on"
officegate_camera:
  widget_type: camera
  title: ""
  entity: camera.officegate
  base_url: http://10.1.1.208:8123
  stream: "on"

layout:
  - patio_camera (4x2), officedoor_camera (4x2)
  - officegate_camera (4x2), reception_camera (4x2)
```

**Comment by acockburn** [comment]
This is a known quirk with the dashboard/exoected behavior. When you are spanning multiple lines, (in this case 2 at a time because of the 2 in 4x2) you need to add a spacer in the layout like this:

```
layout:
  - patio_camera (4x2), officedoor_camera (4x2)
  - spacer (8x2)
  - officegate_camera (4x2), reception_camera (4x2)
```

I tested this layout and it works as expected.

**Comment by acockburn** [comment]
Closing for now - please re-open or comment if you have further issues.
