### ISSUE TITLE
Unable to call_service knx/send

### ISSUE THREAD

**Issue by BoxedBrain** [AppDaemon/appdaemon#1754]
### What happened?

First thanks for this amazing project!

I am unable to use the call_service function on 'knx/send', no matter which data-type/payload.
Tested some other service calls without a problem.

### Version

v4.4.1

### Installation type

Home Assistant add-on

### Relevant log output

```sh
2023-04-13 22:57:00.554572 WARNING HASS: Code: 400, error: 400: Bad Request
2023-04-13 22:57:00.553379 WARNING HASS: Error calling Home Assistant service default/knx/send
```

### Relevant code in the app or config file that caused the issue

```sh
data = {  'address': '16/0/0', 'payload': 'Hello KNX', 'type': '16.000'}
self.call_service('knx/send', data = data)
```

### Anything else?

Issue first came up 2017 in the ha forum: https://community.home-assistant.io/t/appdaemon-countdown-timer-ui/9802

**Comment by Justihar** [comment]
I would try not wrapping the parameters within data and do something like this instead:
```python
self.call_service("knx/send", address="16/0/0", payload="Hello KNX", type="16.000")
```

**Comment by BoxedBrain** [comment]
Thanks @Justihar! I swear I tried that before, but must have missed something.
