### ISSUE TITLE
HASS support `get_entity` by attribute

### ISSUE THREAD

**Issue by carlos-sarmiento** [AppDaemon/appdaemon#1761]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Your feature request

I'm building an automation in which I want to find all the entities which have a particular attribute set for their state. At the outset I have no idea of which entities those would be so I would need to enumerate through the whole list to figure it out.

I tried to see if there is a method to do such a thing on the documentation and issues.

PS: If someone is willing to point me in the right direction I'd be more than happy to write any required PRs

**Comment by acockburn** [comment]
Seems like you could do this in one line of code (which I would have to add to AD core anyway to address this, so it's not as if it would be more efficient. Something like:

```python
entities = [ e for e in self.get_state().values() if "desired_attribute" in e["attributes"] and e["attributes"]["desired_attribute"] == "desired_value" ]
```

Should do it.

**Comment by acockburn** [comment]
In fact, per your suggestion above, this could be added to ad_api.py as a new api method, fairly easily if you see value in it, I would accept a PR for that.
