### ISSUE TITLE
AppDaemon HASS plugin reports wrong sunrise and sunset times 

### ISSUE THREAD

**Issue by gufonero** [AppDaemon/appdaemon#1802]
### What happened?

AppDaemon sunrise and sunset times as reported by the respective functions in a class derived from hass.Hass are not consistent with the actual ones.

The expected times for the location where the AppDaemon instance is configured are: sunrise 06:53, sunset 21:29 local time (GMT+02:00), according to https://dateandtime.info/es/citysunrisesunset.php?id=3117735. As shown below, AppDaemon gives 05:14:16 and 17:15:18 respectively, which are completely unrelated; the time zone and both the current and the UTC times (17:04:02 and 15:05:02) look fine however.

Maybe I'm missing something obvious here, but I cannot make sense of it. Could somebody more knowledgeable please check these results? I find it difficult to believe that it is an actual bug and that none has noticed yet.

### Version

4.4.2

### Installation type

Docker container

### Relevant log output

```sh
self.sunrise(today=True)=datetime.datetime(2023, 5, 19, 5, 14, 16, 800820)
self.sunrise(today=True, aware=True)=datetime.datetime(2023, 5, 19, 5, 14, 16, 800820, tzinfo=<DstTzInfo 'Europe/Madrid' CEST+2:00:00 DST>)
self.sunset()=datetime.datetime(2023, 5, 19, 17, 15, 18, 586512)
self.sunset(aware=True)=datetime.datetime(2023, 5, 19, 17, 15, 18, 586512, tzinfo=<DstTzInfo 'Europe/Madrid' CEST+2:00:00 DST>)
self.time()=datetime.time(17, 4, 2, 420472)
self.datetime()=datetime.datetime(2023, 5, 19, 17, 4, 2, 420772)
self.get_now()=datetime.datetime(2023, 5, 19, 17, 4, 2, 421067, tzinfo=<DstTzInfo 'Europe/Madrid' CEST+2:00:00 DST>)
self.get_tz_offset()=120.0
datetime.datetime.utcnow()=datetime.datetime(2023, 5, 19, 15, 4, 2, 421586)
self.get_timezone()='Europe/Madrid'
```

### Relevant code in the app or config file that caused the issue

```sh
self.log(f"\n{self.sunrise(today=True)=}"
         f"\n{self.sunrise(today=True, aware=True)=}"
         f"\n{self.sunset()=}"
         f"\n{self.sunset(aware=True)=}"
         f"\n{self.time()=}"
         f"\n{self.datetime()=}"
         f"\n{self.get_now()=}"
         f"\n{self.get_tz_offset()=}"
         f"\n{datetime.datetime.utcnow()=}"
         f"\n{self.get_timezone()=}")
```

### Anything else?

When looking for the AppDaemon version I looked for it in the log but I couldn't find it, so I took it from the docker-compose.yaml file (image `acockburn/appdaemon:4.4.2`). I  take the opportunity to suggest that AppDaemon report its own version to the log on start; this would help to spot configuration mistakes.

**Comment by gufonero** [comment]
Never mind, after a lot of frustration this was just a wrong parameters issue: longitude and latitude were inadvertently exchanged.  Sometimes triple-checking is not enough to spot your own mistakes...

**Comment by acockburn** [comment]
Thanks for letting us know.
