### ISSUE TITLE
Icon widget extension: service calls - ignored for default state

### ISSUE THREAD

**Issue by lancasterJ** [AppDaemon/appdaemon#1857]
### What happened?

The icon widget supports post_service_active for calling a Homeassistant service when the icon is clicked.  This does not work when sensor state is not listed in the state map and the "default" rule is matched.

I believe the cause of the issue is line 89 in baseicon.js ([https://github.com/AppDaemon/appdaemon/blob/02a45c36c0e4d22ae14e630e7e747406fad4b753/appdaemon/widgets/baseicon/baseicon.js#L89-L90]) 

It is currently 
`set_service_call(self, self.parameters.default);`

and should be

`set_service_call(self, self.parameters.icons.default);`

### Version

4.4.2

### Installation type

Home Assistant add-on

### Relevant code in the app or config file that caused the issue

```sh
maintenance_alert:
    widget_type: icon
    entity: sensor.maintenance_alert
    title: Maintenance
    title2: summary
    state_text: 1
    icons:
      "No alert":
        icon: mdi-progress-clock
        post_service_active:
          service: homeassistant/turn_on
          entity_id: script.ad_load_dashboard_maintenance_pi_toilet         
      "default":
        icon: mdi-alert
        post_service_active:
          service: homeassistant/turn_on
          entity_id: script.ad_load_dashboard_maintenance_pi_toilet
```

**Comment by acockburn** [comment]
fixed in dev
