### ISSUE TITLE
Script wiped out after upgrade to 15.0 / 15.2

### ISSUE THREAD

**Issue by smorvan** [AppDaemon/appdaemon#1859]
### What happened?

Seems like my script is gone after upgrading to 15.0 / 15.2

I went to the new folder where the data is supposed to be stored but it is not there. My script was replaced by a hello world example.

Another, older script, was there and it seems like it was the right one - albeit older.

I was not able to restore from a 14.x backup. There was nothing backed up.

That script was many many many hours in the making. This sucks.

### Version

0.15.0

### Installation type

Home Assistant add-on

**Comment by acockburn** [comment]
AppDaemon code has not changed in many months, this seems to have been triggered by a change in the Addon which is not maintained by this team, I suggest you create an issue there.

**Comment by acockburn** [comment]
Thanks for the link - will close this now.
