### ISSUE TITLE
What Have you done?

### ISSUE THREAD

**Issue by AditaNi** [AppDaemon/appdaemon#1861]
### What happened?

After updating the appdaemon is not starting anymore. Why?

Before the update it was working fine since one year ago.....WHY?

### Version

0.15.2

### Installation type

Home Assistant add-on

### Relevant log output

```sh
[17:51:48] INFO: Starting AppDaemon...
s6-rc: info: service legacy-services successfully started
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 8, in <module>
ERROR Error loading secrets file: /config/secrets.yaml
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 417, in main
    admain.main()
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 276, in main
    if "appdaemon" not in config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
[17:51:58] INFO: Service AppDaemon exited with code 1 (by signal 0)
```

### Anything else?

Please repair it ASAP!

**Comment by frenck** [comment]
You are barking against the wrong tree. Please check this issue for more information:

https://github.com/hassio-addons/addon-appdaemon/issues/287

../Frenck

**Comment by acockburn** [comment]
THis is due to a problem in the HASS addon code. Their github has an issue with a description and workaorund

**Comment by AditaNi** [comment]
> You are barking against the wrong tree. Please check this issue for more information:
> 
> [hassio-addons/addon-appdaemon#287](https://github.com/hassio-addons/addon-appdaemon/issues/287)
> 
> Please close the issue on this end, as this is not their issue.
> 
> ../Frenck

such an idiot!

**Comment by AditaNi** [comment]
Thanks @acockburn.

No thanks @Frenck .....if you read the error that I'm facing you can see that there is no mention about HASS and the log is pointing out your appdaemon.
For me as a enduser I cannot see from error cames.

**Comment by JanJoh** [comment]
> Thanks @acockburn.
> 
> No thanks @frenck .....if you read the error that I'm facing you can see that there is no mention about HASS and the log is pointing out your appdaemon. For me as a enduser I cannot see from error cames.

Actually, you can indeed see that it as HomeAssistant error, as the error is shown within the supervisor/docker context of homeassistant. So, Frenck is correct (and as the maintainer of the package... he should be ;) )

**Comment by AditaNi** [comment]
@JanJoh ... ok for my understanding is still appdaemon error, because HA is not reading from where is supposed to. 
Anyway:
Please try also to understand not everyone is involved in development for such kind of "tools/apps/programs/etc". 
Like I wrote I'm just an end user. 
If something goes wrong then it is very difficult for un-experienced people to correct the errors.

Anyway big THANK YOU to you all (this time also Frenck ;)) after 3 hours and a lot of reading i fixed the problem for my HA-OS.
Is not easy but it works.
Issue can be closed.
