### ISSUE TITLE
appdaemon folder emptied on Nov 16?

### ISSUE THREAD

**Issue by madchap** [AppDaemon/appdaemon#1862]
### What happened?

For some unknown reasons, I am unable to explain why my /config/appdaemon folder was totally emptied on November 16th... this let to the crash of AppDaemon as a whole. I tried to restore from backup the main files (e.g. appdaemon.yaml, apps folder and apps.yaml alonside some apps), but it does not want to start complaining about -- see snippet right below.

My /config/secrets.yaml is just fine, however.

I am a bit at a loss...

I also tried to uninstall and reinstall the add-on, to no avail. Appdaemon worked fine for a long time until this happened. When it happened, I was not even home and took no action for days.

### Version

4.4.2 (Add-on version: 0.15.2)

### Installation type

Home Assistant add-on

### Relevant log output

```sh
[09:14:48] INFO: Starting AppDaemon...
Traceback (most recent call last):
  File "/usr/bin/appdaemon", line 8, in <module>
ERROR Error loading secrets file: /config/secrets.yaml
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 417, in main
    admain.main()
  File "/usr/lib/python3.11/site-packages/appdaemon/__main__.py", line 276, in main
    if "appdaemon" not in config:
       ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable
[09:14:54] INFO: Service AppDaemon exited with code 1 (by signal 0)
```

**Comment by acockburn** [comment]
Hi there - this is due to an issue with the HASS add-on and is not an AppDaemon issue. Please see this link for an explanation and recovery steps:

https://github.com/hassio-addons/addon-appdaemon/issues/287

**Comment by madchap** [comment]
Thank you, very helpful. I will close this issue. Cheers.

**Comment by acockburn** [comment]
No worries - if you don't mind I'll reopen it for now so others can see the resolution.
