### ISSUE TITLE
Add support for service calls that return data such as todo/get_items

### ISSUE THREAD

**Issue by bbrendon** [AppDaemon/appdaemon#1891]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Your feature request

Right now, if you do a service call such as:

```
a = self.ad_api.call_service('todo/get_items', entity_id='todo.chores', return_result=True)
```

Appdaemon says:
```
appdaemon  | 2023-12-04 21:17:03.183763 INFO AppDaemon: Calling initialize() for ToDo
appdaemon  | 2023-12-04 21:17:03.191523 WARNING HASS: Error calling Home Assistant service default/todo/get_items
appdaemon  | 2023-12-04 21:17:03.191707 WARNING HASS: Code: 500, error: 500 Internal Server Error
appdaemon  |
appdaemon  | Server got itself in trouble
```

**Comment by Tomasinjo** [comment]
Any ETAs on that? I've read on Discord that it's not that simple to implement this.
Any workarounds available?

**Comment by acockburn** [comment]
We are looking at this - it means switching from the HASS REST API to using the stream with is a fairly substantial change, but necessary for other reasons.

Closing as duplicate
