### ISSUE TITLE
Python package imports - "expert mode"

### ISSUE THREAD

**Issue by jsl12** [AppDaemon/appdaemon#1914]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

## Request
Add a configuration key in `appdaemon.yaml` to allow the normal import of Python packages that are stored in the `apps` folder

## Usage Example
I have a repo called `my_repo` with a package inside called `my_pkg`. I'd like to import a class `MyClass` from `my_module.py` from the `my_ad_app.py` file like this.

```python
from my_pkg.my_module import MyClass
```

<details><summary>Directory Structure</summary>

```shell
└── apps
    ├── app.yaml
    ├── my_ad_app.py
    └── my_repo
        ├── my_pkg
        │   ├── __init__.py
        │   └── my_module.py
        └── pyproject.toml
```

</details>

## Current Behavior

- [This line](https://github.com/AppDaemon/appdaemon/blob/5bec5a0de2f81c721dafe96477e301c588282234/appdaemon/app_management.py#L887) in `app_management.py` uses `os.walk` to add all the directories not named `__pycache__` to `sys.path` [here](https://github.com/AppDaemon/appdaemon/blob/5bec5a0de2f81c721dafe96477e301c588282234/appdaemon/app_management.py#L897)
- [This line](https://github.com/AppDaemon/appdaemon/blob/5bec5a0de2f81c721dafe96477e301c588282234/appdaemon/app_management.py#L905) skips files called `__init__.py`

## Implementation

I had something like this in mind:

```python
import sys
from pathlib import Path

def top_level_packages(base_path: Path):
    parents = [f.parent.resolve() for f in base_path.rglob('*.py')]
    top_level = set(str(p) for p in parents if not (p.parent / '__init__.py').exists())
    return top_level

for pkg_dir in top_level_packages(self.AD.app_dir):
    if pkg_dir not in self.module_dirs:
        self.logger.info("Adding %s to import path", pkg_dir)
        sys.path.insert(0, pkg_dir)
        self.module_dirs.append(pkg_dir)
```

**Comment by acockburn** [comment]
This should be resolved in dev with the `import_paths` and `import_method` directives.
