### ISSUE TITLE
Support `silent` in `cancel_listen_state`

### ISSUE THREAD

**Issue by danroc** [AppDaemon/appdaemon#2007]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Your feature request

It would be nice if `cancel_listen_state` supported a `silent` parameter, similar to `cancel_timer`. If accepted, I can work on a PR.

**Comment by acockburn** [comment]
I’d be happy to merge a PR for this, thanks. Please make sure you update the docs as well!

Andrew

**Comment by danroc** [comment]
Thanks @acockburn, I submitted a PR (#2008)!
