### ISSUE TITLE
Discord link in README.md is invalid or expired

### ISSUE THREAD

**Issue by crhbetz** [AppDaemon/appdaemon#2060]
I wanted to join the discord chat using the link provided in the readme, but the discord app says the link is "invalid or expired".

**Comment by acockburn** [comment]
Thanks for reporting this!

I created a new link: https://discord.gg/sgSr79jW5x

The docs are updated and will be visible in the dev branch soon, and the main branch in the next release.



Give the link a try and let me know here or on Discord if it works!

**Comment by acockburn** [comment]
Fixed!
