### ISSUE TITLE
Documentation (minor) example error

### ISSUE THREAD

**Issue by nottledim** [AppDaemon/appdaemon#2132]
### What happened?

Testing the Restful API Support example for http endpoints.  It doesn't work.

### Version

4.4.2

### Installation type

Home Assistant add-on

### Relevant log output

```sh
I get initialize failed. myCallback not found
```

### Relevant code in the app or config file that caused the issue

```sh
def initialize(self):
        self.register_endpoint(my_callback, "test_endpoint")
```

### Anything else?

You should write **self**.my_callback

**Comment by acockburn** [comment]
Are you saying it DID work when you used `self.callback`? Are you saying this is a bug in the docs?

**Comment by nottledim** [comment]
On 10/17/24 14:54, Andrew Cockburn wrote:
> Are you saying it DID work when you used |self.callback|? Are you saying this is a bug in 
> the docs?
Yes it did work and it's just a documentation bug.

**Comment by acockburn** [comment]
Thanks for spotting this, I have fixed it in the dev branch and it will be in the next release, which should be 4.5.0.
