### ISSUE TITLE
self.entity.turn_on silently dropped by Appdaemon

### ISSUE THREAD

**Issue by bachmarc** [AppDaemon/appdaemon#2185]
### What happened?

Hi, 
I have an entity instance pointing to a HA input_boolean that is ignoring the methods turn_on

```
self.status_input_boolean.turn_on
```
will do nothing, no error is in log... it seems to be fired to the void...

while a simple 

`self.turn_on(self.status_input_boolean_name)`

does the job,  while it is initialized as following:

```
self.status_input_boolean_name = self.args["status_input_boolean"]
self.status_input_boolean = self.get_entity(self.status_input_boolean_name)
```
 
 I would like to use a consistent OO style and hate to work with labels instead of instances.

### Version

4.4.2

### Installation type

Home Assistant add-on

**Comment by Justihar** [comment]
Assuming `self.status_input_boolean` an entity object, it looks like you're missing the () after turn_on. Should be `self.status_input_boolean.turn_on()`

**Comment by bachmarc** [comment]
I am not arguing against it, as it works with brackets now!

Coming from ruby this is a pity mistake because there the () is optional and even attributes are functions.
I know it might be the wrong place to ask but what is python then doing with the line?
Is it searching for an instance.variable of that name and returning a valid None with no further action? Correct?

**Comment by Justihar** [comment]
Typically it would return the method object's memory location. AD might be suppressing the message but it would typically be something like this: `<bound method MyClass.turn_on of <__main__.MyClass object at 0x00000297BECF7860>>`

**Comment by bachmarc** [comment]
THx for your fast help!

**Comment by bachmarc** [comment]
No bug, just a ruby guy failing with python
