### ISSUE TITLE
Feature Request: App-local data storage

### ISSUE THREAD

**Issue by efficiosoft** [AppDaemon/appdaemon#676]
Hi,

I'm not sure whether this is planned for 4.0 and, even if so, whether you already implemented it, but I'd like to have an uniform way to store app-specific data, probably best as a persistent key-value store.

If desired, I could provide a thread-safe implementation using Python's `shelve` with an API like this:

```
self.open_storage()  # When called the first time, a persistent db file is created based on app name
self.store["foo"] = [1,2,3]  # writes synchronously to the file, using the regular dict API
```

On app shutdown, AD would just close the store if it has been opened, no invasive code changes needed.

What do you think?

Best regards
Robert

**Comment by Odianosen25** [comment]
@efficiosoft,

This has already been implemented in AD 4.0. AD now has the ability to define [user defined namespaces](https://github.com/home-assistant/appdaemon/blob/4.0.0b1/docs/CONFIGURE.rst#advanced-appdaemon-configuration). These are namespaces, not tied to any plugin and can be used as desired. it can also be set such that when data is stored there, it saves into file the present state (depending on the performance required). 

These namespaces can also be persistent, and so all entities stored in here, are loaded up at boot time. I use this, in conjunction with an app, to get data I want stored or state of some entities I need, in here, and at start up, these entities are loaded back into the required namespaces they are to operate. For example windows or door sensors.

Regards

**Comment by efficiosoft** [comment]
@Odianosen25 Interesting, thanks. I guess the entities are serialized as JSON?

**Comment by Odianosen25** [comment]
You welcome @efficiosoft,

Yes they are. So data that has issues with serialisation cannot be stored in there.

**Comment by Odianosen25** [comment]
Please close the issue when you satisfied.

Thanks

**Comment by ReneTode** [comment]
@efficiosoft i also found this:
https://appdaemon.readthedocs.io/en/dev/AD_API_REFERENCE.html#appdaemon.adapi.ADAPI.save_namespace

and you might not know it but it can be helpfull for you, we now got an index in the docs:
https://appdaemon.readthedocs.io/en/dev/AD_INDEX.html#s

**Comment by efficiosoft** [comment]
Ok, I still think it would be useful to have a kind of implicit per-app namespace that can be used to store internal state, especially when using third-party apps as-is. Do you think that's feasible?

**Comment by efficiosoft** [comment]
@ReneTode Thanks for the links. I indeed only saw the stable versions built on rtfd.

**Comment by ReneTode** [comment]
you can create a namespace for each app.
at this moment that isnt as easy as it should be,
but we are working on create_namepace and delete_namespace.
it should be there before we leave beta.

so then you can create namespace in an app and save it on terminate.

**Comment by efficiosoft** [comment]
I think it would be good to not require people to configure some internal detail (like correctly named namespaces) just to be able to use a pre-built app, so a way to move this responsibility to the app developer would indeed be desirable.

**Comment by ReneTode** [comment]
you could already save the data yourself as app developer, but now we will have the options as predefined functions.

**Comment by efficiosoft** [comment]
@Odianosen25 BTW, can't we simply configure the default namespace (so let's say that used by the hass plugin) to be persistent and just have persistent states for all entities that way?

**Comment by efficiosoft** [comment]
Of course a full JSON dump at every state change would not be desirable in terms of performance and flash wearout, but when simply using a `Shelf` instead of the plain dict to represent custom namespaces, this wouldn't be a problem, and with `writeback=True`, we not even have performance hits... sounds like a considerable alternative to me.

**Comment by ReneTode** [comment]
yes that should be possible odia. for instance the mqtt namespace should have that :P

**Comment by efficiosoft** [comment]
If you want, I can make a PR that uses `Shelf` for all user-defined namespaces and still supports the current writeback strategies.

**Comment by ReneTode** [comment]
but @efficiosoft it wouldnt be very helpfull for hass.
you would need to save all data from hass locally, and the second the plugin connects to hass it gets all retrieved from hass.
that would be a bad idea for saving the single entities you create in AD.
in that case better use local namespace and also send to hass.

**Comment by efficiosoft** [comment]
@ReneTode That single replacement operation is cheap, and with the performance strategy it iss only done in memory.

**Comment by Odianosen25** [comment]
No we can't now, but really its something that can be built in, but honestly I don't think its a good idea as I had looked into it before.

Messing around with the namespace by the plugin, is something to be avoided, and that was why the user defined ones were created. If we do that, it could lead to messed up data. As the plugin is supposed to get its state from the remote program it is communicating with.

Also AD tends to frequently update the plugin state every 10 minutes, based on that, not sure there is a need. I have uploaded my app I use for storing entities from other namespaces [here](https://github.com/Odianosen25/appdaemon_apps/tree/master/storage_app). This will also load them back into the required namespace at start up.

On the issue of performance, that is what I use, and it means AD will not save the namespace to file, unless done. In my sample app, the `storage` namespace in on performance, and so I save my data every 30 minutes not on every state change.

**Comment by ReneTode** [comment]
@efficiosoft on the HA forum you say that it should be in AD, because not every user would do it the same.
now we say we got/create the option and you want to change it to shelve?

you yourself didnt use it because you rather have it developed by an architect ;)

**Comment by efficiosoft** [comment]
@ReneTode Wait, we're going to misunderstand each other. I was saying I'm against letting each app developer implement his own file store/load mechanism because that, especially considering the threaded architecture of AD, can lead to some issues and I'd rather have a single, well architected mechanism for storing custom data. Such a mechanism can of course be the namespaces concept.

I thought about backing the user-defined namespaces by `shelve` for different reasons, not moving away from namespaces.

**Comment by Odianosen25** [comment]
On using shelf @efficiosoft,

I used to use shelf to store data, but as you know it can't be read without using another software to read it, which is very annoying. That is one of the reasons using `json` as we have it now I think is better. Added to the fact I believe shelving is slower, compared to using plain json.

Regards

**Comment by ReneTode** [comment]
> I thought about backing the user-defined namespaces by shelve for different reasons, not moving away from namespaces.

and thats what i mean.
the "architects" are creating a way they seam best and use json dumps. and you want to change that to shelve.

but like i said on the forum, people can do it the way they like, as they always have and always will.
and we have created/ are developing a way that does what you want. saving by AD.

we are still working on it and all the things you said are already in our minds to notice.
you can play around with whats already there and get suprised to what we come up more ;)

**Comment by efficiosoft** [comment]
@Odianosen25 Shelve's performance depends on the usage pattern. Especially disk access is a lot better when you do only small updates to the whole, potentially larger, dataset, which is why I think it's appropriate for keeping a whole plugin namespace in sync (that was just an idea without knowing too much about the internals of AD, you're the expert in this domain). Its API is also very friendly, because it's - as you know - just dict-like and thus could be used as a drop-in replacement.

The key benefit is when using the `safe` writeback strategy you don't have to rewrite the whole JSON dump if only one entity has changed.

Given that you probably won't read the stored files manually, I see the binary format more as an advantage because it's small. And we could easily add a command line option that converts a given db to JSON or YAML for manual inspection.

**Comment by efficiosoft** [comment]
> > I thought about backing the user-defined namespaces by shelve for different reasons, not moving away from namespaces.
> 
> and thats what i mean.
> the "architects" are creating a way they seam best and use json dumps. and you want to change that to shelve.

Really? We're discussing potential improvements here (at least that's what I came here for). If you don't appreciate people throwing their ideas and experience in, just point that out and ignore the conversation.

> but like i said on the forum, people can do it the way they like, as they always have and always will.
> and we have created/ are developing a way that does what you want. saving by AD.

Sure they can with a turing-complete language like Python ;)
And nevertheless: Simple is better than complex.

**Comment by Odianosen25** [comment]
@efficiosoft,

Lols I am in no way close to being an expert, maybe an expert at twisting @acockburn's hands for a feature, that others end up using and asking him for why he did it that way. So some of what I am telling you, are what Andrew had told me before when I queried him.

I don't think he will be adverse to having the optional `shelf`, and make it user configurable. So you could add it, and submit a PR for it to be added. I do know one other advantage of using `shelf` or pickle is the ability to serialise python objects, which is not possible with json.

Regards

**Comment by efficiosoft** [comment]
I explicitly didn't mention the ability to store deepcopy-able objects because I thought the serialization constraints of JSON where there to stay REST-API compatible, but sure, that's another benefit. Anyway, IMHO there shouldn't be two parallel implementation for the same thing, and if you weigh JSON's readability more than the easier handling and random accesses possible by shelve, than that's fine to me. I'll nevertheless make the implementation because it's trivial and then you and @acockburn can judge about it.

**Comment by ReneTode** [comment]
i really dont understand you robert.

i: you could save your sensors
you: no dont want to do it myself it should be created by AD because its complicated
i: AD is providing an option
you: ill create an issue anyway
odia: the option is there
i: and it will be expanded 
you: thats not how i want it, ill create it myself anyway.

then why this whole discussion? you could have done that in the first place.
we have chosen a way, in this case without shelve.
you have given your opinion why you think shelve would be better. so there ends the discussion.
and then its up to us if we decide if we use shelve or json dump, but the option shelve was already considered and not chosen.

so accept our choices, or create something yourselve as i suggested in the first place. ;)

**Comment by efficiosoft** [comment]
> i really dont understand you robert.
> 
> i: you could save your sensors
> you: no dont want to do it myself it should be created by AD because its complicated
> i: AD is providing an option

Wrong, you said you think something like that may come with 4.0, but you aren't sure. That's why I said I'll create an issue and asked if it's planned or not.

> you: ill create an issue anyway
> odia: the option is there
> i: and it will be expanded
> you: thats not how i want it, ill create it myself anyway.

Never said that.

> then why this whole discussion? you could have done that in the first place.
> we have chosen a way, in this case without shelve.
> you have given your opinion why you think shelve would be better. so there ends the discussion.
> and then its up to us if we decide if we use shelve or json dump, but the option shelve was already considered and not chosen.

Honestly, what has been said so far makes it in no way clear that all drawbacks of the chosen approach have been recognized. I mentioned some, you weren't able to respond in a technically qualified manner and instead try to block serious efforts to have a focussed discussion.

> so accept our choices, or create something yourselve as i suggested in the first place. ;)

Don't feel like you (as a person) or AppDaemon as a project have been attacked. Neither is the case and I'm sure users greatly appreciate the support you give. But lessons I learned so far showed to me that attempts to have technical discussions between you and me rarely lead anywhere. Not an issue to me at all, I just won't try to have such anymore with you and use the time differently.

**Comment by dlashua** [comment]
@efficiosoft I do like the idea of having an app-based storage space. regardless of how that data is stored (json, pickle, shelf, etc).

I do this already by creating a user-defined name space (say, called appstore) and then having my apps do this:
```
self.set_state(self.name, state="some_state", attributes={"my":"app", "data":"goes here"}, namespace="appstore")
```

Then, to retrieve, I use:
```
self.get_state(self.name, attribute="all", namespace="appstore")
```

I use it to "freeze" the state of an app at various times during its life-cycle. Outside of the configuration in YAML, my app has learned quite a few things and it would be best if that information could be retained across a restart.

But, you're right in that offering a shared app that requires a persistent datastore would require the user of that app to set up that persistent store in appdaemon.yaml and then restart. And the app would also need a configuration parameter for the name of the datastore namespace, which isn't as simple as it could be. So I agree that an built-in, internal, persistent datastore, along with easy API calls to set and retrieve that data would be useful.

I'll be pushing for this, and, until that happens, the above approach is probably the way to go if your data can fit into the confines of a JSON data store.

**Comment by ReneTode** [comment]
> But lessons I learned so far showed to me that attempts to have technical discussions between you and me rarely lead anywhere.

i just have a different view, and in a lot of cases a different opinion.
i am not easyly convinced that something is better, if there are already other ways.
and i am always the opinion that there are several good possibilities (as wel as bad)

see it like this: in a discussion with me dont try to convince me why something is better, but provide options to think about. there are more people reading our discussion. that can get a better view of things because of such discussions.

and sorry if i did understand that you would create it yourself anyway because you said: "'ll nevertheless make the implementation"

by the way, i said: if i am not mistaken it IS in AD 4. at least odia IS WORKING with something like that.
i really dont see where you get that it might not be planned in AD 4.

**Comment by efficiosoft** [comment]
@dlashua 

> I do this already by creating a user-defined name space (say, called appstore) and then having my apps do this:
> 
> ```
> self.set_state(self.name, state="some_state", attributes={"my":"app", "data":"goes here"}, namespace="appstore")
> ```
> 
> Then, to retrieve, I use:
> 
> ```
> self.get_state(self.name, attribute="all", namespace="appstore")

I think each app instance should have its own datastore to have the flexibility of using different writeback strategies. But with the upcoming dynamic namespace creation, this should become easy. We just need conventions for names so that app namespaces don't conflict. Maybe provide a new app attribute `app_namespace = "app_%s" % self.name`? One can then use

    self.get_state("foo.bar", namespace=self.app_namespace)

**Comment by dlashua** [comment]
When apps create namespaces, namespace conflicts quickly become an issue. This is the reason I suggested creating a single namespace to hold all persistent app data -- fewer namespaces means a conflict is less likely. But, you're right, the writeback strategy would have to affect all or nothing. Though, if handled internally with exposed API calls, I imagine the internal namespace writeback strategy could be be set to "safe" but the api call itself could allow you to set something less intensive as a parameter in the API call with the default also being "safe".

This should allow flexibility for advanced app developers, but simplicity and safety for those who don't wish to manage it themselves.

Of course, for an app making heavy use of data persistence and potentially storing many different attributes as components of a larger system (for instance, an app that connected to a Philips Hue system and created entities for the elements in that system) you're probably going to want an entire namespace. At which point, I'd suggest writing a "plugin" instead (docs on custom_plugins coming at some point during this beta I believe) or, at the very least, giving the user the option to specify a namespace in the YAML config so they can ensure there are no conflicts. If you really wish to avoid that, at the very least I'd use something like "myprefix_{self.name}" as a namespace to avoid conflicts as much as possible.

I understand the desire for self.app_namespace, but I'm not sure how to implement it safely. Regardless of the method used to determine the app_namespace, there is always the potential that the user will create a manual namespace using the same name later.

Similar to using set_state() in an existing namespace, you have to beware of conflicts and therefore, at least in my apps, I always leave that configurable in YAML.

**Comment by efficiosoft** [comment]
> I understand the desire for self.app_namespace, but I'm not sure how to implement it safely. Regardless of the method used to determine the app_namespace, there is always the potential that the user will create a manual namespace using the same name later.

That could be prevented by using a fixed prefix (e.g. `app_`) and not allowing to create user-specific namespaces with that prefix.

**Comment by efficiosoft** [comment]
Also, not every app will need a datastore, hence I'd suggest still having to create it explicitly in `initialize()` using the regular API that's going to be added anyway (e.g. `self.create_namespace(self.app_namespace, writeback="hybrid")`).

**Comment by dlashua** [comment]
> That could be prevented by using a fixed prefix (e.g. app_) and not allowing to create user-specific namespaces with that prefix.

That could work and would provide some sanity to the situation. There's an additional complication (that would exist regardless of how the namespace is handled) regarding an app name that is reused with residual data in a persistent namespace.

And, I agree, that if persistent app-level datastores are to be managed by AD, there's no reason to create them automatically. It could be done intentionally, as you described, or on the first self.save_app_data() (or whatever) call if the namespace didn't exist already. Or both, using create_namespace() to override the default writeback strategy and avoiding that call entirely if the defaults don't concern the app author.

I think, if you're going to do this in app space (without AD internal functions to help) using app_{self.name} as a good way to go, assuming you check for existing data and clear it or show an error to the user when the namespace appears to be "used" already. Setting a entity like "app_name" and "app_version" to something to expect to see is a good way to ensure the data there belong to your app (using two different entities so that you can safely upgrade your users data as long as app_name matches). Then a call to get_state() with just a namespace will ensure there's nothing else there that shouldn't be before you get started.

It's an interesting problem, all around, and one that's likely to come up as more and more apps are shared amongst users with a need for persistent data. I support some kind of AD based solution that covers all the common bases and gives app developers a way around for more complicated needs. I would be happy to remove my custom built solution for this in favor of an AD implemented solution.

**Comment by ReneTode** [comment]
if we can create namespaces in intialise, with any name we like, then why would we need a special function that creates a namespace with the name of the app??

self.create_namespace(self.name) would already create a namespace with the name from the app.

**Comment by Odianosen25** [comment]
Yes as @ReneTode said, all app names are unique, so there wouldn't be an issue creating a namespace for an app. if an api call is developed for creating namespaces which has been accepted to be worked on, the simply having in an app's initialization `self.create_namespace()`, without any name, will automatically  create a namespace in AD using the app's name.

Apps already have unique entity names in the `admin` namespace like `app.bedroom_2_light_app_2`. If we decide to extend this into storing data in a persistent way instead of creating namespaces, that's another discussion.

but yeah it is possible, and lets see how it goes

**Comment by acockburn** [comment]
@efficiosoft - this somewhat coincides with some other work we are looking at. So at the moment I will at least re-implement the persistent namespaces to use shelve - I think that is a good idea.

Regarding per-app namespaces, we have also discussed allowing them to be dynamically created with an in-app call. If we do that it should give you most of (all?) that you are asking for. Dynamic creation of namespaces does have a knock on effect on the AUI so it's not quite as simple as it may seem, but we are actively considering it.

**Comment by ReneTode** [comment]
see @efficiosoft discussing with me isnt useless at all ;)

**Comment by efficiosoft** [comment]
> if we can create namespaces in intialise, with any name we like, then why would we need a special function that creates a namespace with the name of the app??

Imho we don't. Such a call would have no benefits and just make the API more complicated.

> Yes as @ReneTode said, all app names are unique, so there wouldn't be an issue creating a namespace for an app. if an api call is developed for creating namespaces which has been accepted to be worked on, the simply having in an app's initialization `self.create_namespace()`, without any name, will automatically create a namespace in AD using the app's name, if it doesn't exist. Same way it is removed if the app is removed.

Great idea in general, however I'd prefer having to supply the namespace name explicitly to `create_namespace()`, since it has to be provided to `get_state()`, `set_state()` etc. as well. All other methods assume the plugin namespace by default (afaik) and thus providing the datastore namespace to `create_namespace()` would make the difference clearer.

> Apps already have unique entity names in the `admin` namespace like `app.bedroom_2_light_app_2`. If we decide to extend this into storing data in a persistent way instead of creating namespaces, that's another discussion.

I don't think that's needed, one API to store things should be sufficient. Maybe just extend the docs to point out that app-specific datastores should be named like the app name?

@acockburn I already have that implementation of `PersistentDict` incl. locking lying around. Give me some minutes for the PR, then we can profile it or do other measurements/considerations.

**Comment by acockburn** [comment]
Sounds good @efficiosoft.

And yes, I agree, the "self.create_namespace()` call should take an arbitrary name, with the docs recommending `self.create_namespace(self.name)` as the best practice for creating app based namespaces.

**Comment by acockburn** [comment]
OK, we have the shelve re-implemnentation now, thanks to your PR - we are scheduling the create_namespace() piece for sometime after the beta closes.

**Comment by Odianosen25** [comment]
This has been fixed as there is a create namespace api so closing

**Comment by henning-meinhardt** [comment]
Hi all, I'm wondering where to find some information about how to create a namespace programmatically which should be possible as of 4.0.6 and which seems to be what @Odianosen25 is talking about. I can't find anything in the docs. A hint would be very nice.

Kind regards
Henning

**Comment by ReneTode** [comment]
https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html#namespace

**Comment by henning-meinhardt** [comment]
@ReneTode thanks for the link, that's what I've already found. From the discussion here I maybe misunderstood that there should be a new method like create_namespace() in order to create a namespace on the fly and that set_namespace() would rely on a namespace predefined in the configuration. So you mean I can use set_namespace() to create a new one that has not been declared in config as well? that's the way to go?

Kind regards
Henning

**Comment by ReneTode** [comment]
yeah, sorry i got my functions mixed up.

there is add_namespace() and remove_namespace()
but i believe that @Odianosen25 forgot to add it to the docs ;) 

or its meant to be a hidden feauture, but then he shouldnt have talked about it ;)

**Comment by henning-meinhardt** [comment]
you are right, found it in the source code. should of course be added to the docs unless its some kind of unofficial

**Comment by ReneTode** [comment]
its added for some special reasons.
i personally think its hardly usefull in almost all cases.
if you create a namespace you normally want to use that in several apps.
then you need to create that namespace in a priority 1 app.
for administration reasons its better to create namespaces at 1 central point, that is started before everything else.
and creating them in appdaemon.yaml is doing that exactly.

off course you could create seperate namespaces for all kind of apps, but i dont think it would make things more usefull.

**Comment by henning-meinhardt** [comment]
@ReneTode my use case is not reusing state in several apps. Instead I just need a way to persist some (private) variables specific to a single app so that I can recover the data upon restart of the app. Instead of reinvention the wheel I thought using the namespaces for that would be a feasible option. I'm away of the fact that I could use any other python mechanism to persist and recover values, but using namespaces also allows me to have a quick look at the contents using the regular appdaemon UI where my namespace is listed.

Kind regards
Henning

**Comment by ReneTode** [comment]
i understand, but you can also do that in 1 preset namespace.
then at least you are 100% sure that the entities (variables) exist before every app starts.
