### ISSUE TITLE
Cannot cancel listener when passing handle from one app to another

### ISSUE THREAD

**Issue by AlexLadd** [AppDaemon/appdaemon#778]
It is not possible to cancel a callback that is created in one app and the handle is passed to a second app. The following two apps below will demonstrate this. I understand that it is possible to create a method in app One that would cancel its own callback but it seems like it should be possible to cancel a callback from any app with the correct handle. 

Home Assistant version: 0.100.2
Appdaemon version : 3.0.5
Environment: Docker

apps.yaml:
```yaml
one:
  module: test
  class: One

two:
  module: test
  class: Two
  dependencies:
    - one
```

test.py:
```python
import appdaemon.plugins.hass.hassapi as hass

class One(hass.Hass):
  
  def initialize(self):
    pass

  def create_callback(self):
    cb = self.run_in(self._run_callback, 10)
    self.log('Callback created in app One: {}.'.format(cb))
    return cb

  def _run_callback(self, kwargs):
    self.log('Callback function _run_callback was called in app One.')


class Two(hass.Hass):
  
  def initialize(self):
    self.one = self.get_app('one')
    self.handle = None
    self.run_in(self._test, 1)


  def _test(self, kwargs):
    self.handle = self.one.create_callback()
    self.log('Created callback using app One from app Two: {}.'.format(self.handle))
    self.run_in(self._cancel_callback, 5)


  def _cancel_callback(self, kwargs):
    self.log('Cancelling callback in app Two: {}.'.format(self.handle))
    self.cancel_timer(self.handle)
```

**Comment by ReneTode** [comment]
a callback is connected to an app, so indeed its not possible to cancel 1 from another app.
if an app is advanced enough to start a callback in another app, it should also be advanced enough to cancel in the other app.

in the end it comes down to 2 lines of code.

see it like this:
an app is an entity and the listener or schedular is an attribute from that entity.
you use a certain way to create and see that attribute, so canceling it should be done the same way.

**Comment by Odianosen25** [comment]
Unfortunately this won't be fixed. Please @acockburn correct me if wrong. Will be closing for now.
