### ISSUE TITLE
Admin interface doesnt load the logs right.

### ISSUE THREAD

**Issue by ReneTode** [AppDaemon/appdaemon#784]
when i open the AI it works great, but when i try to view the logs google chrome gives me a warning that the page is not responding. it gives me the option to close the page or wait, but waiting doesnt help.

I already noticed this behaviour in dev since 18 august.
in older versions i dont have that problem.

**Comment by ReneTode** [comment]
and to top that issue.

in dashboard log i get this
```
2019-10-28 02:28:28.937441 INFO Access: Unexpected client disconnection
```
every second!

**Comment by ReneTode** [comment]
i think the issue is related to deleting log files.
AD automaticly creates a log loop log, log1, log2, etc.
when i delete log1 and or log2 AD tries to read those files to send them to the AI and fails.

the unexpected client issue might have been a version conflict.
the AI was opened when AD was updated.

**Comment by ReneTode** [comment]
no the unexpected client disconnection keeps occuring.
and all i can do to get rid of it is close all my admin pages on every PC.

**Comment by MarkusHornbach** [comment]
i still have the same problem with AD 4.0.1, browser is freezing after viewing some logs in Admin Interface. 
is there any workaround for this?

**Comment by ReneTode** [comment]
no workaround.
it only happens when the logs get to big, and then go to more then 1 file.

issue still open.
