### ISSUE TITLE
Camera widget needs to use tokens to display - after HA .101.2 upgrade.  

### ISSUE THREAD

**Issue by MarkHofmann11** [AppDaemon/appdaemon#796]
Legacy API support has apparently been removed from Home Assistant for cameras.  In order for cameras to display in appdaemon again, would need to use token based authentication.

**Comment by ReneTode** [comment]
yes we know.
AD 4 is in beta and supports token.

but the full release from AD 4 will come after HA 1.01 has been released, so for those using cams on dashboards we advise to not update HA untill AD 4 is released or use the beta version from AD 4 (not available for hassio)

**Comment by MarkHofmann11** [comment]
Thanks for the update/info!  

Excuse this question, but how would I go about installing the beta AD4?  I run HA & Appdaemon on Windows and use "py -m pi pinstall --upgrade appdaemon" as my current method to upgrade.  That doesn't pull the beta obviously, and never knew how to install a beta.

Thanks!

**Comment by MarkHofmann11** [comment]
Looks like I'll have to get the cameras working again for now.  Getting a "No module name 'fcntl' in d:\appdaemon\lib\site-packages\pid\__init__.py - apparently due to the fact I'm running this on Windows.  

From what I read, there is no fcntl support on Windows.  Stuck at the moment.

**Comment by ReneTode** [comment]
still good that you tested.
because now we know there is a problem with installing AD 4 on windows.
we will try to correct that before AD 4 is fully released.

**Comment by MarkHofmann11** [comment]
Glad my efforts were not for nothing.  :)  Happy to test again on Windows when ready.
