### ISSUE TITLE
No module name 'fcntl' in d:\appdaemon\lib\site-packages\pid_init_.py  (4.x beta - on Windows)

### ISSUE THREAD

**Issue by MarkHofmann11** [AppDaemon/appdaemon#797]
Tested Appdaemon v4 beta on Windows - getting is error:

**No module name 'fcntl' in d:\appdaemon\lib\site-packages\pid_init_.py**

It appears the work-around is to use "import portalocker" and change instances using fcntl to use portalocker for Windows systems only.  There might be a better way.  I got past that error by doing just that.

Found this bit of interesting information on cross-platform file locking:

https://www.oreilly.com/library/view/python-cookbook/0596001673/ch04s25.html

Then got:  **"Error getting state, check Java Console for details"** for all my dashboards after getting around that initial problem.  Could be related, not sure.

**Comment by ReneTode** [comment]
did you update from an AD 3 version?
because then you need to make changes to your appdaemon.yaml (see breaking changes and configuration in the AD dev docs)
that could solve your dashboard problem.

the file locking thing i leave up to @acockburn

**Comment by MarkHofmann11** [comment]
Yes, I upgraded from AD 3 and did make all the updates to the appdaemon.yaml.  I was able to get it running on Windows after commenting out the "import fcntl" and adding the "import portalocker" and replacing references to fcntl with portalocker (just to see if I could get it to work on Windows).  That park worked after those changes.  So, the fix could be as simple as if "os=windows" then use the other logic, otherwise use fcntl.  

I believe the Error getting state, check Java Console for details could have been due to me not clearing the browser cache after all the updates.  For the time being, I reverted back to AD 3.

Will see what @acockburn thinks concerning the cross-platform file locking.

**Comment by MarkHofmann11** [comment]
![Capture](https://user-images.githubusercontent.com/13205433/68091477-3dd84a80-fe4e-11e9-97e1-b95385c13df7.JPG)
For the time being, got the camera images working in AD 3 again by pointing the URL to my internal Blue Iris program.  http://blueiris-ip/image/camera-short-name

**Comment by FredericMa** [comment]
I've seen that Windows support has been added to pid so in the next release of pid this issue should be solved.

**Comment by MarkHofmann11** [comment]
That is great news, is there a link referencing the updates to allow Windows support?  Back when I was testing, I was able to get it working based on the changes I listed above.  Good to know a permanent solution is in the works!
