### ISSUE TITLE
Oneshot not quite right

### ISSUE THREAD

**Issue by martinlong1978** [AppDaemon/appdaemon#836]
Hi, 

It's very difficult to find bugs in appdaemon, but I think I've got one. 

When i set the oneshot option on listen_state, also specifying "old" and "new" values, then it considers the "oneshot" to be complete, even if the old and new criterea are not met. 

So, for example I set up a listener on my door lock... 

self.listen_state(self.locked, self.lock, new = 'locked', old = 'unlocked', execute_when = func, oneshot = True)

however, if the door is already locked, and I unlock it first, then relock it, this doesn't get fired. I ASSUME that this is because it is considering the first "locked" -> "unlocked" event to be the "oneshot", and it then cancels the listener after that. 

I get around this by removing the oneshot flag, and grabbing a handle which I cancel myself,  but this adds additional complexity.

**Comment by Odianosen25** [comment]
@martinlong1978 what version of AD you are using pls?

**Comment by martinlong1978** [comment]
Sorry for the late reply. It's version 3.0.5. Thanks

**Comment by Odianosen25** [comment]
Ok @martinlong1978, if that’s the case, kindly upgrade to the latest released 4.0 and see if it continues. There were some bug fixes for oneshot in this release. 

Do take note of breaking changes as you upgrade.

Regards

**Comment by acockburn** [comment]
Have you managed to test this on 4.0.0 or later?

**Comment by martinlong1978** [comment]
I'm sorry, work has taken over for now, I've had no time to test any of it.
Please keep it open, and I hope to give it a try in the next couple of
weeks.

Thanks

**Comment by Odianosen25** [comment]
@martinlong1978,

Any luck on this? As will like to close this. Thanks
