### ISSUE TITLE
constrain_input_boolean behavior

### ISSUE THREAD

**Issue by bratanon** [AppDaemon/appdaemon#872]
Not sure if this was introduced with appdaemon 4 or not, but I have noticed a strange behavior when using the `constrain_input_boolean ` with appdaemon 4.

If using this with a boolean that does not exists (value is None), the expression is evaluated to "true".

From reading the docs, I would have the assumption that as long as the boolean is not "false" the listen_X function would not run.

**Comment by acockburn** [comment]
You are right, the way it is currently coded will give the exact behavior you describe, and it did likely change in AD 4.0. However, since it's been over 3 years (my bad), I don't think it makes sense to restore the old behavior as you can argue it either way. I will however put a note in the docs.
