### ISSUE TITLE
Any plans for upgrading to Astral 2?

### ISSUE THREAD

**Issue by GuyKh** [AppDaemon/appdaemon#886]
When using https://github.com/torkildr/rpi-appdaemon-docker fork where I upgrade the AppDaemon version to 4.0.1 - it launches and then install astral 2.0.1.

Then fails to launch logging this:
```
...
    self.AD = ad.AppDaemon(self.logging, loop, **appdaemon)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/appdaemon.py", line 188, in __init__
    self.sched = scheduler.Scheduler(self)
  File "/usr/local/lib/python3.6/site-packages/appdaemon/scheduler.py", line 54, in __init__
    self.init_sun()
  File "/usr/local/lib/python3.6/site-packages/appdaemon/scheduler.py", line 187, in init_sun
    self.location = astral.Location((
AttributeError: module 'astral' has no attribute 'Location'
```

Any plans to upgrade the package versions in the master branch?

**Comment by ReneTode** [comment]
it seems that that project is abandoned.
so ithink that if you want to be safe to make sure everything is correct, then you need to buid its yourself.

**Comment by ReneTode** [comment]
seems your in luck, dependabot just made a PR to upgrade to astral 2.

not that i am glad with it, because then support for python 3.5 is gone.

**Comment by GuyKh** [comment]
When this is expected to reach a release version?

**Comment by acockburn** [comment]
In the next version all the packages have pinned versions so this shouldn’t be a issue whether or not we decide to upgrade astral.

**Comment by juan11perez** [comment]
Good day. I've upgraded to 4.0.2 and getting this error:

```
2020-02-29 19:35:25.928066 WARNING AppDaemon: ------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/appdaemon/__main__.py", line 117, in run
    self.AD = ad.AppDaemon(self.logging, loop, **appdaemon)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/appdaemon.py", line 188, in __init__
    self.sched = scheduler.Scheduler(self)
  File "/usr/local/lib/python3.8/site-packages/appdaemon/scheduler.py", line 54, in __init__
    self.init_sun()
  File "/usr/local/lib/python3.8/site-packages/appdaemon/scheduler.py", line 187, in init_sun
    self.location = astral.Location((
AttributeError: module 'astral' has no attribute 'Location'
```

reverting to 4.0.1 returns to normal operation

**Comment by nivekmai** [comment]
Heyo, I created https://github.com/AppDaemon/appdaemon/pull/1021 to update to 2.2 and change the calls to astral in `scheduler.py` to work with the new API.

**Comment by ReneTode** [comment]
i believe that Andrew already did look at it a while ago, and if i rember correctly there was way more to it then just some changes in schedular.py

it is already on the list from andrew and if it was that simple then i dont think he would have waited.

at this point there are also other issues with the sun functions.

**Comment by nivekmai** [comment]
Hmm, I don't see any other references to `astral` other than `scheduler.py`. The only usage of `astral` in `scheduler.py` is to set up `location` and the only problem with that was that we need to switch to using `LocationInfo` and `sun` instead of trying to call `sun` from `location` in the old API.

**Comment by ReneTode** [comment]
i dont know exactly what the other issues were, it was a while ago.
it might also have to do with backward compatibility.

it is still possible to run AD in python 3.6, and i have something in my mid that astal needs a higher python version then the minimum that is set for AD.

**Comment by nivekmai** [comment]
> i dont know exactly what the other issues were, it was a while ago.

Looking through the open issues (I found #926 and #889), it appears to be a problem with the state in scheduler, and not something specific to how astral is computing the sunrise/sunset times (updating astral wouldn't affect those bugs, seeing as how the solution from #926 is to just restart AD every day...).

> it is still possible to run AD in python 3.6, and i have something in my mid that astal needs a higher python version then the minimum that is set for AD.
and i believe AD 4 even still runs on python 3.5.3

Yes, astral 2.2 needs 3.6, but seeing as how [home-assistant now needs 3.7.1](https://www.home-assistant.io/blog/2020/07/22/release-113#read-more), I'm not sure why that would be a blocker anymore (are there a lot of AD without home-assistant users?).

**Comment by ReneTode** [comment]
AD is completely independant from HA.
and it can be installed anywhere, where python is installed.

for example: i got HA installed on my main device (which is a beebox) and i got 1 instance from AD installed on my synology NAS, which unfortunatly has python 3.5, and last time i looked still very difficult to upgrade python there.

so also users that use AD with HA still can have environments that have python 3.5
personally i think that there must be a big advantage for most AD users, or a greater need, to exclude those users.

**Comment by nivekmai** [comment]
Sounds good, I'll leave the pull request up as I need it to run a new app I wrote (my app requires astral 2.2), maybe if AD ever updates to 3.6 it can be pulled in.

**Comment by Odianosen25** [comment]
Fixed in dev
