### ISSUE TITLE
get_tz_offset is always returning zero

### ISSUE THREAD

**Issue by sillyfrog** [AppDaemon/appdaemon#910]
I'm new to AppDaemon, and figuring out time stuff - including timezones - and am finding that `get_tz_offset()` is always returning zero.

Running `self.datetime(True)` gives me a (correct) timezone aware datetime, eg: `2020-03-04 14:04:26.233414+10:00`

For the moment, I'm using the following line to get the number of seconds the timezone is offset:
```
self.AD.tz.utcoffset(self.datetime()).total_seconds()
```

I'm wondering if this wouldn't be a better implementation of the `get_tz_offset` method. (I also noticed that the current implementation does not support 1/2 hour offsets based on the comments, this would also address that).

If you think it makes sense, I'm happy to do a PR, but not sure if there are other implications that I'm missing.

Cheers.

**Comment by Odianosen25** [comment]
Hello @sillyfrog,

Do create the PR please and it will be reviewed. I am sure @acockburn will really be willing to look into it. 

Thanks

**Comment by acockburn** [comment]
What timezone are you in? this API call works fine for me  ...

**Comment by sillyfrog** [comment]
I tried a few. I'm in Australia/Brisbane, but also tried Australia/Sydney and America/Los Angles (this is off the top of my head, I did verify them at the time, and the code mentioned above worked). All by tests were done in the latest docker container.
