### ISSUE TITLE
[Feature Request] Library / Helper Files

### ISSUE THREAD

**Issue by Matchlighter** [AppDaemon/appdaemon#944]
It would be really nice if AppDaemon could support using helper files/libraries located in the appdaemon directory somewhere. I can import other files within the `apps` directory, but I've noticed that doing that is pretty buggy and doesn't reload changes correctly (changes to the library code only take effect when I completely restart ApPDaemon - even forcing the consuming App to module-reload doesn't work).

**Comment by dlashua** [comment]
I think what you're looking for is the "global_modules" feature.

https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#global-module-dependencies

https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html#appdaemon.adapi.ADAPI.depends_on_module
