### ISSUE TITLE
Document on listen_event references state callbacks incorrectly.

### ISSUE THREAD

**Issue by zhaoz** [AppDaemon/appdaemon#945]
https://appdaemon.readthedocs.io/en/latest/APPGUIDE.html#about-event-callbacks has a different signature than https://appdaemon.readthedocs.io/en/latest/AD_API_REFERENCE.html#events

Specifically, the 2nd link references state callbacks for listen_event. This seems to be wrong?

**Comment by dlashua** [comment]
Thanks for finding this! You're right, the documentation links to the wrong place.

@rhumbertgz can you fix this? If not, I can try to unravel your documentation magic to fix it myself.

**Comment by rhumbertgz** [comment]
@dlashua I'll look it
