### ISSUE TITLE
Issue with zigbee timeouts

### ISSUE THREAD

**Issue by jstys** [AppDaemon/appdaemon#960]
I seem to intermittently receive the following log messages for various zigbee devices when attempting to turn on/off via appdaemon:
```
2020-04-13 09:23:51.021106 WARNING AppDaemon: automation_hub: Entity light.ledvance_flex_rgbw_000089d8_1 not found in AppDaemon
```

I'm under the assumption that this means the API call to turn off/on is failing, akin to attempting to toggle the power in the Lovelace UI but a timeout causes the toggle to revert to the original position.  Is this what's happening in this case?

If so, is there a way to more gracefully handle these timeouts with a retry mechanism?  Obviously best case scenario would be to improve the zigbee mesh but I already have many repeaters so probably need some way to have error handling in my appdaemon code in addition.

**Comment by dlashua** [comment]
Usually that means the entity wasn't transmitted from Home Assistant to AppDaemon and you are either trying to get the state of it or listen to the state of it. The warning is telling you that it will listen anyway, but that, as of that moment, that thing doesn't exist.

**Comment by Odianosen25** [comment]
Wil be closing this, pls reopen if needed. Regards
