### ISSUE TITLE
API requests returning 200 even without an access token

### ISSUE THREAD

**Issue by ethank** [AppDaemon/appdaemon#964]
I have "api_key" set in the configuration, but doing a CURL, ie:

curl -i -X POST -H "x-ad-access: fred" -H "Content-Type: application/json" http://192.168.X.X:5050/api/appdaemon/test_endpoint -d '{"type": "Hello World Test"}'

returns a 200, even though I'm not including the key

As well, api_port doesn't seem to be honored? I want to secure this before deployment with Alexa as an endpoint.

**Comment by Odianosen25** [comment]
@ethank,

Where did you place the api key? This should be under the http component, as I am sure it works.

Regards

**Comment by ReneTode** [comment]
it depends on the AD version.

api key is from AD 3, where it works
in AD 4 there is no api_key anymore, it has been replaced by password in the http section.

**Comment by ethank** [comment]
OK, the documentation is still out of date then in 4.0.X documentation. References "api_key" under API Security.

**Comment by ReneTode** [comment]
or you are looking at the wrong docs.
https://appdaemon.readthedocs.io/en/latest/CONFIGURE.html#configuring-the-api

> Configuring the API
The AppDaemon App API is configured by adding a top-level directive to appdaemon.yaml:

> api:
> **It takes no arguments.**

**Comment by ethank** [comment]
Nope, looking at the same docs: https://appdaemon.readthedocs.io/en/4.0.3/APPGUIDE.html#api-security

**Comment by ReneTode** [comment]
yeah indeed that part is incorrect, but it points to how to add the api_key in the configuration part of the docs.
where in the api section is stated that api doesnt take any argument.
