### ISSUE TITLE
Is there a way to access network drive from appdeamon 4

### ISSUE THREAD

**Issue by dibyadip-das** [AppDaemon/appdaemon#983]
I am trying to make an event listening automation where I want to use `shutil `to check for free space on my NAS drive. Is there a way to make it happen?

- I tried to find the network drive right from the code using OS but then I realized everything running inside docker.
- Tired to mount using the init commands in configuration but I cannot mount network drives. Getting permission denied error.

**Comment by Odianosen25** [comment]
@dibyadip-das if your network drive is running Linux, then you could install paramiko python package, which will enable you in AD to run commands in the nas system. Then you can parse the output to get the data you need.

Regards

**Comment by dibyadip-das** [comment]
@Odianosen25 Unfortunately, WD won't allow as my NAS is WD My Cloud Home. Although it runs some version of Linux, I won't be able to perform SSH on it.  `shutil` worked great on my local machine. So, by any means if I could expose the docker container to my network devices or mount the drive inside the docker container I should be able to perform  `shutil`  on it.

**Comment by ReneTode** [comment]
if you cant mount a network drive, i dont think there is any way to access the network drive.
