### ISSUE TITLE
Fontawesome Pro

### ISSUE THREAD

**Issue by ACJUK** [AppDaemon/appdaemon#984]
Hi

I've got a subscription to Fontawesome Pro so I have a big collection of icons that I'd like to use.

What I can't work out is how to use them in my dashboard on appdaemon.

Please could someone point me in the right direction?

Best regards
Andy

**Comment by ReneTode** [comment]
it doesnt matter that you got Pro.
the developer from the website (in this case Andrew) needs to have pro to make it possible to use those icons.

so im sorry to say, but your pro account is only usable if you start changing the appdaemon installation.

**Comment by ACJUK** [comment]
Ok, thank you.  I have managed to get it kind of working.  I ran this:

`docker exec -it addon_a0d7b954_appdaemon /bin/sh`

That enabled me to access the /css directory.  I then uploaded all.css into that directory and I uploaded the webfonts into the compiled/css directory.

This got things working.  I know that restarting appdaemon wipes my version of all.css and I have to copy it back again.  I don't know if there's a way round this.  I'm also not sure what effect putting the webfonts into the compiled/css directory if I need to restart the Pi or when things get upgraded.

For the moment, I'm happy enough that it'll work until it stops.  But at least I should be able to repeat what I did this time.

I'm absolutely over the moon with this so far!

**Comment by ReneTode** [comment]
placing it in the compiled directory isnt the best way, because that is the directory with the temporary files.

the fa webfonts are placed in the dir appdaemon/assets/webfonts.

so you better overwrite that.

i think that should keep it working untill you update AD. (but i dont know enough from docker to be sure)

**Comment by ACJUK** [comment]
At first, I put them in that directory but all I got was a square outline for the icon I wanted.  I tried one of the free ones and that worked but it wouldn't work with the pro ones.  Possibly a cache issue?

And yes, even restarting appdaemon kills it as that resets all.css.  What I might do is just write a tiny script that will cp the file over from a different directory.
