### ISSUE TITLE
add attributes (or: don't delete already existing attributes when setting state)?

### ISSUE THREAD

**Issue by prankousky** [AppDaemon/appdaemon#991]
Hi everybody,

still learning appdaemon, so please excuse me if this is a dumb question...

I have an entity `vacuum.medusa` in Home Assistant with these attributes:

```
battery_level: 93
battery_icon: 'mdi:battery-90'
status: Turbo House Cleaning
clean_start: '2020-06-07 11:04:48'
clean_stop: '2020-06-07 11:27:13'
clean_area: 18.7136
clean_suspension_count: 0
clean_suspension_time: 0
clean_pause_time: 0
clean_error_time: 0
battery_level_at_clean_start: 98
battery_level_at_clean_end: 77
launched_from: app
friendly_name: Medusa
icon: 'mdi:robot-vacuum-variant'
supported_features: 15964
```

Via appdaemon, I want to write `self.set_state(vacuum, state="cleaning", attributes="{"letzter_start": _jetzt}` (vacuum and _jetzt being previously defined variables, letzter_start just meaning last_start in German).

When I do this, the entity will change to 

```
letzter_start: 1591617600.8214695
```

So all attributes that were there, and that I didn't (want to) change, are gone. Is there something like `self.add_attribute(vacuum, attribute={"letzter_start": _jetzt}`? So that the attribute will be added to the existing attributes, rather than overwriting them / deleting them?

And if not, is there a simple way to cache all existing attributes, so that I could just always change the attributes to the same value when I want to write to `letzer_start` so that they will be re-written to their previous values (and therefore, be there instead of deleted)?

Thank you for your help :)

**Comment by ReneTode** [comment]
hi @prankousky 

for questions you can better visit the discord channel, because issues are better left for things that need to be changed or updated.

that said:
setting attributtes on entities that are created by HA is not dependable.
the HA intergration will overwrite it again as soon as the integration updates, and attributes that are added by other things then HA then will dissapear.

and to get attribute states you can use get_state()

**Comment by prankousky** [comment]
Thank you, Rene. Just one last thing: the same will happen if I use an entity that I have created via appdaemon: `sensor.adt_test_time` will lose `letzer_start` if I set a value for attribute `letzter_stop`. The entire attribute will be gone, and only `letzer_stop`will be there until I set_state for `letzter_start` again (which will then make the other attribute disappear again).

**Comment by ReneTode** [comment]
yeah i know, that behaviour did change over time.
i always get the old attributes and set them new.
but i believe the replace argument could be used to change that behaviour. but i didnt test that.
