### ISSUE TITLE
self.get_now() seems to be in UTC rather than local time 

### ISSUE THREAD

**Issue by Krexatex** [AppDaemon/appdaemon#996]
Hi Appdaemon team,
I have migrated recently from Smartthings to Hassio and have been using Appdaemon for my automations. It is quite powerful. Thank you!

I have been, however, encountering issues with apps that the sunrise/sunset time constraints to run at the local times for sunrise and sunset respectively. 
For a example I have the below app to turn on a light at sunset and turn it at sunrise using the run_at_sunrise() and run_at_sunet() methods
`import hassapi as hass

class OutsideLights(hass.Hass):

  def initialize(self):
    self.run_at_sunrise(self.sunrise)
    self.run_at_sunset(self.sunset)
    self.light = self.args['light']

  def sunrise(self, kwargs):
    self.turn_off(self.light)

  def sunset(self, kwargs):
    self.turn_on(self.light)`

The apps.yaml entry looks like this: 
`#Balcony light on at sunset and off at sunrise
balcony_sunset:
  module: sunset
  class: OutsideLights
  light: switch.balcony_light`

It never runs at the expected times, so I set you to find why is that and noticed that when I log self.get_now(), I see the time in UTC, however documentation suggest it should be running in my local time. 
Here is the app I used to test it and it's corresponding apps.yaml entry:
`import hassapi as hass
import datetime

class TimeTest(hass.Hass):

  def initialize(self):
    self.sensor = self.args['sensor']
    self.listen_state(self.time_logs, self.sensor, new='on')

  def time_logs(self, entity, attribute, old, new, kwargs):
    self.log('get_now() time: %s', self.get_now())
    self.log('Next Sunset: %s', self.sunset())
    self.log('Next Sunrise: %s', self.sunrise())
    self.log('datetime time: %s', datetime.datetime.now())`

`# Time test
appdaemon_time:
  module: test_time
  class: TimeTest
  sensor: group.office_motion`

The logs from the app show get_now() in UTC while datetime show the correct local time:
`2020-06-27 14:44:26.180592 INFO appdaemon_time: get_now() time: 2020-06-27 20:44:26.175505+00:00
2020-06-27 14:44:26.184830 INFO appdaemon_time: Next Sunset: 2020-06-28 06:36:23
2020-06-27 14:44:26.188902 INFO appdaemon_time: Next Sunrise: 2020-06-27 15:29:30
2020-06-27 14:44:26.192169 INFO appdaemon_time: datetime time: 2020-06-27 14:44:26.189522`

I've made sure the time on the Raspberry pi and HA are correct. 
I've also updated appdaemon.yaml to have my location data and timezone:
appdaemon:
  latitude: 39.9205
  longitude: 105.0867
  elevation: 1652
  time_zone: America/Denver
  plugins:
    HASS:
      type: hass

**Comment by ReneTode** [comment]
do you have spaces before latitude, etc?
because we cant tell from what you post.

**Comment by Krexatex** [comment]
Sorry, the code block didn't work as intended, but, yes I have a space in front of latitude.
See attached screenshot
![Screen Shot 2020-06-27 at 8 49 03 PM](https://user-images.githubusercontent.com/27723274/85936444-36bbec00-b8b8-11ea-82eb-5ffb7338cdc1.png)

**Comment by ReneTode** [comment]
i thought the issue was closed but this ir related to this open issue
https://github.com/home-assistant/appdaemon/issues/889

**Comment by Odianosen25** [comment]
Actually @Krexatex,`get_now` is a non-tz aware time, thereby  using UTC while `datatime` is aware. So if you want your local time, do use `self.datetime` and not `self.get_now`. Also fell into that recently, but its intentionally designed that way.

Regards

**Comment by ReneTode** [comment]
@Odianosen25 if get_now is designed to be unaware from the timezone, then the docs are completele wrong.

**Comment by Krexatex** [comment]
@Odianosen25 As Rene mentioned, documentation says get_now should be in local date and time. 
See below:
![Screen Shot 2020-06-29 at 11 25 53 AM](https://user-images.githubusercontent.com/27723274/86036764-98d13a00-b9fb-11ea-9009-72fb090b575e.png)

@ReneTode [#889](https://github.com/home-assistant/appdaemon/issues/889) seems to be my exact problem.

**Comment by ReneTode** [comment]
just use self.datetime for the local time.
the other stuff will be figured out.

**Comment by Odianosen25** [comment]
@ReneTode I agree, and I honestly just found that out recently. @acockburn can better explain.

**Comment by ReneTode** [comment]
and allthough the self.sunset and the self.sunrise can give the wrong time, 
self.run_at_sunset() and self.run_at_sunrise() should work as expected when the environment is correct.

i use those myself on daily basis and never have trouble with them.

and for self.sunset and sunrise you need to use
```
self.sunset(aware = True)
```
to let it return the timezone aware time.

**Comment by thethereza** [comment]
looks like this bug still exists.

**Comment by Odianosen25** [comment]
Ok this is fixed
